### ISSUE TITLE
Double freeing security and server objects in client test app

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#109]
My setup:
I'm using the latest (git from 11.03.) lwm2mclient with a leshan server+bootstrap server. I register/unregister the client several times from the server and also reinitilize the client with bootstrap from time to time.

The error with memtrace enabled:
```
lwm2m_step() failed: 0xA3
[BOOTSTRAP] restore security and server objects
memory: free error (no malloc) /home/david/wakaama/tests/client/object_security.c, 501, free_security_object
memory: already frees at /home/david/wakaama/tests/client/object_security.c, 501, free_security_object
memory: free error (no malloc) /home/david/wakaama/tests/client/object_server.c, 450, free_server_object
memory: already frees at /home/david/wakaama/tests/client/object_server.c, 450, free_server_object
[BOOTSTRAP] ObjectList restored
```

And after looking into the code I actually have problems to understand `void prv_restore_objects(lwm2m_context_t * context)` in **lwm2mclient.c**. You first call `free_security_object(object)` which as last statement calls `lwm2m_free(object)`. So the object pointer is invalid from this point on. After that you call `copy_security_object(object, backup_object)` which tries to do a **memcpy** to this (in my opinion) invalid pointer. Did I overlooked something?

**Comment by dnav** [comment]
Thank you for spotting this.
Fixed by #112.

Regards
