### ISSUE TITLE
Test client: object_firmware.c. Wrong return type for RES_O_UPDATE_SUPPORTED_OPJECTS

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#110]
Two issues:
* I guess it should read RES_O_UPDATE_SUPPORTED_O**B**JECTS :-)
* Around line 111:
```
        case RES_O_UPDATE_SUPPORTED_OPJECTS:
            lwm2m_data_encode_int(data->supported, *dataArrayP + i);
            (*dataArrayP)[i].type = LWM2M_TYPE_RESOURCE;

            if (0 != (*dataArrayP)[i].length) result = COAP_205_CONTENT;
            else result = COAP_500_INTERNAL_SERVER_ERROR;

            break;
```
Should be lwm2m_data_encode_bool instead of lwm2m_data_encode_int according to specification [OMA-SUP-XML_LWM2M_Firmware_Update-V1_0-20131210-C.txt](http://technical.openmobilealliance.org/Technical/Release_Program/docs/LightweightM2M/V1_0-20151214-C/OMA-SUP-XML_LWM2M_Firmware_Update-V1_0-20131210-C.txt)

**Comment by dnav** [comment]
Indeed. Fixed by #111.
