### ISSUE TITLE
suggestion：keep maintain tests/client and merge tests/securityclient in it

### ISSUE THREAD

**Issue by ieei0214** [eclipse/wakaama#113]
Hi,

Since tinydtls is sub module of wakaama, do we still need two client demo?

Actually in my local copy I already merge tests/securityclient into tests/client because tests/client has more  features in it.

It's easier for maintain and bug fix.  We may use define dtls feature in tests/client.

Thanks.

**Comment by dnav** [comment]
I agree.
Let's wait for #114 to be merged first.

**Comment by dnav** [comment]
Resolved by #122
