### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by ericyao2013** [eclipse/wakaama#119]
I think some source code may be cause a memory leak problem in the file "object_device.c".
It will free 'deviceObj' and return 'NULL' if malloc memory for 'userData' failure.
But it doesn't  free 'deviceObj->instanceList' memory ....

		/*
		 * Also some user data can be stored in the object with a private structure containing the needed variables 
		 */
		if (NULL != deviceObj->userData)
		{
			((device_data_t*) deviceObj->userData)->battery_level = PRV_BATTERY_LEVEL;
			((device_data_t*) deviceObj->userData)->free_memory = PRV_MEMORY_FREE;
			((device_data_t*) deviceObj->userData)->error = PRV_ERROR_CODE;
			((device_data_t*) deviceObj->userData)->time = 1367491215;
			strcpy(((device_data_t*) deviceObj->userData)->time_offset, "+01:00");
		}
		else
		{
                        //@Fixme: lwm2m_free(objectP->instanceList);  objectP->instanceList = NULL;
			lwm2m_free(deviceObj);
			deviceObj = NULL;
		}

**Comment by dnav** [comment]
Indeed.
I will fix this.

**Comment by dnav** [comment]
Fixed by #123
