### ISSUE TITLE
Buildsystem/IDE: Also list header files

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#127]
All IDEs that I know of, which support cmake as a buildsystem or consume a cmake generated project, require the header files also to be listed for the add_executable call. This affects: QtCreator, Visual Studio, XCode.

At the moment all examples repeat the source list of
- the platform
- tinydtls (if applicable).

I propose to create a cmake file for the platform and and tinydtls each and let those files be included by the example and test projects. That would also be consistent with how the core sources files are listed and included.

**Comment by dnav** [comment]
Fixed by #128
