### ISSUE TITLE
Manually "bootstraping" after security object is registered

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#129]
According to http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/bootstrapmodes.htm a client may bootstrap itself by using a boostrap server, a smartcard or using factory bootstrap information.

In the examples this is done by setting up the server address in the security object and calling ``lwm2m_configure``. 

If you have to wait for factory bootstrap information to be available for one or another reason,
what is the correct way to provide it to wakaama, after ``lwm2m_configure`` has been called?

The AwaLWM2M implementation provides a ``AwaStaticClient_SetFactoryBootstrapInformation`` in https://github.com/FlowM2M/AwaLWM2M/blob/master/api/include/awa/static.h#L299 for exactly this case. It that already possible or should wakaama support something similar, too?

**Comment by boaks** [comment]
LWM2M TS V1_0 20160308, 5.2.2.1
„In this mode, the LWM2M Client has been configured with the necessary Bootstrap Information prior to deployment of the device.“

If the client has been configured prior to deployment, I'm not sure, why "lwm2m_configure" should be called before.

May be the term "factory bootstrap" could be interpreted in different ways. But if you want a clarification on that, just use
the OMA issue page (https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues). 

Mit freundlichen Grüßen / Best regards

Achim Kraus

Bosch Software Innovations GmbH
Communications (INST/ESY1)
Stuttgarter Straße 130
71332 Waiblingen
GERMANY
www.bosch-si.de
www.blog.bosch-si.com 

Registered office: Berlin, Register court: Amtsgericht Charlottenburg, HRB 148411 B
Executives: Dr.-Ing. Rainer Kallenbach; Michael Hahn


Von: David Gräff [mailto:notifications@github.com] 
Gesendet: Dienstag, 29. März 2016 12:53
An: eclipse/wakaama
Betreff: [eclipse/wakaama] Manually "bootstraping" after security object is registered (#129)

According to http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/bootstrapmodes.htm a client may bootstrap itself by using a boostrap server, a smartcard or using factory bootstrap information.
In the examples this is done by setting up the server address in the security object and calling lwm2m_configure. 
If you have to wait for factory bootstrap information to be available for one or another reason,
what is the correct way to provide it to wakaama, after lwm2m_configure has been called?
The AwaLWM2M implementation provides a AwaStaticClient_SetFactoryBootstrapInformation in https://github.com/FlowM2M/AwaLWM2M/blob/master/api/include/awa/static.h#L299 for exactly this case. It that already possible or should wakaama support something similar, too?

**Comment by dnav** [comment]
Keep in mind wakaama is not multi-threaded.
When calling lwm2m_step(), if you do not have any server information (bootstrap or LWM2M server), the internal state machine will stay in STATE_BOOTSTRAP_REQUIRED and lwm2m_step() will return COAP_503_SERVICE_UNAVAILABLE. 
When factory bootstrap information are available, wakaama will retrieve them from the Security Object lwm2m_object_t.

In your case, it is only a matter of handling the return code of lwm2m_step() accordingly.

Regards,
