### ISSUE TITLE
bug: lwm2mclient.c,   with tinydtls   Pre-Shared-Key option  error, in print_usage function.

### ISSUE THREAD

**Issue by liuxiyu** [eclipse/wakaama#140]
in lwm2mclient.c

#ifdef WITH_TINYDTLS    
      fprintf(stdout, "  -p HEXSTRING\tSet the device management or bootstrap server Pre-Shared-Key. If not set use none secure mode\r\n");    
#endif

Should be

#ifdef WITH_TINYDTLS    
       fprintf(stdout, "  -s HEXSTRING\tSet the device management or bootstrap server Pre-Shared-Key. If not set use none secure mode\r\n");    
#endif

**Comment by dnav** [comment]
Thank you, I ninja-fixed this in #139

**Comment by dnav** [comment]
Fixed in #139
