### ISSUE TITLE
Missing Test Object instance when using lwm2mclient in bootstrap mode

### ISSUE THREAD

**Issue by vibhorkalley** [eclipse/wakaama#141]
Test Object /1024 and/or resources cannot be read/write after bootstrapping.
Once the bootstrapping is done and the client tries to register to the leshan demo server, the register message does not contain instances to test object </1024>. Whereas in regular mode the wakaama client registers with instance ids also </1024/10>,</1024/11>,</1024/12> . Is this a bug in wakaama client ? Also the output of the >disp command doesn't print any instances unlike non-bootstrap mode.

Wakaama Client registered after bootstrapping
>Sending 125 bytes to [10.64.98.70]:5683
44 02 34 4D  4D 34 50 7D  B2 72 64 11  28 3D 05 65   D.4MM4P}.rd.(=.e
70 3D 74 65  73 74 6C 77  6D 32 6D 63  6C 69 65 6E   p=testlwm2mclien
74 03 62 3D  55 05 6C 74  3D 32 30 FF  3C 2F 3E 3B   t.b=U.lt=20.</>;
72 74 3D 22  6F 6D 61 2E  6C 77 6D 32  6D 22 3B 63   rt="oma.lwm2m";c
74 3D 31 35  34 33 2C 3C  2F 31 2F 30  3E 2C 3C 2F   t=1543,</1/0>,</
33 2F 30 3E  2C 3C 2F 35  2F 30 3E 2C  3C 2F 36 2F   3/0>,</5/0>,</6/
30 3E 2C 3C  2F 31 30 32  34 3E 2C 3C  2F 34 2F 30   0>,</1024>,</4/0
3E 2C 3C 2F  37 2F 30 3E  2C 3C 2F 32  3E            >,</7/0>,</2>

> disp
  /0: Security object, instances:
    /0/0: instanceId: 0, uri: coap://10.64.98.70:5683, isBootstrap: true, shortId: 111, clientHoldOffTime: 1
    /0/1: instanceId: 1, uri: coap://10.64.98.70:5683, isBootstrap: false, shortId: 123, clientHoldOffTime: 1
  /1: Server object, instances:
    /1/0: instanceId: 0, shortServerId: 123, lifetime: 20, storing: true, binding: U
  /3: Device object:
    time: 1367491215, time_offset: +01:00
  /5: Firmware object:
    state: 1, supported: false, result: 0
  /6: Location object:
    latitude: 27.986065, longitude: 86.922623, altitude: 8495.0000, uncertainty: 0.01, timestamp: 1460174150
  /1024: Test object, instances:

Wakaama Client without bootstrapping
>Sending 153 bytes to [10.64.98.70]:5683
44 02 E1 0B  0B E1 C1 7D  B2 72 64 11  28 3D 05 65   D......}.rd.(=.e
70 3D 74 65  73 74 6C 77  6D 32 6D 63  6C 69 65 6E   p=testlwm2mclien
74 03 62 3D  55 06 6C 74  3D 33 30 30  FF 3C 2F 3E   t.b=U.lt=300.</>
3B 72 74 3D  22 6F 6D 61  2E 6C 77 6D  32 6D 22 3B   ;rt="oma.lwm2m";
63 74 3D 31  35 34 33 2C  3C 2F 31 2F  30 3E 2C 3C   ct=1543,</1/0>,<
2F 33 2F 30  3E 2C 3C 2F  35 2F 30 3E  2C 3C 2F 36   /3/0>,</5/0>,</6
2F 30 3E 2C  3C 2F 31 30  32 34 2F 31  30 3E 2C 3C   /0>,</1024/10>,<
2F 31 30 32  34 2F 31 31  3E 2C 3C 2F  31 30 32 34   /1024/11>,</1024
2F 31 32 3E  2C 3C 2F 34  2F 30 3E 2C  3C 2F 37 2F   /12>,</4/0>,</7/
30 3E 2C 3C  2F 32 2F 30  3E                         0>,</2/0>

> disp
  /0: Security object, instances:
    /0/0: instanceId: 0, uri: coap://10.64.98.70:5683, isBootstrap: false, shortId: 123, clientHoldOffTime: 10
  /1: Server object, instances:
    /1/0: instanceId: 0, shortServerId: 123, lifetime: 300, storing: false, binding: U
  /3: Device object:
    time: 1367491215, time_offset: +01:00
  /5: Firmware object:
    state: 1, supported: false, result: 0
  /6: Location object:
    latitude: 27.986065, longitude: 86.922623, altitude: 8495.0000, uncertainty: 0.01, timestamp: 1460174273
  /1024: Test object, instances:
    /1024/10: shortId: 10, test: 20
    /1024/11: shortId: 11, test: 21
    /1024/12: shortId: 12, test: 22

**Comment by dnav** [comment]
Hi,

This is the expected behavior: during the bootstrap process, the Bootstrap Server deletes all instances of objects. In the examples client, only the test object implements deletion. Thus the result you observe where the 1024 object has no instances whereas other objects still have theirs.

Regards
