### ISSUE TITLE
TLV format for single instance resource

### ISSUE THREAD

**Issue by sbernard31** [eclipse/wakaama#145]
The recent versions of the spec say now TLV can be used for single resources.

> "The LWM2M Client MUST support the TLV data format for all
requests." (§6.3 Data Formats for Transferring Resource Information)

(There is a [PR](https://github.com/eclipse/leshan/pull/118) in Leshan which implements this)

**Comment by dnav** [comment]
Thanks for pointing this.

Currently for single resource request, the client can encode the data using TLV if the CoAP GET message content type is application/vnd.oma.lwm2m+tlv. If there is no content type specified, the client uses plain text by default.
On the server-side, the API does not allow to specify the content-type. I'll rework this part.

Regards,
