### ISSUE TITLE
Could the wakaama client bootstrap from leshan bootstrap server ?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#148]
I tried bootstrapping wakaama client( DTLS disabled lwm2mclient ) with leshan bootstrap server. But it is failing. Attached [logs](https://github.com/eclipse/wakaama/files/248549/bootstrap.txt). The commands used are below. Is the way of invoking wakaama client wrong or is bootstrapping wakaama not yet a complete feature ?

```
java -jar leshan-bsserver-demo-0.1.11-M9-jar-with-dependencies.jar 
java -jar leshan-server-demo-0.1.11-M9-jar-with-dependencies.jar -lp 5783 -slp 5784 -wp 8082
./lwm2mclient -4 -n Kochi -p 5683 -b
```
Entry corresponding to Kochi were added in Bootstrap server. If I don't use the bootstrap part, the client successfully registers with device management server( with or without PSK). Of lesser importance: I also tried building/running the wakaama bootstrap server. But it seg faults. I assume it is no more being used.

**Comment by boaks** [comment]
Hi Kiran,

which version of leshan you’re using?
Is it a new one, which stores the bootstrap information in json?
If so could you provide the bootstrap json information?

As far as I understood the wakaama log, the client successfully
Started the bootstratp and got two security and one server object(s).
But in the end, it fails to validate the received information.
Therefore it would be easier to understand this, if you can provide
the bootstrap information in a readable format.

Mit freundlichen Grüßen / Best regards

Achim Kraus

Bosch Software Innovations GmbH
Communications (INST/ESY1)
Stuttgarter Straße 130
71332 Waiblingen
GERMANY
www.bosch-si.de
www.blog.bosch-si.com<http://www.blog.bosch-si.com>


Registered office: Berlin, Register court: Amtsgericht Charlottenburg, HRB 148411 B
Executives: Dr.-Ing. Rainer Kallenbach; Michael Hahn


Von: Kiran Pradeep [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. Mai 2016 12:15
An: eclipse/wakaama
Betreff: [eclipse/wakaama] Is the wakaama boostrap client working ? (#148)


I tried bootstrapping wakaama client( DTLS disabled lwm2mclient ) with leshan bootstrap server. But it is failing. Attached logs<https://github.com/eclipse/wakaama/files/248549/bootstrap.txt>. The commands used are below. Is the way of invoking wakaama client wrong or is bootstrapping wakaama not yet a complete feature ?

java -jar leshan-bsserver-demo-0.1.11-M9-jar-with-dependencies.jar

java -jar leshan-server-demo-0.1.11-M9-jar-with-dependencies.jar -lp 5783 -slp 5784 -wp 8082

./lwm2mclient -4 -n Kochi -p 5683 -b

Entry corresponding to Kochi were added in Bootstrap server. Of lesser importance: I also tried building/running the wakaama bootstrap server. But it seg faults. I assume it is no more being used.

**Comment by dnav** [comment]
Hi Kiran,

It appears the master branch lwm2mclient example has a bug in its server object. I'm fixing this right now.
Regarding the bootstrap server, it is still of use (at least by me). The master branch is missing a small fix. I'm correcting this also.

Sorry for the inconvenience,
I nee to clean up my too many local branches...

**Comment by kiranpradeep** [comment]
David and Achim, Thanks for the both fix and wakaama project.
