### ISSUE TITLE
Will wakaama client work for non debug builds ?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#150]
I was trying a non debug (`cmake ../client`) build of wakaama client. The debug build(`cmake ../client -DCMAKE_BUILD_TYPE=Debug`) of wakaama client registers successfully with device management server( leshan server). But the non debug client registration fails. Attaching [logs](https://github.com/eclipse/wakaama/files/250303/release.txt)

Build system: Ubuntu14.04 LTS, cmake 3.5.2, gcc 4.8.4, GNU Make 3.81)
I also tried the same on mac os x with same results.
Build system: OSX 10.11, cmake 3.5.2, Apple LLVM version 7.3.0, GNU Make 3.81)

Is the release build a work in progress ? Or am I doing any thing wrong with the build process ? I could add add any missing information on need.

**Comment by dnav** [comment]
Hi,
As of today I can not reproduce your issue with the current master branch.
In your logs, I can see that leshan is sending your client a registration location, meaning your client is registered. Have you check on the leshan web UI ?
Note that the release version does not display the "=> REGISTERED" message.

Regards

**Comment by kiranpradeep** [comment]
I am in front of a work PC right now. But I remember checking leshan UI and didn't see the client registered for release builds( both on mac and ubunutu). Is there any thing else I can do to enable more logs( on release builds ) or any thing that will help ?

**Comment by kiranpradeep** [comment]
@dnav Really sorry about wasting your time. As you said, client was getting registered and it was just that it didn't show the registered message.

**Comment by dnav** [comment]
No problem
