### ISSUE TITLE
IPv6 not working for DTLS enabled non debug builds

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#159]
IPv6 works well for non DTLS builds. But for non debug builds with DTLS enabled, IPv6 fails to register with leshan device management server. Commands used
```
cmake -DDTLS=1 ../client/ -DCMAKE_BUILD_TYPE=Release
make
```
Logs [attached](https://github.com/eclipse/wakaama/files/294895/ipv6.txt)
Note: IPv6 works for DTLS debug builds.
Code is in sync with wakaama/master.
Compiler: Apple LLVM version 7.3.0 (clang-703.0.29)

**Comment by dnav** [comment]
Hi,
It is actually any build without LOGS that fails with the same error. Even Debug IPv4 non-DTLS...
I'm looking at this.

**Comment by dnav** [comment]
It seems #193 fixed this issue.
Could you try on your set-up ?

Regards
