### ISSUE TITLE
Higher level queue really needed when many requests from LWM2M server?

### ISSUE THREAD

**Issue by mlindstedt** [eclipse/wakaama#161]
Hi,

I've implemented wakamaa server in a project. However if the server at the same time on the same objectId and instanceId:
1) request observation on resourceId 1 on client side
2) makes a read on resourceId 2 on client side
3) makes a write to resourceId 3 on client side
then it seems like Wakamaa can't handle 3 requests, i.e it sends back an response from the client on the obervation request, but no response on the others.

Is it necessary to add a queue on a higher level on the server-side, so the client can cope without being choked. But isn't there a queue mechanism already inside of the Wakamaa protocol, or have I misunderstood the implementation?

Is it only me who need to make many requests? Are other people adding sleep(X) seconds between each request, or how are you using this protocol? All ideas/suggestions are welcome.

Best regards Magnus Lindstedt

**Comment by dnav** [comment]
Hi,

I just reproduced your experiment with the current wakaama client and server and it worked fine.
In  lwm2mserver.c I added this function:
```
static void prv_stress_client(char * buffer,
                              void * user_data)
{
    lwm2m_context_t * lwm2mH = (lwm2m_context_t *)user_data;
    lwm2m_uri_t uri;
    int result;

    uri.flag = LWM2M_URI_FLAG_OBJECT_ID | LWM2M_URI_FLAG_INSTANCE_ID | LWM2M_URI_FLAG_RESOURCE_ID;
    uri.objectId = 3;
    uri.instanceId = 0;
    uri.resourceId = 0;
    result = lwm2m_observe(lwm2mH, 0, &uri, prv_notify_callback, NULL);

    uri.resourceId = 1;
    result = lwm2m_dm_read(lwm2mH, 0, &uri, prv_result_callback, NULL);

    uri.resourceId = 13;
    result = lwm2m_dm_write(lwm2mH, 0, &uri, LWM2M_CONTENT_TEXT, "12", 2, prv_result_callback, NULL);
}
```
And I got the three answers from the client:
```
Notify from client #0 /3/0/0 number 0
    20 bytes received of type text/plain:
    4F 70 65 6E  20 4D 6F 62  69 6C 65 20  41 6C 6C 69   Open Mobile Alli
    61 6E 63 65                                          ance

Client #0 /3/0/1 : 2.05 (COAP_205_CONTENT)
    22 bytes received of type text/plain:
    4C 69 67 68  74 77 65 69  67 68 74 20  4D 32 4D 20   Lightweight M2M 
    43 6C 69 65  6E 74                                   Client

Client #0 /3/0/13 : 2.04 (COAP_204_CHANGED)
```

Could you check on the network level if messages are received and sent on both side ?

Regards,

**Comment by mlindstedt** [comment]
@dnav thanks for the reply!

My mistake, the LWM2M server seems to be doing fine. It seems to be problems on the LWM2M client-side, it seems to crash. As soon as I send 3 requests at same time, client seems to choke. If I send 2 requests at a time, client sometimes work, sometimes crash. If I send 1 request at a time from server to client, then everything seems to be working fine.

Not sure how client is implemented, i.e if it uses Wakamaa, Leishan or something else. I will see if I can find a different client that I can try to connect to and/or create a LWM2M client on my own.

I will close this issue. Once again, thanks for your help.
