### ISSUE TITLE
Case value not in enumerated type coap_content_type_t

### ISSUE THREAD

**Issue by mlindstedt** [eclipse/wakaama#165]
Hi,

I've been trying out Wakamaa implementation and found a strange thing that the Xcode compiler warns about (yes, i'm running native-c code inside swift and it works fine).

In core/utils.c there is a function:
`lwm2m_media_type_t utils_convertMediaType(coap_content_type_t type)`
which checks **LWM2M_CONTENT_TLV** and **LWM2M_CONTENT_JSON**, but those two cases are not part of enum **lwm2m_media_type_t**. Why are there printouts? Wouldn't it be better instead to either add those to the enum or remove the two cases?

`

    switch(type) {

    case TEXT_PLAIN:
        return LWM2M_CONTENT_TEXT;

    case APPLICATION_OCTET_STREAM:
        return LWM2M_CONTENT_OPAQUE;

    case LWM2M_CONTENT_TLV:
        // print if compiler warning occur
        LOG("ERROR: Case value LWM2M_CONTENT_TLV, not in enumerated type: %d\r\n", type);
        return LWM2M_CONTENT_TLV;

    case LWM2M_CONTENT_JSON:
        // print if compiler warning occur
        LOG("ERROR: Case value LWM2M_CONTENT_JSON, not in enumerated type: %d\r\n", type);
        return LWM2M_CONTENT_JSON;

    case APPLICATION_LINK_FORMAT:
        return LWM2M_CONTENT_LINK;

    default:
        return LWM2M_CONTENT_TEXT;
    }
`

**Comment by dnav** [comment]
Hi,

This function is used to check that the content format of the CoAP payload is handled by the LWM2M stack. In CoAP, the content type is an unsigned 16-bit integer.
coap_content_type_t and  lwm2m_media_type_t enums are actually used as defines. And I did not expend the original coap_content_type_t enum with the new values defined for LWM2M.
This warning is legit but I chose to consider it harmless.
Once the LWM2M content format values are registered with IANA, I will rework this part.

Regards,

**Comment by mlindstedt** [comment]
OK! And thanks for very quick answer!

I am satisfied with the answer, the warnings are harmless and there are ERROR-printouts in case they occur as well.

So, do you keep track of making this rework somewhere, so I can close this issue, or shall I keep my issue open until you've made the reworked?

Also do you have an idea when IANA will have registered the LWM2M content format? Within a month, 3 months, a year?

**Comment by dnav** [comment]
You're welcome.
I would say it is a matter of months. 3 to 6 IMHO.

**Comment by mlindstedt** [comment]
Ok @dnav 

Do you want me to close this issue?

**Comment by jpradocueva** [comment]
The following MIME type has been already registered with [IANA](http://www.iana.org/assignments/media-types/media-types.xhtml):
* application/vnd.oma.lwm2m+json.

The following MIME type: **application/vnd.oma.lwm2m+tlv**   is still pending registration but it will take just a couple of weeks.
