### ISSUE TITLE
Shall it be possible to observe same value twice?

### ISSUE THREAD

**Issue by mlindstedt** [eclipse/wakaama#166]
Hi,

sorry to bother again, with a new question. I've run into another question, that maybe someone knows the answer to?

Let's say the LWM2M server tells a LWM2M client that it wants to observe for example /3/0/0. And lets say server then stupidly doesn't keep track of what it is doing and requests an observe on the same value towards the LWM2M client again.

According to code in lwm2m_observe() function in core/observe.c, I can't see that there is a check to NOT observe on the same value again (neither lwm2m_list_newId or LWM2M_LIST_ADD does a check). Is that correct behaviour? What's the reason for being able to add multiple observations on same value? Is it because the observe callback could be to another function? Does anyone know?

`
int lwm2m_observe(lwm2m_context_t * contextP,

                  uint16_t clientID,
                  lwm2m_uri_t * uriP,
                  lwm2m_result_callback_t callback,
                  void * userData) {
    lwm2m_client_t * clientP;
    lwm2m_transaction_t * transactionP;
    lwm2m_observation_t * observationP;
    uint8_t token[4];

    if (!LWM2M_URI_IS_SET_INSTANCE(uriP) && LWM2M_URI_IS_SET_RESOURCE(uriP)) return COAP_400_BAD_REQUEST;

    clientP = (lwm2m_client_t *)lwm2m_list_find((lwm2m_list_t *)contextP->clientList, clientID);
    if (clientP == NULL) return COAP_404_NOT_FOUND;

    observationP = (lwm2m_observation_t *)lwm2m_malloc(sizeof(lwm2m_observation_t));
    if (observationP == NULL) return COAP_500_INTERNAL_SERVER_ERROR;
    memset(observationP, 0, sizeof(lwm2m_observation_t));

    observationP->id = lwm2m_list_newId((lwm2m_list_t *)clientP->observationList);
    memcpy(&observationP->uri, uriP, sizeof(lwm2m_uri_t));
    observationP->clientP = clientP;
    observationP->status = STATE_REG_PENDING;
    observationP->callback = callback;
    observationP->userData = userData;

    token[0] = clientP->internalID >> 8;
    token[1] = clientP->internalID & 0xFF;
    token[2] = observationP->id >> 8;
    token[3] = observationP->id & 0xFF;

    transactionP = transaction_new(COAP_TYPE_CON, COAP_GET, clientP->altPath, uriP, contextP->nextMID++, 4, token, ENDPOINT_CLIENT, (void *)clientP);
    if (transactionP == NULL)
    {
        lwm2m_free(observationP);
        return COAP_500_INTERNAL_SERVER_ERROR;
    }

    observationP->clientP->observationList = (lwm2m_observation_t *)LWM2M_LIST_ADD(observationP->clientP->observationList, observationP);

    coap_set_header_observe(transactionP->message, 0);
    coap_set_header_token(transactionP->message, token, sizeof(token));

    transactionP->callback = prv_obsRequestCallback;
    transactionP->userData = (void *)observationP;

    contextP->transactionList = (lwm2m_transaction_t *)LWM2M_LIST_ADD(contextP->transactionList, transactionP);

    return transaction_send(contextP, transactionP);
}
`

**Comment by dnav** [comment]
Short answer: Yes it should.

Please have a look to observe_handleRequest() in observe.c. The `case 0:` is for observation request.
wakaama starts by creating a lwm2m_watcher_t matching the URI and the server. In your use case, the lwm2m_watcher_t already exists and wakaama overwrites its data (token, time, last value). Thus the previous observation "disappears" and wakaama only knows of the new observation.

Regards,

**Comment by mlindstedt** [comment]
Sorry for late reply, I've been on vacation.

Very good answer! Thanks, I'll close issue.
