### ISSUE TITLE
Should wakaama client tries to register if an update registration fails ?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#167]
With Wakaama client, a single failed registration or failed update registration, stops the client. However, Wakaama behaves differently with a failed bootstrap, by retrying till it successfully bootstraps. 

In Leshan LWM2M client, on a failed update registration, client tries to register, and further failures takes it to bootstrap server. Kindly see UpdateRegistrationTask([1](https://github.com/eclipse/leshan/blob/leshan-0.1.11-M10/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/RegistrationEngine.java#L268)). 

I understand this is a conscious design decision taken, but this burdens the application developer. From my narrow perspective, any Wakaama user, would like the Leshan route. Is there any class of application developers benefiting from this kind of a decision and would like to know the reasoning behind this decision?

**Comment by kiranpradeep** [comment]
Copy pasting dnav's reply from closed thread([2](https://github.com/eclipse/wakaama/issues/156)):

>  If the a server is not available (registration or update failed), it is ignored to avoid infinte loop of registration.
> 
> I need to re-work the behavior in case of failed registration update. For now, a failed registration does not impact the state machine. But the behavior should be the same as a failed registration.
> The lib user should indeed inspect the context status and each server status to determine what to do when the lwm2m_step() function returns an error.

**Comment by dnav** [comment]
In #172, I make the behaviors for failed registration and failed registration update consistent.
Now the client returns to the `STATE_BOOTSTRAP_REQUIRED` state.
If there is no declared LWM2M Bootstrap Server or if wakkama was not compiled with the bootstrap support, `lwm2m_step()` will return `COAP_503_SERVICE_UNAVAILABLE`.
In this case, the client application can either provide new servers or reset the state to `STATE_INITIAL`.

**Comment by kiranpradeep** [comment]
A query: Wouldn't it be better if state moves to `STATE_REGISTER_REQUIRED` on an update registration failure ? In addition to lifetime update, update registration will be frequently used to keep the nat route alive ( < 180 seconds ). If on mobile network reception, there is a high chance of update registration failure once a while. Also for IP changes on a wake after sleep.

All of the above does only need a registration and not a bootstrap. It is a query only and like to know your thought.

**Comment by rpozza** [comment]
Another query: I might be wrong but it appears that in registration_step on STATE_REG_FAILED the connection gets closed.
Does this means that on step above the connection needs to be reopened?

**Comment by dnav** [comment]
@kiranpradeep PR #172 just makes the behavior consistent in case of all server (update) registration failing.
It is is open for debate on what to do exactly. Note that CoAP already does several retries. IMHO this should be left to the application to avoid infinte loop.

@rpozza Yes the connection gets closed. Then it is reopened by a call to lwm2m_connect_server().
