### ISSUE TITLE
lwm2m_resource_value_changed and lwm2m_step timeout

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#168]
Assuming wakaama user is invoking _lwm2m_resource_value_changed_ in a background thread, for the response to be sent to device management server, the _lwm2m_step_ timeout has to expire / wait for data from server. In order to avoid this wait, could wakaama consider adding a _lwm2m*_ method, which the user could invoke, to get out of the _lwm2m_step_ timeout ? Or any alternative plan which helps the lwm2m observer to notified as early as possible.

**Comment by dnav** [comment]
I'm not sure to understand your request. lwm2m_step() is not a blocking function. The timeout it returns is an information for the application. It is the maximal time, the application can wait before calling lwm2m_step() again. For instance, because wakaama needs to re-transmit a message.
If you look at the example/client/lwm2mclient.c, you'll see that the client is blocked by a select() not by lwm2m_step().

Regards,

**Comment by kiranpradeep** [comment]
I was wrong. Yes it `select` and not `lwm2m_step()`. Also, I also had a wrong view that _lwm2mclient.c_ in examples was part of library and not a demo implementation. I see it is a demo implementation now.

A query: Assuming we use wakaama with multiple threads - let's say we started a thread for firmware or software download and would like to notify observer on download complete. I understand we need to call `lwm2m_resource_value_changed` on appropriate download or state resource once download is complete. Will this kind of implementation need an immediate call to `lwm2m_step()` after `lwm2m_resource_value_changed` call to  for the observer to be notified ? Currently the `select()` blocks and and notification is sent only after select timeouts and next `lwm2m_step()` is invoked.

The reason for this query came since I was using Leshan where a resource change only needed a simple fireResourceChange([1](https://github.com/eclipse/leshan/blob/leshan-0.1.11-M10/leshan-client-demo/src/main/java/org/eclipse/leshan/client/demo/MyLocation.java#L62)). Of course that has the support of Java system.

**Comment by dnav** [comment]
A call to `lwm2m_resource_value_changed()` does not a send a packet immediately. But as the application is the owner of the `select()`, it can add another file descriptor to unblock it when needed.
Also, in a multi-threaded application, I would advise you to protect the access to the `lwm2m_context_t` with a mutex.
