### ISSUE TITLE
prv_refreshServerList API makes unsorted list

### ISSUE THREAD

**Issue by boria8** [eclipse/wakaama#169]
prv_refreshServerList  API makes unsorted list, as a result if we have more than 2 servers, lets say instance 0,1, then instead getting 0,1 list we will get 1,0 list.
it causes wakaama to not find instance 0 server.
eventually we will have duplicated servers.

see the following  fix code:

static int prv_refreshServerList(lwm2m_context_t * contextP)
{
    lwm2m_server_t * targetP;
    lwm2m_server_t * nextP;
    lwm2m_server_t * head=0;

    // Remove all servers marked as dirty
    targetP = contextP->bootstrapServerList;
    contextP->bootstrapServerList = NULL;
    while (targetP != NULL)
    {
        DBG(DBG_VERBOSE,"bootstrapServerList not empty \n");
        nextP = targetP->next;
        if (targetP->dirty == false)
        {
            DBG(DBG_VERBOSE,"Bootstrap serverId=%d is NOT dirty, server was not deleted \n",targetP->shortID);
            targetP->status = STATE_DEREGISTERED;
            targetP->next=0;
            head = (lwm2m_server_t*)LWM2M_LIST_ADD(head, targetP);
        }
        else
        {
            DBG(DBG_VERBOSE,"prv_deleteServer \n");
            prv_deleteServer(targetP);
        }
        targetP = nextP;
    }
    contextP->bootstrapServerList=head;
    head=0;
    targetP = contextP->serverList;
    contextP->serverList = NULL;
    while (targetP != NULL)
    {
        nextP = targetP->next;
        if (targetP->dirty == false )
        {
            // TODO: Should we revert the status to STATE_DEREGISTERED ?
            DBG(DBG_VERBOSE,"serverId=%d is NOT dirty, server was not deleted  \n",targetP->shortID);
            targetP->next=0;
            head = (lwm2m_server_t*)LWM2M_LIST_ADD(head, targetP);
        }
        else
        {
            prv_deleteServer(targetP);
        }
        targetP = nextP;
    }
    contextP->serverList=head;
    return object_getServers(contextP);
}

**Comment by dnav** [comment]
Thank you for spotting this.
Could you propose your fix as a Pull Request ?

Thanks,

**Comment by dnav** [comment]
Actually,  I included a fix for this in #172.

Regards

**Comment by dnav** [comment]
Fixed by #172
