### ISSUE TITLE
calling prv_updateRegistration before registration was done

### ISSUE THREAD

**Issue by boria8** [eclipse/wakaama#170]
if we call prv_updateRegistration before registration was done,wakaama we crash from segfault.

see the following fix code:

static int prv_updateRegistration(lwm2m_context_t * contextP,
                                  lwm2m_server_t * server,
                                  bool withObjects)
{
    lwm2m_transaction_t * transaction;
    uint8_t payload[512];
    int payload_length;

>    if(server->location == 0)
>     {
>         LOG("Server is Not registered yet\n");
>         return COAP_500_INTERNAL_SERVER_ERROR;
>     }

    transaction = transaction_new(COAP_TYPE_CON, COAP_POST, NULL, NULL, contextP->nextMID++, 4, NULL, ENDPOINT_SERVER, (void *)server);
    if (transaction == NULL) return COAP_500_INTERNAL_SERVER_ERROR;

    coap_set_header_uri_path(transaction->message, server->location);

    if (withObjects == true)
    {
        payload_length = object_getRegisterPayload(contextP, payload, sizeof(payload));
        if (payload_length == 0)
        {
            transaction_free(transaction);
            return COAP_500_INTERNAL_SERVER_ERROR;
        }
        coap_set_payload(transaction->message, payload, payload_length);
    }

    transaction->callback = prv_handleRegistrationUpdateReply;
    transaction->userData = (void *) server;

    contextP->transactionList = (lwm2m_transaction_t *)LWM2M_LIST_ADD(contextP->transactionList, transaction);

    if (transaction_send(contextP, transaction) == 0)
    {
        server->status = STATE_REG_UPDATE_PENDING;
    }

    return COAP_NO_ERROR;
}

// update the registration of a given server
int lwm2m_update_registration(lwm2m_context_t * contextP,
                              uint16_t shortServerID,
                              bool withObjects)
{
    lwm2m_server_t * targetP;
    uint8_t result;

    result = COAP_NO_ERROR;

    targetP = contextP->serverList;
    if (targetP == NULL)
    {
        if (object_getServers(contextP) == -1)
        {
            return COAP_404_NOT_FOUND;
        }
    }
    while (targetP != NULL && result == COAP_NO_ERROR)
    {
        if (shortServerID != 0)
        {
            if (targetP->shortID == shortServerID)
            {
                // found the server, trigger the update transaction

>                 if( targetP->status != STATE_REGISTERED)
>                 {
>                     LOG("Server is Not registered yet\n");
>                     return COAP_500_INTERNAL_SERVER_ERROR;
>                 }

                return prv_updateRegistration(contextP, targetP, withObjects);
            }
        }
        else
        {
            result = prv_updateRegistration(contextP, targetP, withObjects);
        }
        targetP = targetP->next;
    }

    if (shortServerID != 0
     && targetP == NULL)
    {
        // no server found
        result = COAP_404_NOT_FOUND;
    }

    return result;
}

**Comment by dnav** [comment]
Thank you.

I included a fix for this in #172.

Regards,

**Comment by dnav** [comment]
Fixed by #172
