### ISSUE TITLE
wakaama client sample not sending update registration requests when DTLS enabled and initiated with a bootstrap

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#175]
DTLS enabled wakaama examples client (lwm2mclient) doesn't send update registration requests if initiated with a bootstrap. Kindly see attached [logs](https://github.com/eclipse/wakaama/files/316012/no_lwm2m_update_registration.txt).

Code in sync with wakaama/master. Same behavior in wakaama/registration_rework.
Compiler: Apple LLVM version 7.3.0 (clang-703.0.29)
Server: Leshan bootstrap and device management server.

**Comment by kiranpradeep** [comment]
Usually logs shows entries for update registration. In this particular case there are none for update registration although I have kept life time to 30s. I will post results of dump /0 as early as I am infront of PC.

I should have posted logs with update registration entries for the issue to be clear.

**Comment by dnav** [comment]
Thing is the lifetime is set by the bootstrap server in this case. Please check it is expired.

**Comment by kiranpradeep** [comment]
I will update this as early as I am infront of PC.

But even if lifetime is set by bootstrap, it shouldn't have been specific to DTLS. I will update.

**Comment by kiranpradeep** [comment]
Yes. As tou pointed, timeout is set by bootstrap server. So in this case, -t has no effect. Thanks.
