### ISSUE TITLE
DTLS enabled, bootstrapped wakaama client crashes if device management server is not available

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#177]
1. Start Leshan bootstrap server having an entry for client. Stop the device management server if running.
2.  Start DTLS enabled lwm2mclient to be bootstrapped.
3. Wait for the crash.

Attaching [non_ipv4_ipv6_address_crash.txt](https://github.com/eclipse/wakaama/files/319872/non_ipv4_ipv6.txt)

Note: Will need pull request #178 or else client crashes early on double free.

Code in sync with wakaama/master.
Compiler: Apple LLVM version 7.3.0 (clang-703.0.29)
Server: Leshan Bootstrap server 0.1.11-M11

**Comment by dnav** [comment]
Fixed by #178

**Comment by kiranpradeep** [comment]
@dnav There has been a misunderstanding. #178 is not a fix for this issue. It just helps get to this issue. Kindly don't close this issue. I am not sure how to fix this.

**Comment by dnav** [comment]
Sorry for that.
I do not pay the same attention to example code than to the core.

**Comment by kiranpradeep** [comment]
@dnav - I have been trying to resolve this issue. But, for the lwm2mclient(example) to take any action, the lwm2m_step() has to return an non zero value. During these steps, the lwm2m_step() always succeeds till the crash. Could you give some pointers on how to fix this ?

**Comment by kiranpradeep** [comment]
This is no more reproducible and closing.
