### ISSUE TITLE
Core is only compatible to posix/win32 at the moment

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#180]
In core/liblwm2m.h the following can be found:
```
#ifdef WIN32
#include <time.h>
#else
#include <sys/time.h>
#endif
```
This makes the core effectivly not compatible to any other platform than posix/win32, because neither sys/time.h nor time.h is part of a compiler standard library. This is only used for logging isn't it? Can this be def'd out?

**Comment by davidgraeff** [comment]
Hm, I'm not entirely right about this. time_t is defined in time.h (in ctime for c++). It is probably right to always include <time.h> in the core to have access to this type (and size_t).

But <sys/time.h> should not be part of the core, it is POSIX only.

**Comment by dnav** [comment]
Indeed. This is a long standing issue. Time for me to fix it.

**Comment by davidgraeff** [comment]
Could you also remove the \<signal.h\> include in er-coap-13/er-coap-13.h? it is not used at all, at least all compiles fine for me after removing it.
