### ISSUE TITLE
empty string resource will result in internal server error

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#181]
object_read[[1](https://github.com/eclipse/wakaama/blob/master/core/objects.c#L205)] method in objects.c will return internal server error for empty strings.

Spec appears to allow strings of size zero.

**Comment by dnav** [comment]
What is the media-type you are using ? (the formatP parameter)

**Comment by kiranpradeep** [comment]
formatP is `LWM2M_CONTENT_TEXT`
