### ISSUE TITLE
Wakaama client doesn't take new entries added to bootstrap server

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#186]
I am using Leshan bootstrap and device management server. This is very similar to issue #155. 

I had given wrong port for device management server in bootstrap server GUI. I started lwm2mclient and after a while found the mistake(of wrong port) and corrected port in bootstrap server. But Wakaama client, continues to use the old incorrect port. Kindly see attached [bootstrap_new_entries_failed.txt](https://github.com/eclipse/wakaama/files/336383/bootstrap_new_entries_failed.txt). In Bootstrap GUI, I had changed Leshan device management port from 5784 to 5884. But the lwm2mclient is not picking it up.

Code in sync with wakaama/master
Compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Leshan BM/BS server version - 0.1.11-M10

**Comment by dnav** [comment]
Hi,
I could ne reproduce this issue **using the wakaama bootstrap server**.
Maybe the port correction was not replicated immediately to the bootstrap server ?

Here are my logs:
[log_186_dnav.txt](https://github.com/eclipse/wakaama/files/369419/log_186_dnav.txt)

**Comment by kiranpradeep** [comment]
@dnav. Sorry, I forgot to explicitly mention about the need of DTLS to reproduce the issue. Please see that my logs had DTLS.

**Comment by kiranpradeep** [comment]
This issue is no more reproducible.
