### ISSUE TITLE
Not able to parse message sent in multiple blocks

### ISSUE THREAD

**Issue by senni-oc** [eclipse/wakaama#188]
We are using the Wakaama client with a Leshan server. The Leshan server is sending a message to the Wakama client in multiple blocks and the Wakaama client is not able to parse the entire message. The first block is read and parsed properly by the Wakaama client, but then the following debug message is seen: "packet.c: Block1 NOT IMPLEMENTED".

**Comment by dnav** [comment]
Fixed by #211
