### ISSUE TITLE
Update registration is not interoperable with lwm2m-node-lib server

### ISSUE THREAD

**Issue by pasear** [eclipse/wakaama#196]
Hi there,

I tried to implement a wakaama client and a [lwm2m-node-lib](https://github.com/telefonicaid/lwm2m-node-lib) server.

It seems that the lwm2m-node-lib expects a PUT message on update registration whereas wakaama sends a POST.
The result is a BAD REQUEST from the lwm2m-node-lib server.

I do not know which follows the OMA spec, so actually I post the issue on both projects :D 
The logs are [here](https://github.com/telefonicaid/lwm2m-node-lib/issues/106).

A quick patch can fix this, and it works for lwm2m-node-lib and Leshan servers as well.

```
diff --git a/core/registration.c b/core/registration.c
index 01c5644..a251b70 100644
--- a/core/registration.c
+++ b/core/registration.c
@@ -238,7 +238,7 @@ static int prv_updateRegistration(lwm2m_context_t * contextP,
     uint8_t payload[512];
     int payload_length;
 
-    transaction = transaction_new(COAP_TYPE_CON, COAP_POST, NULL, NULL, contextP->nextMID++, 4, NULL, ENDPOINT_SERVER, (void *)server);
+    transaction = transaction_new(COAP_TYPE_CON, COAP_PUT, NULL, NULL, contextP->nextMID++, 4, NULL, ENDPOINT_SERVER, (void *)server);
     if (transaction == NULL) return COAP_500_INTERNAL_SERVER_ERROR;
 
     coap_set_header_uri_path(transaction->message, server->location);
```

Thank you.

**Comment by dnav** [comment]
Hi,

The registration update mapping was changed to a CoAP POST recently. Refer to chapter 8.2.3 of the latest LWM2M Technical Specification on the [OMA FTP](http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/)

Regards
