### ISSUE TITLE
lwm2mclient debug build crashes in bootstrap.c ( bootstrap_getStatus )

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#198]
Built Wakaama as: `cmake ../client/ -DDTLS=1 -DCMAKE_BUILD_TYPE=Debug`
Client crashes irrespective of whether server is running or not. Logs [attached](https://github.com/eclipse/wakaama/files/408334/debug_crash.txt). Non debug build are not crashing.  Tried building in Ubuntu and Mac. Same behavior.

Code in sync with Wakaama master.

**Comment by dnav** [comment]
Hi,
The bootstrap server is not designed to work with DTLS.
I considering two options: preventing -DDTLS=1 in the CMakeLists.txt or handling DTLS connection in the bootstrap server. But the latter would require a way to provide the credentials.

**Comment by dnav** [comment]
Oops ! Copy/Paste error...
Fixed by #201
