### ISSUE TITLE
Wakaama bootstrap server crashes

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#199]
Wakaama bootstrap server built with command `cmake ../bootstrap_server/ -DDTLS=1`.
Wakaama bootstrap server is crashing early. Behavior same for debug and non debug build. Logs [attached](https://github.com/eclipse/wakaama/files/408348/bootstrap.txt).

Code in sync with master. Same behavior on Mac and Ubuntu.

**Comment by dnav** [comment]
Hi,
The bootstrap server is not designed to work with DTLS.
I considering two options: preventing -DDTLS=1 in the CMakeLists.txt or handling DTLS connection in the bootstrap server. But the latter would require a way to provide the credentials.

**Comment by dnav** [comment]
I created PR #200 to prevent the usage of DTLS with the example server, bootstrap server and light client.

If one wants to implement this, it requires several things:
- use dtls_connection_t when WITH_TINYDTLS is defined.
- set the dtls context when a new incoming connection is created 
- add command line parameters to set the servers credentials
