### ISSUE TITLE
Failing to register with dtls support

### ISSUE THREAD

**Issue by malek0512** [eclipse/wakaama#202]
Hi,
I've done every step that is mentioned in the [readme](https://github.com/eclipse/wakaama/tree/master/examples/client) file, but the lwm2mclient in wakaama/example/client folder keeps failing in the registration step.

I've tested it with the online leshan server instance. I have carefully declared a PSK security key with this information : 
* Client endpoint: rpi
* Mode : PSK
* Psk identity: rpi
* Psk secret: 1234

When I execute the program as mentionned below, it fails with a 0xA3 error. So I've pulled out wireshark to see what's going on the network. And all I can see is a single encrypted CoAP packet going out.

Any idea on what the problem is ?

Thanks

>
./lwm2mclient -h leshan.eclipse.org -4 -n rpi -i rpi -s 1234
Trying to bind LWM2M Client to port 56830
LWM2M Client "rpi" started on port 56830
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
 -> State: STATE_BOOTSTRAP_REQUIRED
lwm2m_step() failed: 0xA3
>

**Comment by malek0512** [comment]
My bad, I forgot to add the port number. I should have launched it this way :
./lwm2mclient -h leshan.eclipse.org -p 5684 -4 -n rpi -i rpi -s 1234

**Comment by nextgeofront** [comment]
Thank you for your information.!!
