### ISSUE TITLE
Different installation doc for DTLS steps in examples/client/README.md and README.md

### ISSUE THREAD

**Issue by phtrivier** [eclipse/wakaama#203]
Following the doc in the "client" example's README (https://github.com/eclipse/wakaama/blob/master/examples/client/README.md), I get stuck at the autoreconf part : 

   > cd examples/shared/tinydtls
   > autoreconf -i ./configure
   autoreconf: 'configure.ac' or 'configure.in' is required

However the doc from the main README.md seems to work better.

**Comment by dnav** [comment]
Thank you for spotting this.
Fixed by #204
