### ISSUE TITLE
Client crashes on update because of server 404

### ISSUE THREAD

**Issue by ekarlso** [eclipse/wakaama#205]
[lwm2m_step:459] Final state: STATE_READY
 -> State: STATE_READY
9 bytes received from [5.39.83.206]:5683
64 84 98 5F  5F 98 32 74  C0  d..__.2t.
[lwm2m_handle_packet:209] Entering
[lwm2m_handle_packet:214] Parsed: ver 1, type 2, tkl 4, code 4.04, mid 39007, Content type: 0
[lwm2m_handle_packet:215] Payload: 
[transaction_handleResponse:278] Entering
[prv_handleRegistrationUpdateReply:228] Registration update failed
[transaction_remove:264] Entering
[transaction_free:255] Entering
[lwm2m_step:349] timeoutP: 1
[lwm2m_step:354] State: STATE_READY
[registration_getStatus:362] State: STATE_READY
[registration_getStatus:369] targetP->status: STATE_REG_FAILED
[registration_getStatus:390] reg_status: STATE_REG_FAILED
 -> State: STATE_BOOTSTRAP_REQUIRED
lwm2m_step() failed: 0xA3

**Comment by ekarlso** [comment]
It's easy to reproduce
./lwm2mclient -4 -t 2 -h leshan.eclipse.org

then just wait a bit and see that it crashes

**Comment by ekarlso** [comment]
I have reproduced this now on 3 different machines on different networks towards the eclipse leshan server and they all die.

**Comment by dnav** [comment]
Sorry but it is working as expected:
The Client updates its registration.
The Server replies with a 4.04 error.
The Client considers that the registration has failed and that this Server is not available.
The Client having no other Server to register to, it requires a bootstrap.
No bootstrap server is available thus the Client exits.

BTW, this is an exit not a crash.

Regards

**Comment by ekarlso** [comment]
But is it typical for Leshan or Wakaama server to do a 404 after a certain time ?

**Comment by boaks** [comment]
Maybe, it a good timepoint to start studying the LWM2M TS.

The registration interface is described in LWM2M TS, 5.3., the mapping to CoAP in 8.2.3.
So, if a “registration update” returns a 4.04 NOT FOUND, then the sever has no “registered device” under that` location`. I would guess 2 main reasons for that: life time expires before a “registration update” could be delivered successful to the lwm2m server, or the lwm2m server is restarted and cleans up his registration (common for test server). So, if you again get a 4.04, look on the leshan clients page. Today the longest registered device is from 8. September. I would guess it’s restarted before.
