### ISSUE TITLE
Missing doc for init submodule for DTLS

### ISSUE THREAD

**Issue by sbernard31** [eclipse/wakaama#206]
examples/client/README.md was removed but the main README.md still reference it :

> DTLS feature requires tinydtls submodule. Look at examples/client/README.md for an example of how to include tinydtls.

I suppose this should be added :

> DTLS  feature requires tinyDTLS.
> TinyDTLS is included as a GIT submodule. On first usage, you need to run the following commands to retrieve the sources:
> git submodule init
> git submodule update
> You need to install the packages libtool and autoreconf.

**Comment by tenderitaf** [comment]
when tried those commands it gives me : 

`fatal: reference is not a tree: 0016138fe3998552eee3987a1c09da43a23c9fb5
Unable to checkout '0016138fe3998552eee3987a1c09da43a23c9fb5' in submodule path 'examples/shared/tinydtls'
`

**Comment by dnav** [comment]
Fixed by #229

**Comment by senabayraktaroglu** [comment]
Hi,
I want to use dtls feature in my client. However, I could not understand where I will install autoconf and automaker to build  with tinydtls. Also I couldn’t solve what 
git submodule init
git submodule update
commands do. When I wrote those commands nothing happened.
