### ISSUE TITLE
An update of the lifetime parameter of a server object instance has no effect

### ISSUE THREAD

**Issue by vuzunov** [eclipse/wakaama#209]
An update of the lifetime parameter of a server object instance has no effect on the actual lifetime used for registration update. 

At the start of the client, a server object is created using the values of the security object instance and server object instance provided to the client. This server object gets the lifetime value by copying the value from the server object instance ( prv_getMandatoryInfo(...) ). 

This newly created server object, which has a copy of the lifetime value of the server object insatnce, is used when deciding if we need a registration update. So if we update the server object instance, it does not affect the actual lifetime value used by the client.

**Comment by JPSELC** [comment]
Seems like a fairly key piece of functionality for a client - being able to set the lifetime of the server.
One solution would be to detect if the Server Object is written to in object_write. Then find the corresponding server object from the contextP->serverList, and use prv_getMandatoryInfo to update the latter from the object that was written.

**Comment by jmbrederveld** [comment]
I second this feature request. I also run in to this issue where simply writing the lifetime value of the server object is insufficient, as the updated lifetime value is not processed for calculating the next timeout..
I will try your suggestion as you mentioned @JPSELC in the meantime. Thank you.
