### ISSUE TITLE
question about repeated observe request from a lwm2m server

### ISSUE THREAD

**Issue by xwang98** [eclipse/wakaama#215]
From the code in observe.c, it seems the lwm2m client side maintains the watchers in server basis. It means one lwm2m server can only have one watch session on a client.

From the lwm2m server code, it seems when lwm2m_observe() is called multiple times for the same client, the  lwm2m_observation_t node is created every time, but the older nodes are no longer valid since the client already reset the token in the watcher node. should we remove the older observation nodes?

I haven't validated this suspicion yet. Can anyone give some comments about my question?

**Comment by dnav** [comment]
Hi,
Actually, the client side maintain a list of observed URIs and for each of these, a list of the server watching it. However in the scenario you describe, there is a memory leak for the token at observe.c:181.
For the server-side, you are right. There should be a check of current lwm2m_observation_t before creating a new one.

Regards,

**Comment by dnav** [comment]
Proposed fix in #270

**Comment by dnav** [comment]
Fixed by #270
