### ISSUE TITLE
Receiving 5.00 Internal server error along with ACK from Client

### ISSUE THREAD

**Issue by charishmag** [eclipse/wakaama#216]
Hi,
Integrated wakaama-master code in our Project(LPC Xpresso). While Writing to Client or Reading from Client, i am getting 5.00 Internal Server Error immediately after receiving ACK from client.

Please help in finding the reason for this error.

Thanks,
Charishma.G

**Comment by dnav** [comment]
Hi,
Is this issue still valid ?
