### ISSUE TITLE
Lifetime values greater than 99999 are not well managed

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#217]
If a lifetime value greater than 99999 is used, the lifetime value sent by the client to the server in REGISTER  is not correct.
For lifetime = 100000, the data sent to the server is `lt=000000`
Issue seems to be in utils.c file, in `utils_intCopy function`:
`memcpy(buffer, str + _PRV_INT32_MAX_STR_LEN - len, len);`
to be replaced by
`memcpy(buffer, str, len);`

**Comment by dnav** [comment]
Indeed. Thanks for spotting this.
