### ISSUE TITLE
Wrong definition of COAP_MAX_TRANSMIT_WAIT 

### ISSUE THREAD

**Issue by vuzunov** [eclipse/wakaama#220]
The definition of COAP_MAX_TRANSMIT_WAIT in er-coap.h is wrong.
The caret is a binary XOR and not an operator for power calculation. Probably a pow() function shall be used instead.

**Comment by jvermillard** [comment]
in the CoAP RFC:
ACK_TIMEOUT * ((2 ** (MAX_RETRANSMIT + 1)) - 1) * ACK_RANDOM_FACTOR

in the wakaama code:

#define COAP_MAX_TRANSMIT_WAIT               ((COAP_RESPONSE_TIMEOUT * ((2 ^ (COAP_MAX_RETRANSMIT + 1)) - 1) * COAP_ACK_RANDOM_FACTOR))


** was translated into ^
I suppose ** mean powerof

**Comment by vuzunov** [comment]
Indeed, it is 2 to the power of  (MAX_RETRANSMIT + 1). 

It doesn't really have much of an impact on the correct behavior, since it is only used to guard against registration failure due to datagram loss.

**Comment by jvermillard** [comment]
Can you review the fix here: https://github.com/eclipse/wakaama/pull/222

**Comment by vuzunov** [comment]
Thats not quite correct. It has to be something like

`#define COAP_MAX_TRANSMIT_WAIT      ((COAP_RESPONSE_TIMEOUT * ( pow(2, (COAP_MAX_RETRANSMIT + 1) ) - 1) * COAP_ACK_RANDOM_FACTOR))`

And then of course the function pow needs the `math.h` header included.

**Comment by jvermillard** [comment]
I did it this way to avoid a dependency on math.h
using  `(COAP_MAX_RETRANSMIT + 1) * (COAP_MAX_RETRANSMIT + 1)` in place of `pow(2,   (COAP_MAX_RETRANSMIT + 1))`

**Comment by vuzunov** [comment]
That's what I thought too, but its not the same.
`(COAP_MAX_RETRANSMIT + 1) * (COAP_MAX_RETRANSMIT + 1)` is the same as `(COAP_MAX_RETRANSMIT + 1) to the power of 2 `and not `2 to the power of (COAP_MAX_RETRANSMIT + 1)`

Alternatively a small pow function implementation might be added.

**Comment by jvermillard** [comment]
try #2 using bit shifting

**Comment by vuzunov** [comment]
That is definitely the more elegant solution 👍

**Comment by dnav** [comment]
Nice catch @vuzunov. How could I do that ?..
Thanks for the fix @jvermillard

**Comment by dnav** [comment]
Fixed by #222
