### ISSUE TITLE
registration update and supported object list

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#221]
According to LWM2M specification at §5.3.2 Update:
This “Update” operation MUST contain only the parameters listed in Table 9 which have changed compared to the last registration parameters sent to the LWM2M Server.

Using Wakaama, when a registration update is sent, the supported object list is always sent even if this list was not changed compared to the last registration (registration and registration update messages) parameters sent to the LWM2M Server.

**Comment by fdur** [comment]
Tested with command line
`update <short server Id>`
May be not a "real" issue ...

**Comment by fdur** [comment]
OK when lifetime timer expires --> to close

**Comment by fdur** [comment]
When `lwm2m_update_registration` is called, the registration update always contains the supported object list even if this list is not updated since the last register/registration update

`        case STATE_REG_UPDATE_NEEDED:
            prv_updateRegistration(contextP, targetP, true);
            break;`
--> 3rd param is hard-coded to true

**Comment by dnav** [comment]
Fixed by #234
