### ISSUE TITLE
Failing to register to server with Mbed client when objects are declared

### ISSUE THREAD

**Issue by rdoume** [eclipse/wakaama#223]
Hello,

I have an issue that is quite problematic. 
I am using the Wakaama server example in this case.
On the other side, I have  a version of the mbed client, that try to register on the server. You can see it here :https://github.com/rdoume/MBED-LWM2M.

When I try to register my client, withouth adding any ressources, the wakaama server handles the connection properly. However, when I add any ressources on my client, I then got a BAD REQUEST  128 coap error.
In order to test my client, I run it against a Leshan server and a AWA-LWM2M server, and this is working on both cases with my ressources. 
Any idea how to deal with this kind of issue?

Sincerely,
rdoume.

**Comment by dnav** [comment]
Hi,

Could you upload the content of the exchanged messages ? A wireshark capture for instance.

Regards,

**Comment by rdoume** [comment]
Hi dnav,
I join here 2 pcap traces from Wireshark, that i will detail here:
One trace is with a Wakaama server on, the other trace is with a AwaLWM2M server on. The type of server is the only variable here, the different clients are the same on both case.

In the Wakaama Server trace, I execute in order : 

 - Registration and update of a client from mbed, named DEVIT, with a button resource. **FAILED**
- Registration and update of an OMA-DEVKI object, named OMA, with resources. **REGISTRATION OK, UPDATE FAIL**
- Registration and update of a client from mbed, named DEVIT, without any resource. **OK** 
- Registration and update of an AwaLWM2M object, named Awa Client, with resources. **OK**

In the AwaLWM2M Server trace, I execute in order : 

- Registration and update of a client from mbed, named DEVIT, without any resource. **OK** 

 - Registration and update of a client from mbed, named DEVIT, with a button resource. **OK**

- Registration and update of an OMA-DEVKI object, named OMA, with resources. **OK**

- Registration and update of an AwaLWM2M object, named Awa Client, with resources. **OK**

I did not join a third trace with the Leshan Server, the results are the same as with the AWA, everything register and update. The leshan client can register and update on the Wakaama server.

As you can see, the Wakaama server fails multiple times, for different reason ( Don't accept the update, don't accept the ressource etc.), and I can't really explain why. 

[Traces.zip](https://github.com/eclipse/wakaama/files/693818/Traces.zip)

**Comment by boaks** [comment]
Registration for DEVIT, button resource:

0000   00 00 00 01 00 06 26 45 5c 56 12 d9 04 61 86 dd  ......&E\V...a..
0010   60 05 d2 b1 00 40 11 3f fd 00 0d b8 0f f1 00 00  `....@.?........
0020   fe c2 3d 00 00 03 84 d2 fd 00 0d b8 0f f1 00 00  ..=.............
0030   19 49 da 29 ee 9a 06 ce ff fe 16 33 00 40 05 3b  .I.).......3.@.;
0040   40 02 01 ca b2 72 64 11 28 38 65 70 3d 44 45 56  @....rd.(8ep=DEV
0050   49 54 05 6c 74 3d 36 30 03 62 3d 55 ff 3c 2f 30  IT.lt=60.b=U.</0
0060   2f 30 2f 30 3e 3b 72 74 3d 22 42 75 74 74 6f 6e  /0/0>;rt="Button
0070   22 2c 3c 2f 33 2f 30 3e                          ",</3/0>

**FAILED**.

May be because resources ("/0/0/0", path with 3 parts) are not considered to be valid in a registration.

**Comment by fdur** [comment]
From my point of view, object 0 shall not be present in registration message (neither in registration update message)
In §5.3.1 of TS:
The Security Object ID:0 MUST not be part of the Registration Objects and Object Instances list.

**Comment by boaks** [comment]
> Registration and update of an OMA-DEVKI object, named OMA, with resources. REGISTRATION OK, UPDATE FAIL

`1943	133.828920	fd00:db8:ff1:0:1949:da29:ee9a:6ce	fd00:db8:ff1:0:1949:da29:ee9a:6ce	CoAP	83	CON, MID:35987, PUT, /rd/0?lt=60&b=U
`
`PUT` is not (longer) valid for UPDATE REGISTER. May be better using `POST`.
(That changed for now more then a year.)

**Comment by dnav** [comment]
What @boaks and @fdur said.
This is not a valid LWM2M registration payload:
- URI has three parts.
- Object ID 0 must not be registered.
- "rt" value is unknown.

A LWM2M Server is not a complete Resource Directory Server.

Regards,

**Comment by rdoume** [comment]
First of all, thank you for your answers.
Regarding the OMA update process with the PUT, I would have thought the OMA-webkit would be up to date.
Regarding the /0 object, my bad, i did that mistake on the trace.

However, I still have follow-up questions regarding the 3 terms URI.
I understand that in the case of known Ipso object, the URI of the ressource is known, and a 2 term URI (object ID & instance number) is sufficient.

But in the case of custom object, such as the test object in the Wakaama server, I don't understand how a 2 term URI is enough.  
The test object is defined as 

> > /*
>  * Implements an object for testing purpose
>  *
>  *  Multiple
>  * Object |  ID  | Instances | Mandatoty |
>  *  Test  | 1024 |    Yes    |    No     |
>  *
>  *  Ressources:
>  *              Supported    Multiple
>  *  Name | ID | Operations | Instances | Mandatory |  Type   | Range | Units | Description |
>  *  test |  1 |    R/W     |    No     |    Yes    | Integer | 0-255 |       |             |
>  *  exec |  2 |     E      |    No     |    Yes    |         |       |       |             |
>  *  dec  |  3 |    R/W     |    No     |    Yes    |  Float  |       |       |             |
>  *
>  */
The 1024 object has therefore 3 resources.
The payload  the client send is  " /1/0, /2/0, /3/0, /4/0, /5/0, /6/0, /7/0, /1024/10, /1024/11, /1024/12"

I don't see how the second term is supposed to be interpreted as instance of the object in the begining in the payload (e.g /1/0), and as ressource for the test object.
And, as shown in the joined pic, the Leshan M2M server interpret it my way as well, considering the " /1024/10, /1024/11, /1024/12 " as one object 1024, with 3 instances and no ressource.
![lesh](https://cloud.githubusercontent.com/assets/3531195/21828573/7e411606-d791-11e6-9801-4af9dc109ecd.png)

I'm sorry in advance if my question seems trivial, but I have a bit of hard time understanding the subtility
of Wakaama compared to a leshan for example.
Thank you,
Best regards

**Comment by dnav** [comment]
Hi,

10, 11 and 12 are not resources of the wakaama custom object. They are instances. Its resources are 1, 2 and 3.
In LWM2M, the object layout is not given at the registration step. A core concept is that the ID of the Object is well-known by all parties. It is not only the case for IPSO Objects but for all objects.
For custom objects, the server can perform a discover operation to have a rough idea of the object layout but it is not sufficient.

Regards,
