### ISSUE TITLE
DTLS on server-side, not client

### ISSUE THREAD

**Issue by mlindstedt** [eclipse/wakaama#224]
Hi,

sorry, if this question is obvious, I'm new to Wakaama.

I've added your great Wakaama c-code into an iOS app with swift-code as a LWM2M server. It communicates over BLE with an embedded system, which is LWM2M client, but it uses Leishan instead.

Now I've been asked to add DTLS to iOS app, since embedded system has already added it. When I look in Wakaama documentation and code, the README.md tells me to set switch to DTLS=1 and that works fine and also adding tinyDTLS works fine. However it seems like tinyDTLS is only needed for client side, since compiler flag WITH_TINYDTLS is used in wakaama/examples/client/lwm2mclient.c, but I can't find anything DTLS related in the wakaama/examples/server/lwm2mserver.c. Is DTLS working straight out of the box on server-side? Or what is needed to make it work on server-side?

Hope someone can help me. Thanks in advance!

**Comment by vuzunov** [comment]
tinyDTLS is just a layer between Wakaama and the network connection that you use. So it doesn't really make much of a difference if you use Wakaama as a client or a server.

Data that you would normally directly send to any peer is instead sent to tinyDTLS, where it gets encrypted and is then sent back to your application through callbacks which you register upon connection establishment. You can then send the encrypted data to your peer. Similarly you'll have to push any received data through tinyDTLS before passing it to Wakaama for further handling.

**Comment by boaks** [comment]
>  So it doesn't really make much of a difference if you use Wakaama as a client or a server.

After the DTLS handshake :-).
During the DTLS handshake, the way the credentials are provided for tinyDTLS client or server are different. But it's not too hard. See the bootstrapserver.

**Comment by mlindstedt** [comment]
Thanks, great answer!
