### ISSUE TITLE
Wakaama client doesn't allow instance creation with out writeable fields

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#235]
Using Leshan UI(leshan.eclipse.org), I tried creating new instances of LWM2M Server Object(/1) with out values in any of the fields( other than instance id ). Leshan client ( lwm2m-client-demo.jar ) does allow it, while Wakaama( lwm2mclient ) doesn't. Is it mandatory to have resources during instance creation ?

I create a similar ticket(#230) earlier which was closed telling it was since Leshan doesn't know all fields. I suspect root cause is same.

**Comment by dnav** [comment]
Hi,

Sorry I thought I answered. In LwM2M TS, it is indeed mandatory to provide the content of the new instance during the creation.

Regards,

**Comment by sbernard31** [comment]
Ok but if there is not Writable resource ? like [Temperature](http://www.openmobilealliance.org/tech/profiles/lwm2m/3303.xml) (Even if I'm not sure to see how creating a new instance of Temperature could make sense oO ?)

**Comment by dnav** [comment]
The allowed operations are considered only for Write, Read and Execute operations. The Create operation is done at the Instance level and ignore the allowed operations.

**Comment by sbernard31** [comment]
I'm not sure to see how this could make sense ? When you create an instance you can send values for Executable or Readable resource ....

**Comment by dnav** [comment]
Executable resources do not have values so you do not include them in the Create payload.
Readable resources have a value so you need to include them in the Create payload. It is the same as the Bootstrap Write operation.

**Comment by sbernard31** [comment]
Ok, so we are flexible enough to set value to read only resource (e.g. setting temperature of a sensor ...), however it is strictly forbidden to create an instance without payload. Sounds strange to me, but I can leave with that. (At Leshan side I don't think we will be so strict)

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20170208-A, 7.3.2.4

> If the “Create” operation is permitted, the LwM2M Client MUST perform the instantiation on the Object only if all the mandatory Resources are present in the “New Value” parameter (see Section 5). If all the mandatory Resources are not present, the LwM2M Client MUST send a “Bad Request” error code to the LwM2M Server.
> ...
> if a value of such a Read-only Resource is present in the “New Value” parameter, this value MUST simply be ignored
> 

So, even if it's somehow strange, provide the READ ONLY resources and then ignore them :-).

**Comment by dnav** [comment]
Yes the TS is not very clear on this point.

Anyway, wakaama requires the Create operation to target a URI in the form /[ObjectID] with a parsable payload. If the payload is an Object Instance, its ID must not exist in the targeted Object.
The validation of the content is left to the Object plugin.

Regards,

**Comment by kiranpradeep** [comment]
What I understood from above discussion is, "_If all resource fields of an lwm2m object are both non mandatory and read-only, then lwm2m client should allow instance creation with out values for any of fields_". Please correct me if that is wrong.

I modified all fields in Wakaama lwm2mclient's test object(/1024) to be both read-only and non mandatory ( in leshan's oma-object-spec.json[[1](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M1/leshan-core/src/main/resources/oma-objects-spec.json)] ). Wakaama client still fails in instance creation of test object (/1024).

**Comment by dnav** [comment]
Thing is the TS makes it mandatory to have a payload in the Create message.
This is a point which needs clarification from the OMA Working Group on the points raised here.
My understanding of the part quoted by @boaks is that the mandatory Read-Only resources must be part of the payload but the Client can ignore them.
An Object with no mandatory resource is a corner case which was not considered.

Regards,
