### ISSUE TITLE
Support LWM2M version in REGISTER

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#236]
Because LWM2M v1.0 specification seems to be adopted, wakaama could send the supported LWM2M specification version.
This is already defined in Wakaama: 
`#define QUERY_VERSION_FULL      "lwm2m=1.0"`
`#define QUERY_VERSION_FULL_LEN  9`
But `QUERY_VERSION_FULL` is not used in `prv_getRegistrationQuery`or in `prv_register`

**Comment by dnav** [comment]
Indeed. The version was recently made madatory to include.
I'll take care of this.

Thanks

**Comment by dnav** [comment]
See #239

**Comment by dnav** [comment]
Fixed by #239
