### ISSUE TITLE
Object read returns an error if no object instance exist

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#237]
Each object can have one or several object instances (as indicated in LWM2M specification).
In software update specification ([object 9](http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/OMA-TS-LWM2M_SwMgmt-V1_0-20151201-C.zip)), this object can support one or several object instance.
As indicated in §6: 

> Each software component is managed via a dedicated Software Management Object instance

If no software component is managed, this object does not have any object instance.
If a READ command is received on object 9 while no object instance exist, Wakaama returns `COAP_404_NOT_FOUND`
From my point of view, in this case, Wakaama needs to return `COAP_205_CONTENT`with empty payload

**Comment by dnav** [comment]
I tend to share your point of view.
I'll investigate this.

**Comment by dnav** [comment]
See #240

**Comment by dnav** [comment]
Fixed by #240

**Comment by dnav** [comment]
Reopen following @jvermillard comment:
> This fix doesn't work because the content format is NULL so the server can't parse the payload as a TLV.
Also if the server read as JSON wwe should have "{}" and not an empty payload. IMO We should add the @fdur fix

**Comment by dnav** [comment]
Hi,
several aspects of the issue:
1- the content type should not be NULL if the LwM2M Server sent an accept option. I'll investigate this.
2- IMHO an empty payload is a valid TLV payload
3- You're right, the JSON payload should be "{}"

**Comment by jvermillard** [comment]
For 2 & 3 I think we should manage an empty instance list as any other content and encode it and don't try to make a special case

**Comment by dnav** [comment]
You're right, there are too much special cases now.
It will be easier to manage by changing the returned value of lwm2m_data_serialize() so that 0 is now longer an error.

**Comment by dnav** [comment]
Please have a look at #251 
For empty Objects, the JSON payload is `{"bn":"/1234/","e":[]}`.
The TLV payload is an empty payload.
The right content-type is returned correctly.
