### ISSUE TITLE
coap_content_type_t size

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#246]
There is a problem with coap_content_type_t in er-coap-13.h when the compiler uses the minimum size for an enum (this is the default for IAR). It only contains enumeration values up to 51, leading to a storage size of 1 byte. There are, however, content types up to 65535, requiring 2 bytes. I ran into this when receiving a message with content type for TLV (11542 or 0x2D16). It was gettuing stored in a single byte in the packet by  by coap_parse_message and then interpreted as IMAGE_JPEG (22 or 0x16).
	
This is a potential future issue for coap_option_t also, according to the range of values from http://www.iana.org/assignments/core-parameters/core-parameters.xhtml.

**Comment by fdur** [comment]
This issue was also seen when wakaama is compiled using C90 compiler (#232]

**Comment by sbernard31** [comment]
There is a discussion about that on the mailing list : https://dev.eclipse.org/mhonarc/lists/wakaama-dev/msg00392.html

**Comment by dnav** [comment]
Hi,

Does #247 fixes the issue ?

Regards,

**Comment by sbertin-telular** [comment]
That does fix the problem, but I would suggest doing something similar for coap_option_t also to prevent a future problem.

**Comment by dnav** [comment]
Right. Updated.

**Comment by dnav** [comment]
Fixed by #247
