### ISSUE TITLE
Bootstrap leaves connection open on client.

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#257]
The bootstrap_step function with status STATE_BS_FINISHED would close the connection, but it is never called with that status. The lwm2m_step function in the state STATE_BOOTSTRAPPING calls bootstrap_getStatus and only calls bootstrap_step if the status is not STATE_BS_FINISHED and not STATE_BS_FAILED.
	
I would suggest having the lwm2m_step function in the state STATE_BOOTSTRAPPING call the bootstrap_step function in all cases. I have tested moving it from the default case to before the switch statement and it disconnected properly.

**Comment by dnav** [comment]
Indeed.
Your suggestion fixes the issue but I'll investigate to determine if a design change would be better.
Thanks

**Comment by sbertin-telular** [comment]
That change looks like it will handle the successful case, but I think the connection will still be left open in the failed case.

**Comment by dnav** [comment]
You're right. It should be OK now.

**Comment by sbertin-telular** [comment]
bootstrap_getStatus should return STATE_BS_PENDING in STATE_BS_FAILING. It currently returns STATE_BS_FAILED, but that prevents bootstrap_step for being called to close the connection and move from STATE_BS_FAILING to STATE_BS_FAILED.

**Comment by dnav** [comment]
Fixed by #294
