### ISSUE TITLE
Coap_blockwise

### ISSUE THREAD

**Issue by TomMettam** [eclipse/wakaama#258]
Hello

Does Wakaama not support coap blockwise transfers? It seems that it is not possible to transmit strings of 1280 bytes or more.

**Comment by dnav** [comment]
Hi,

Currently wakaama supports blockwise transfer only when receiving data from a LwM2M Server.

Regards

**Comment by TomMettam** [comment]
Is full (send) support planned?

**Comment by dnav** [comment]
It is planned. But I'm afraid I can not give you an ETA...

**Comment by SushainRazdan** [comment]
Hi dnav,

Is the block1 send going to be available soon ?

Thanks,
Sushain

**Comment by PadmabushanReddy** [comment]
Actually, I have a case where Notification response for an observation is sometimes massive (320kb). It would need block2 with observe i guess as per [rfc7959](https://tools.ietf.org/html/rfc7959#section-3.4).

**Comment by SushainRazdan** [comment]
Hi dnav,

Any new update on this ?

**Comment by tuve** [comment]
I have an open pull request for this #[461](https://github.com/eclipse/wakaama/pull/461) I still have some pending (bugfixes )  to that but I hope to push in the next few days now when then project is back. Maybe these changes need some more discussion as they are quite extensive, @sbertin-telular did leave some comments.

**Comment by sbernard31** [comment]
(out of topic / github tips : you can just write #461 and link is automatically created. see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls)

**Comment by qleisan** [comment]
@sbernard31 #461 is merged so this issue can be closed
