### ISSUE TITLE
Bug - using time causing unexpected behaviors

### ISSUE THREAD

**Issue by rayzhang415** [eclipse/wakaama#259]
File: liblwm2m.c
> lwm2m_context_t * lwm2m_init(void * userData)
> {
>     lwm2m_context_t * contextP;
>     LOG("Entering");
>     contextP = (lwm2m_context_t *)lwm2m_malloc(sizeof(lwm2m_context_t));
>     if (NULL != contextP)
>     {
>         memset(contextP, 0, sizeof(lwm2m_context_t));
>         contextP->userData = userData;
>         **_srand(time(NULL));  //<--should use lwm2m_gettime()_**
>         contextP->nextMID = rand();
>     }
>     return contextP;
> }

In above code it's hardcoding time as opposed to using the platform abstraction function which causes strange things to happen when time is not being used in the project

**Comment by dnav** [comment]
Indeed. I'll handle this.

**Comment by dnav** [comment]
Fixed by #260
