### ISSUE TITLE
lwm2mclient not honoring lifetime parameter( -t )

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#261]
I tried using lwm2mclient with leshan.eclipse.org as below

`./lwm2mclient -n K -h leshan.eclipse.org -p 5683 -t 120 -4`

Irrespective of what value I give lifetime parameter( -t ), lwm2mclient is sending update registration requests every **30** seconds. The same is reflected in 'Last Update' status of leshan UI.

Code in sync with wakaama/master and behavior is same across operating systems/compilers.

**Comment by dnav** [comment]
Hi,

When sending a confirmable CoAP message, you have to wait up to 93 secondes (MAX_TRANSMIT_WAIT) for the acknowledgement.
Wakaama sends registration update messages 93 secondes earlier to be sure that the message reach the LwM2M Server before it drops the registration. See registration_step() in core/registration.c

Regards,
