### ISSUE TITLE
Bootstrap write ignores instance ID when creating instance

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#262]
During a bootstrap, an object instance may be written multiple times. The first time it is written (if it doesn't exist), an instance is created with the lowest available ID. This ignores the ID sent by the server. If they don't match, the next write to that instance ID will either create another instance or write to a different instance if one was created between the writes with the same ID.

bootstrap_handleCommand() calls object_createInstance(), which calls the create function with a new ID.

**Comment by dnav** [comment]
There is indeed a bug as the Instance ID sent by the server must not be ignored. I'll take care of this. 

Thanks for spotting this issue.

**Comment by sbertin-telular** [comment]
Sorry it went so long with no feedback. I was travelling and didn't have a chance to look at it. Looks good.
