### ISSUE TITLE
lwm2m_data_serialize() doesn't consider older json/tlv formats 

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#266]
It appears current master([1](https://github.com/eclipse/wakaama/blob/86b41ddd0f9a9a03b4ab52881b563044bc722861/core/data.c#L471)) doesn't take  `LWM2M_*_OLD` into account while serializing data.

I tried modifying  `lwm2m_data_serialize` and read was succeeding. But then observations failed.

Is this(#238) now a non goal of this project ?

**Comment by dnav** [comment]
Hi,

The fix for #238 was incomplete. Please have a look to #267.
The accept option was also ignored in Observation requests.
