### ISSUE TITLE
Possible memory leak for observes when instance is deleted

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#268]
When an instance is deleted, the observes for that instance and any resources of that instance don't seem to be removed. The spec is unclear on exactly what should happen in this case, but I believe the observes should be removed to prevent memory leaks.

**Comment by dnav** [comment]
Proposed fix in #270

**Comment by sbertin-telular** [comment]
That looks good for the single instance case, but when deleting all instances no observes will be cleared if the delete of any instance fails.

This also only handles deletions by the server. If the instance is deleted by a local process, I don't think object_delete would be called. This may need to be the responsibility of the Object plugin.

**Comment by dnav** [comment]
You are right, I was lazy. Now it should be better.

instance deletion by a local processis not correctly handled by wakaama currently. Along with the observation removal, it should also generate a registration update. Maybe a new API is required for the Object plugins to signal a change in instances.

**Comment by sbertin-telular** [comment]
That looks good. Should we close the issue, or are you planning something for instance deletion by a local process as part of this?

**Comment by dnav** [comment]
It would be better to have a new issue created for this problem.
