### ISSUE TITLE
lwm2m_data_encode_string and lwm2m_data_encode_opaque may access memory after it is freed.

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#272]
If the call to prv_setBuffer returns 0, dataP will have been freed, but they both will then set dataP->type = LWM2M_TYPE_UNDEFINED.

I wasn't expecting that dataP could be freed by either function (or prv_setBuffer), but lwm2m_data_parse relies on prv_setBuffer freeing the buffer when it returns 0. I would suggest removing the side effer of freeing the buffer in prv_setBuffer and freeing the data in lwm2m_data_parse when it returns 0. There is no way for the caller of lwm2m_data_encode_string or lwm2m_data_encode_opaque to know the data has been freed.

**Comment by dnav** [comment]
Indeed. Will fix.
Thanks.
