### ISSUE TITLE
base64_decode() issue

### ISSUE THREAD

**Issue by boria8** [eclipse/wakaama#274]
i'm getting  segfault on conversion of "MA==" base64 string to Opaque from utils_base64ToOpaque function in the following line:
*bufferP[result_index - 3] = (tmp[0] << 2) | (tmp[1] >> 4);

**Comment by dnav** [comment]
Yes, this implementation is bugged.
I am considering removing it as it is not used currently in wakaama and it is not exposed.

**Comment by boria8** [comment]
actually i think that such api is required(#273 ), i'm not sure that the best way is to implement it from scratch.

**Comment by dnav** [comment]
In #271 I moved the base64 decode function to examples/shared/commandline.c until we figure something adressing #273.

**Comment by dnav** [comment]
utils_base64ToOpaque() is now base64_decode() and part of examples/shared

**Comment by boria8** [comment]
Is there a plan to fix this api?

**Comment by dnav** [comment]
Personnaly, like every other issues tagged `examples`, it is pretty low on my TODO list.
base64 is very common so it should be easy to replace the code with a working version.

**Comment by sbertin-telular** [comment]
I think this is resolved by utils_base64Decode introduced in #428.

**Comment by sbernard31** [comment]
It should be fixed. 
(should if be backported in a 1.x version ? #487)
