### ISSUE TITLE
coap_parse_message function is not validating option length variable 

### ISSUE THREAD

**Issue by boria8** [eclipse/wakaama#275]
this could lead easily to crashes when the packet is slightly corrupted.
i thing we should add at list some sanity check like:
    if(option_length>data_len)
    {
    	PRINTF("OPTION %u (delta %u, len %u): have invalid lenght \n", option_number, option_delta, option_length);
    	return BAD_REQUEST_4_00;
    }
    else
    {
    	PRINTF("OPTION %u (delta %u, len %u): \n", option_number, option_delta, option_length);
    }

**Comment by dnav** [comment]
Proposed fix in #279

**Comment by dnav** [comment]
Fixed by #279
