### ISSUE TITLE
Client stuck in STATE_INITIAL

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#277]
I had a client with Security object instances for a bootstrap server and a standard server, but no Server object instances. In this case I would expect it to bootstrap, however it never left STATE_INITIAL. This was because object_getServers (called from prv_refreshServerList) was returning -1 when it encountered the Security object instance for the standard server without a corresponding Server object instance. I think it should skip over any invalid servers and process all the Security object instances and only return an error if there are no good bootstrap or standard servers.

**Comment by dnav** [comment]
Hi,

The initial consideration was: if the configuration is flawed, the lwm2m_step() function returns an error.

However, with recent LwM2M specification changes, the configuration you describe is valid.

Regards,

**Comment by dnav** [comment]
Proposed fix in #280

**Comment by sbertin-telular** [comment]
It looks like that will fix the issue I encountered,

I am still concerned that a single misconfigured instance could render a device unusable. That sounds like a design decision for Wakaama that will need to be handled by the application.
