### ISSUE TITLE
Bootstrap needs ability for client to report errors.

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#281]
During bootstrap the configuration may not always be in a consistent state. When the Bootstrap-Finish is received the configuration needs to be checked and a "4.06 Not Acceptable" error returned if it is not consistent. Right now, "2.04 Changed" is always returned. At a minimum, the same checks performed by object_getServers should be done. There may also need to be a callback to the application to check the consistency of other configuration.

**Comment by dnav** [comment]
Fixed by #313. Thank you.
