### ISSUE TITLE
Potential memory leak in DTLS

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#284]
In `dtlsconnection.c` file, in `connection_free` API, `dtls_connection_t* ` is freed
But `dtlsSession` field seems to not been freed

**Comment by fdur** [comment]
Please give feedback on this remark.

**Comment by boaks** [comment]
Yes, smells like a leak. Also in `connection_create`, when the `dtlsSession` is just set to NULL without being freed. 

>// no dtls session
>connP->dtlsSession = NULL;
>

**Comment by fdur** [comment]
:+1:

**Comment by dnav** [comment]
Fixed by #288
