### ISSUE TITLE
Issue in connection_free in DTLS case

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#286]
In dtlsconnection file:
```
void connection_free(dtls_connection_t * connList)
{
    while (connList != NULL)
    {
        dtls_connection_t * nextP;

        nextP = connList->next;
        free(connList);

        connList = nextP;
    }
    dtls_free_context(dtlsContext);
    dtlsContext = NULL;
}
```
1st action: free connection list
2nd action: call `dtls_free_context` but this function calls:
`dtls_destroy_peer` --> `dtls_close` --> `dtls_send_alert` --> `dtls_send` --> `dtls_send_multi` --> `write/send_to_peer` --> `connection_find` (connection list was released)

I think that actions in connection_free API needs to be inverted:
1st action: call `dtls_free_context` API
2nd action: free connection list

**Comment by dnav** [comment]
Fixed by #288
