### ISSUE TITLE
Infinite loop in server after observing the same thing twice

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#301]
This is due to a problem in lwm2m_observe. Adding an observation to the server first looks for an already existing observation that matches. This will then add the existing observation to the observation list a second time. This results in an infinite loop when traversing the list later, as the observation will point to itself for the next observation.

I see three potential solutions:
1. Avoid adding the observation to the list in lwm2m_observe if it was found in the list.
2. Modify lwm2m_list_add to avoid adding something to the list that is already there. This would have the benefit of preventing the problem for all lists.
3. Return an error from lwm2m_observe for a duplicate observation instead of processing.

I would suggest both 1 and 2, but wanted to solicit opinions before I create a pull request.

**Comment by dnav** [comment]
Solution 1) is the simplest.
Actually, it is so simple that I took the liberty to create a pull request while I was reviewing the issue. See #302.

Regards,

**Comment by dnav** [comment]
Fixed by #302
