### ISSUE TITLE
Regression because of an API break on lwm2m_data_decode_int

### ISSUE THREAD

**Issue by sbernard31** [eclipse/wakaama#304]
The commit 20c73c590802383ee804df0fccf4402678a76a97 introduce an API break on [lwm2m_data_decode_int](https://github.com/eclipse/wakaama/commit/20c73c590802383ee804df0fccf4402678a76a97#diff-5cba1ebf927a67021c0f5755c9edcf94L240).

Before `lwm2m_data_decode_int` returns `0` or `1`, now it can also returns `2`, `4`, `8` in case of success.

**Comment by dnav** [comment]
Indeed.
What is the symptom of the regression ?

**Comment by sbernard31** [comment]
I suspect several issues about that, but in my case I try to write a lifetime of 900 to an object server and I get a BAD_REQUEST because 900 is not a one byte integer.

Everywhere we check this function succeed like this `1 == lwm2m_data_decode_int()`, we can face an issue if the int value to decode is > 256.

**Comment by dnav** [comment]
Right, I did not update the example client objects accordingly.
I will take a look as I introduced the change.

**Comment by sbernard31** [comment]
Does it mean you want the lwm2m_data_decode_int() function now returns the size of the int ?

**Comment by dnav** [comment]
I introduced this change while concolidating the conversion functions. I'll check if returning the size of the int is really necessary or if returning 0 or 1 is enough.
I would prefer to come back to the old return values (0 or 1).

**Comment by sbernard31** [comment]
I would prefer too.
Same API break introduces in lwm2m_data_decode_float by the way.

**Comment by dnav** [comment]
See #305.

**Comment by dnav** [comment]
Fixed by #305
