### ISSUE TITLE
Gets the value of package_url

### ISSUE THREAD

**Issue by zmsoft** [eclipse/wakaama#307]
In the latest code,is there a way to get update_url?
In object_firmware.c file line:153 “ prv_firmware_write --> case RES_M_PACKAGE_URI: ”,how to get update_url?

Many thanks

**Comment by dnav** [comment]
Hi,

The update URL is pointed by `dataArray[i].value.asBuffer.buffer` and is of length `dataArray[i].value.asBuffer.length`.

Regards
