### ISSUE TITLE
Leshan server and Wakaama client timeout

### ISSUE THREAD

**Issue by zmsoft** [eclipse/wakaama#308]
![image](https://user-images.githubusercontent.com/8024438/27363517-a2460e26-5667-11e7-9e42-afa8b89e8590.png)

Leshan server and Wakaama client,When I wrote to package_url, it timed out every time.

**Comment by dnav** [comment]
Hi,

Most of the time this is due to a NAT equpment along the way closing the UDP mapping.
You cantry using a low lifetime for your Client (like 90 seconds). The Client would send registration messages to the server every minute, keeping the mapping active.

Regards,

**Comment by fdur** [comment]
Because of https://github.com/eclipse/wakaama/commit/5707d38e7674e2bdca17103b543fad4d1533f58d, better to use a lifetime value like ... mmhhhh 100 :)
