### ISSUE TITLE
API for additional params to URI query string during registration

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#326]
Is there an API in Wakaama project to pass, additional params to the server during registration? For e.g. please see Leshan project( [link](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M3/leshan-core/src/main/java/org/eclipse/leshan/core/request/RegisterRequest.java#L49) ). I understand this could be outside of LwM2M spec, but still, it is useful when a client needs to report data to the server with out any initiation from the server.

**Comment by dnav** [comment]
Hi,

A goal of wakaama is to be as close as possible to the LwM2M standard. Thus this API does not exist.
Furthermore, LwM2M Servers would not know how to interpret the extra parameters.

You could make a suggestion to https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers

Regards,

**Comment by sbernard31** [comment]
> LwM2M Servers would not know how to interpret the extra parameters.

No need to interpret this.
In Leshan, we just pass it to the user in a map attributes (which contains all the out of the spec attributes), up to him to use it in the way he want to

In real world this seems useful for several users.

**Comment by sbernard31** [comment]
I change this as enhancement.
@sbertin-telular @rettichschnidi if we don't plan to implement it. We can close it.

**Comment by rettichschnidi** [comment]
I have no plans to implement this, but would not mind a PR created by someone else.
