### ISSUE TITLE
How can a lib user know if client has succeeded/failed in registration or update registration ?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#327]
The lib user can check the server states before and after `lwm2m_step()` method as lwm2mclient.c([1](https://github.com/eclipse/wakaama/blob/master/examples/client/lwm2mclient.c#L359)) example. The doubt here is that, can the lib user safely assume, lwm2m_step() will take him through all states. To be clear, will lwm2m_step() skip states by itself? For e.g. Can lib user write code like below?

```
if( state == STATE_REGISTERED ) {
    //steps to do if registration or update registration succeds
} else if ( state == STATE_REG_FAILED ) {
   //steps to do if registration fails continuously e.g. exit process or restart system
}
```

**Comment by dnav** [comment]
After a call to `lwm2m_step()`, the server state can be at any value. Some operations like registration may require more time to complete that the timeout specified by the caller.
However, the `STATE_REG_FAILED` state is final, meaning it won't change except if a Bootstrat is performed.
Same for the `STATE_REGISTERED`. The server will keep this state until the lifetime expires (going to `STATE_REG_UPDATE_NEEDED`) or the connection is lost.

Regards,
