### ISSUE TITLE
hbbhhhhhhhbghhhhhhhhhhhhhhhhhhhfedbev35geedc cv c ef1 4rcddc                                                                             4

### ISSUE THREAD

**Issue by boria8** [eclipse/wakaama#333]

**Comment by sbernard31** [comment]
![GitHub Logo](https://media.giphy.com/media/fpXxIjftmkk9y/giphy.gif)

**Comment by sbernard31** [comment]
![GitHub Logo](https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif)

**Comment by sbernard31** [comment]
![makes sense](https://media.giphy.com/media/deNPNTjrAysuY/giphy.gif)
