### ISSUE TITLE
URI with brackets not working for connection_create() function in dtlsconnection.c

### ISSUE THREAD

**Issue by alanlhc** [eclipse/wakaama#336]
I noticed a bug in connection_create() function in dtlsconnection.c It will always return NULL when '[' and ']' brackets is found in the URI.

/***************************************************/
dtls_connection_t * connection_create(dtls_connection_t *connList,
                                                             int sock,
                                                             lwm2m_object * securityObj,
                                                            int instanceId,
                                                            lwm2m_context_t * lwm2mH,
                                                            int addressFamily)
{
            :
            :
        // remove brackets
        if (host[0] == '[')
        {
            host++;
            if (*(port - 1) == ']')
            {
                *(port - 1) = 0;
            }
            **return NULL;**
        }
        // split strings
        *port = 0;
        port++;
            :
            :
}
/*********************************************************/

**Comment by dnav** [comment]
Fixed by #337. Thanks.
