### ISSUE TITLE
JSON format update URL

### ISSUE THREAD

**Issue by zmsoft** [eclipse/wakaama#344]
@fab13n 
The wakaama client handles the URL of the json data format and how to get the URL when it receives the update URL.
Many thanks.

The server version:
[leshan](https://github.com/eclipse/leshan)  --latest version

The log is:
zmsoft@Vostro-3400:~/iot/wakaama/examples/client$ ./lwm2mclient -4 -n fota.123 -h xx.168.xx.xx
Trying to bind LWM2M Client to port 56830
LWM2M Client "fota.123" started on port 56830
> Opening connection to server at xx.168.xx.xx:5683
 -> State: STATE_REGISTERING
22 bytes received from [xx.168.xx.xx]:5683
64 41 73 94  94 73 83 BC  82 72 64 0A  75 64 70 32   dAs..s...rd.udp2
77 4C 6D 55  63 57                                   wLmUcW
 -> State: STATE_READY
20 bytes received from [xx.168.xx.xx]:5683
48 01 60 CD  84 B8 48 A0  AB 45 3F 86  60 51 35 01   H.`...H..E?.`Q5.
30 62 2D 17                                          0b-.
 object_firmware prv_firmware_readdata.c L653 json_serialize(uriP, size, dataP, bufferP)
 -> State: STATE_READY
19 bytes received from [xx.168.xx.xx]:5683
48 01 60 CE  57 CC D0 CA  F7 AB B9 AD  B1 35 01 30   H.`.W........5.0
62 2D 17                                             b-.
object_firmware prv_firmware_readdata.c L653 json_serialize(uriP, size, dataP, bufferP)
 -> State: STATE_READY
123 bytes received from [xx.168.xx.xx]:5683
48 03 60 CF  A9 1E 9B 1C  1C CA 78 78  B1 35 01 30   H.`.......xx.5.0
01 31 12 2D  17 FF 7B 22  62 6E 22 3A  22 2F 35 2F   .1.-..{"bn":"/5/
30 2F 31 22  2C 22 65 22  3A 5B 7B 22  6E 22 3A 22   0/1","e":[{"n":"
22 2C 22 73  76 22 3A 22  68 74 74 70  3A 2F 2F 35   ","sv":"http://x
32 2E 31 36  38 2E 38 37  2E 33 34 3A  38 30 38 31   x.168.xx.xx:8081
2F 70 61 63  6B 61 67 65  5A 69 70 46  69 6C 65 2F   /packageZipFile/
77 61 6B 61  61 6D 61 7A  69 6D 61 67  65 5F 31 2E   wakaamazimage_1.
31 2E 31 2E  7A 69 70 22  7D 5D 7D                   1.1.zip"}]}
data.c L571 LWM2M_CONTENT_JSON
Segmentation fault (core dumped)
zmsoft@Vostro-3400:~/iot/wakaama/examples/client$ 

The wireshark capture is:
Payload Desc: application/link-format
0000   3c 2f 3e 3b 72 74 3d 22 6f 6d 61 2e 6c 77 6d 32  </>;rt="oma.lwm2
0010   6d 22 3b 63 74 3d 31 31 35 34 33 2c 3c 2f 31 2f  m";ct=11543,</1/
0020   30 3e 2c 3c 2f 32 2f 30 3e 2c 3c 2f 33 2f 30 3e  0>,</2/0>,</3/0>
0030   2c 3c 2f 34 2f 30 3e 2c 3c 2f 35 2f 30 3e 2c 3c  ,</4/0>,</5/0>,<
0040   2f 36 2f 30 3e 2c 3c 2f 37 2f 30 3e 2c 3c 2f 33  /6/0>,</7/0>,</3
0050   31 30 32 34 2f 31 30 3e 2c 3c 2f 33 31 30 32 34  1024/10>,</31024
0060   2f 31 31 3e 2c 3c 2f 33 31 30 32 34 2f 31 32 3e                                                  /11>,</31024/12>

</>;rt="oma.lwm2m";ct=11543,</1/0>,</2/0>,</3/0>,</4/0>,</5/0>,</6/0>,</7/0>,</31024/10>,</31024/11>,</31024/12>

cmake LWM2M_CLIENT_MODE LWM2M_SUPPORT_JSON examples/client
make
./lwm2mclient -4 -n xxx -h xx.xxx.xx.xx

**Comment by lianzeng** [comment]
hi, is it  solved  ? in which commit ?  i also have the same problem,  it 's ok to write URL in TEXT format by leshan server, but failed in JSON format, the log show cJson parse failed.

**Comment by sbernard31** [comment]
Please reopen if needed.
