### ISSUE TITLE
memory free bug！

### ISSUE THREAD

**Issue by huwentao1222** [eclipse/wakaama#346]
function 'lwm2m_handle_packet' will call lwm2m_free(response->payload) to free memory. when receive a GET Request with BLOCK2 option，response->payload may point to the start address of memory plus 'block_offset', it will cause a memory problem. 
Probable fix method:   lwm2m_free(response->payload-block_offset); 
see packet.c line 340

**Comment by sbertin-telular** [comment]
Looks like it could also free the constant string "BlockOutOfScope" from packet.c line 314.

**Comment by dnav** [comment]
Fixed by #357.

Thanks.
