### ISSUE TITLE
What CoAP version does Wakaama implement?

### ISSUE THREAD

**Issue by Gunzter** [eclipse/wakaama#351]
Hi!

I have a few questions:

The Wakaama project split of from Erbium in 2014, has the updates since then mirrored the Erbium updates, or has Wakaama and Erbium "diverged"?

As I understand it Wakaama implements LWM2M v1.0, that includes CoAP, CoAP-Observe, CoAP-Block-Wise and CoAP-EST. Is this correct?

Appart from changing Client and Server naming conventions to fit LWM2M terminology, are there significant differences between Wakaama and Erbium at this stage? I have looked on the Wakaama code and the most noticeable changes are due to the removal of Contiki-OS dependencies.

**Comment by dnav** [comment]
Hi,

Wakaama and Erbium have diverged a long time ago. Removing the Contiki-OS dependencies was the first step but now the remaining erbium code is only for serialization and parsing of CoAP packets.

Regards

**Comment by Gunzter** [comment]
Hi, 
I understand. Wakaama implement the latest version of the CoAP RFCs right?

**Comment by dnav** [comment]
Only the CoAP features required for LwM2M are really implemented. For instance, the Max-Age option can be parsed and serialized but it is ignored and never used.

**Comment by Gunzter** [comment]
Ok, I see. Thank you for your answers!
