### ISSUE TITLE
Wakaama support for bootstrap server

### ISSUE THREAD

**Issue by apsk25** [eclipse/wakaama#353]
Hi,

Is bootstrapping supported with wakaama client?

I have enterred following commands

Scenario 1
/bootstrap_server_build$ ./bootstrap_server -4 -f ../examples/bootstrap_server/bootstrap_server.ini
LWM2M Bootstrap Server now listening on port 5685.

> 31 bytes received from [127.0.0.1]:56830
44 02 8E C0  C0 8E 9B E1  B2 62 73 4D  05 65 70 3D   D........bsM.ep=
74 65 73 74  6C 77 6D 32  6D 63 6C 69  65 6E 74      testlwm2mclient

Bootstrap request from "testlwm2mclient"
Sending DELETE /0 to "testlwm2mclient" OK.
8 bytes received from [127.0.0.1]:56830
64 42 3C 00  00 3C 9B E1   dB<..<..

 Received status 2.02 (COAP_202_DELETED) for URI /0 from endpoint testlwm2mclient.
Sending DELETE /1 to "testlwm2mclient" OK.
8 bytes received from [127.0.0.1]:56830
64 42 3C 01  01 3C 9B E1   dB<..<..

 Received status 2.02 (COAP_202_DELETED) for URI /1 from endpoint testlwm2mclient.
Sending WRITE /0/2 to "testlwm2mclient" OK.
8 bytes received from [127.0.0.1]:56830
64 80 3C 02  02 3C 9B E1   d.<..<..

 Received status 4.00 (COAP_400_BAD_REQUEST) for URI /0/2 from endpoint testlwm2mclient.

./lwm2mclient -4 -b
Trying to bind LWM2M Client to port 56830
Amrit GET SECURITY OBJECTTTTTTTTTTTTTTTTTTTTTTTTTTLWM2M Client "testlwm2mclient" started on port 56830
>  -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
8 bytes received from [127.0.0.1]:5685
64 44 8E C0  C0 8E 9B E1   dD......
 -> State: STATE_BOOTSTRAPPING
10 bytes received from [127.0.0.1]:5685
44 04 3C 00  00 3C 9B E1  B1 30  D.<..<...0
 -> State: STATE_BOOTSTRAPPING
10 bytes received from [127.0.0.1]:5685
44 04 3C 01  01 3C 9B E1  B1 31  D.<..<...1
 -> State: STATE_BOOTSTRAPPING
75 bytes received from [127.0.0.1]:5685
44 03 3C 02  02 3C 9B E1  B1 30 01 32  12 06 06 FF   D.<..<...0.2....
C8 00 15 63  6F 61 70 3A  2F 2F 6C 6F  63 61 6C 68   ...coap://localh
6F 73 74 3A  35 36 38 35  C1 01 01 C1  0A 02 C1 02   ost:5685........
00 C8 03 0B  4F 75 72 49  64 65 6E 74  69 74 79 C8   ....OurIdentity.
05 09 4F 75  72 53 65 63  72 65 74                   ..OurSecret
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING

Scenario 2
/bootstrap_server_build$ ./bootstrap_server -4 -f ../examples/bootstrap_server/bootstrap_server.ini
LWM2M Bootstrap Server now listening on port 5685.

> 67 bytes received from [127.0.0.1]:56830
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 0A 44   *.......*......D
4B 20 CD 17  81 39 92 40  BA 79 8B 69  A5 68 69 E3   K ...9.@.y.i.hi.
77 E8 40 6E  58 30 67 BF  63 5C 56 00  00 00 02 C0   w.@nX0g.c\V.....
A8 01 00                                             ...

./lwm2mclient -4 -b -i 4f75724964656e74697479 -s  4F7572536563726574
Trying to bind LWM2M Client to port 56830
Amrit GET SECURITY OBJECTTTTTTTTTTTTTTTTTTTTTTTTTTLWM2M Client "testlwm2mclient" started on port 56830
>  -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
27 bytes received from [127.0.0.1]:5685
60 80 FD 00  FF 43 6F 41  50 20 76 65  72 73 69 6F   `....CoAP versio
6E 20 6D 75  73 74 20 62  65 20 31                   n must be 1
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
lwm2m_step() failed: 0xA3
[BOOTSTRAP] ObjectList restored
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING

[bootstrap_server.ini.log](https://github.com/eclipse/wakaama/files/1684992/bootstrap_server.ini.log)
bootstrap_server.ini is attached.
There is one print added by me.

I have following questions.

1. Is there any support for boot strap server in case of Wakaama.
2. In the github master download page, the examples given does not include any bootstrapping. Do we have dtls support in Client?
3. If the support is there, then let me know what I am missing. Do we require bootstrap(-b option)ing option in client if we are mentioning the identity and pre shared key on command line?
4. Let me know If I am missing anything. I have been given identity and pre shared key for a distant leshan server in some other geographical location. But it also stucks at STATE_BOOSTRAPPING(with -b) or STATE_REGISTERING(without -b).

Thanks,
Amrit Pal Singh.

**Comment by fdur** [comment]
In wakaama client, bootstrap is supported if `LWM2M_BOOTSTRAP`compilation flag is used.
However, I never used the Wakaama server ...
I suggest you to use the leshan server: https://github.com/eclipse/leshan

**Comment by apsk25** [comment]
I am basically a C programmer, so wanted to use Wakaama server as well.
Leshan is a java implementation.
I have enabled the LWM2M_BOOTSTRAP flag but things dont work.

I also dont know why bootstrapping is required if we mention the psk and identity on command line?

Ideally there will be three programs running, one BS server, One LWM2M server(for normal operations) and one LWM2M client.

if -b option is mentioned on the command line, then LWM2M client should take the psk and Identity parameters from BS server and then use these paramaters to connect with LWM2M server.

Is my assumption correct?

**Comment by dnav** [comment]
Hi,

I just tried your scenario 1 with current master branch and the bootstrapping went fine (i.e. no COAP_400_BAD_REQUEST error on /0/2).

To answer your questions:
1. Bootstrapping is implemented in the client when building with the LWM2M_BOOTSTRAP define. (e.g. examples/client)
2. DTLS is implemented by the connection layer in functions ```lwm2m_connect_server()```, ```lwm2m_close_connection()``` and ```lwm2m_buffer_send()```. See files examples/shared/dtlsconnection.[c|h]
3. in examples/client/lwm2mclient, the ```-b``` argument means that you want to perform bootstrapping and that the server information provided in the other arguments are for the Bootstrap Server. In your scenario 2, you are connecting to the bootstrap server using DTLS. The example BS does not support DTLS connections.
4. If you are trying to connect to a distant Leshan Server, do not use the -b flag. Your errors are either network errors (the client can not reach the server) or DTLS errors (invalid credentials)

Hope this helps,

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.

**Comment by qleisan** [comment]
Agree to closing;  current master requires "LWM2M_SUPPORT_TLV" to be used when building the client in order to bootstrap successfully using the wakaama bootstrap server example. This is now documented in the README.md
