### ISSUE TITLE
bootstrap_step uses uint32_t for currentTime in stead of time_t

### ISSUE THREAD

**Issue by pvanoppen2** [eclipse/wakaama#360]
The bootstrap_step method is defined as:

`void bootstrap_step(lwm2m_context_t * contextP, uint32_t currentTime, time_t* timeoutP);
`
Which assumes time to be a 32 bit value. This in contrast to the correctly defined  registration step:  

`void registration_step(lwm2m_context_t * contextP, time_t currentTime, time_t * timeoutP);
`
bootstrap_step should  use time_t  for currentTime, not uint32_t. When using 64bit time_t compilation (or interfacing with java based servers, which use 64 bit times) this might soon be an issue.

**Comment by dnav** [comment]
Fixed by #362
