### ISSUE TITLE
Access Control Object read question

### ISSUE THREAD

**Issue by cyh2018git** [eclipse/wakaama#367]
If there is no acl instance in acc instance, read acc instance has no problem; 
If I use _"acc_ctrl_oi_add_ac_val"_ to add acl instances to a target acc instance, read acc instance will get COAP_500_INTERNAL_SERVER_ERROR.  because when read end, _"lwm2m_data_serialize"_ failed.
Can anyone help me?

**Comment by cyh2018git** [comment]
I'm sure it is a bug in object_access_control.c in function prv_set_tlv:130
You should use ri instead of 2(magic number):
lwm2m_data_encode_instances(subTlvP, 2, dataP); -- >lwm2m_data_encode_instances(subTlvP, ri, dataP);

**Comment by qleisan** [comment]
Fixed by already merged PR [Handle resource instances in reads.](https://github.com/qleisan/wakaama/commit/b1f181d776f2175552238669d7d5adc41e5f0f96)
@sbernard31 @sbertin-telular close if you agree
