### ISSUE TITLE
Memory leak: registration_handleRequest

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#368]
In `registration_handleRequest` (registration.c), `prv_getParameters` is called which allocates memory for all kind of information like `name`,`lifetime` and also `version`.

In some code paths (actually in all code paths), `version` is never used again after comparing it and never free`d again therefore.

One way to fix this is shown below:
```cpp
            // version must be 1.0
            if (strlen(version) != LWM2M_VERSION_LEN
                || lwm2m_strncmp(version, LWM2M_VERSION, LWM2M_VERSION_LEN))
            {
                lwm2m_free(version);
                lwm2m_free(name);
                if (msisdn != NULL) lwm2m_free(msisdn);
                return COAP_412_PRECONDITION_FAILED;
            }

            // BUGFIX: Free version
            lwm2m_free(version);
            version = NULL;
```

**Comment by qleisan** [comment]
`version` is no longer a dynamically allocated variable so the issue no longer exist. 
Fixed by [Registration version differences for LWM2M 1.1.](https://github.com/eclipse/wakaama/commit/5f2e52b85835ce0e93b7f2185fd2c98d7b046f72)
@sbernard31 @sbertin-telular If you agree please close
