### ISSUE TITLE
json serialize: Doesn't propagate error

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/wakaama#370]
In `json.c` in `json_serialize(...)` line 1416:
```
    for (index = 0 ; index < num && head < PRV_JSON_BUFFER_SIZE ; index++) {
        int  res = prv_serializeData(targetP + index, NULL, 0, bufferJSON + head, PRV_JSON_BUFFER_SIZE - head);
        if (res < 0) return 0;
        head += res;
    }
```
If `prv_serializeData` fails, 0 is returned. This is not identified as an error in the calling function (lwm2m_data_serialize <- object_read), but a COAP_500_INTERNAL_SERVER_ERROR should be returned.

Wouldn't it be more correct if all erroneous code paths in `json_serialize(...)` return `-1` instead of `0`?

**Comment by dnav** [comment]
Fixed by #390.
