### ISSUE TITLE
Hard use of observe notification callback

### ISSUE THREAD

**Issue by Kevin0626** [eclipse/wakaama#379]
Hi, Our application needs to ensure repeatedly collecting data from the lwm2m devices. The software will try to use obs mechanism if the device support observe, if not supported it will repeat READ from the device.

However we found it very hard to build robust solution with the obs notification callback if we want to handle exceptional situations, such as obs unsupported, obs timeout, device reset etc.

After spending time to look into the source code, it seems the "count" can provide some indication about the situation, however it is mixed use with the observe sequence indicator. So we can not be sure if it is the seuqnce number or status inidcator when its is value is "COAP_202_DELETED" for instance. Currently our solution is adding a "first" flag in the userData structure, we will use it to help checking the meaning of "count" parameter. 

Should we add addition parameter in this callback so the meaning won't be mixed?

void obs_notify_callback(uint16_t clientID,
                                lwm2m_uri_t * uriP,
                                int count,
                                lwm2m_media_type_t format,
                                uint8_t * data,
                                int dataLength,
                                void * userData)

"count" meaning digged from the source code:
Obs not supported: 
COAP_405_METHOD_NOT_ALLOWED
Obs Timeout: 
COAP_503_SERVICE_UNAVAILABLE
Device reset:
COAP_202_DELETED
Any other value:
The observe option as order indicator

**Comment by sbernard31** [comment]
Be sure that coap observe is adapter to you often this is not the case.
See https://github.com/eclipse/leshan/wiki/LWM2M-Observe

Polling with read request or using new send operation from LWM2M 1.1 is maybe a better choice. 

Could we close this one ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
