### ISSUE TITLE
exception in observe_remove()

### ISSUE THREAD

**Issue by Kevin0626** [eclipse/wakaama#382]
@davidgraeff , We met an exception in the LWM2M server application. When the problem happens, the client process was just terminated, and a obs request was sent and eventually timeout.

note: there was already obs on the object when the new request was sent. It was triggered by a protection to ensure the obseration is alway on - the software will send a new obs if no notified data recieved exceed the pmax period.

This mechnism may be questionable, however we don't expect any exception like this. We tried to find out the reason from the stack but no clue on the reason.

Thread #12 [lwm2m_main] 18058 [core: 0] (Suspended : Signal : SIGABRT:Aborted)	
	__GI_raise() at raise.c:54 0x7ffff7604428	
	__GI_abort() at abort.c:89 0x7ffff760602a	
	__libc_message() at libc_fatal.c:175 0x7ffff76467ea	
	malloc_printerr() at malloc.c:5,006 0x7ffff764f37a	
	_int_free() at malloc.c:3,867 0x7ffff764f37a	
	__GI___libc_free() at malloc.c:2,968 0x7ffff765353c	
	lwm2m_free() at platform.c:33 0x7fffeea58ed0	
	observe_remove() at observe.c:791 0x7fffeea50a4b	
	prv_obsRequestCallback() at observe.c:837 0x7fffeea50b3f	
	transaction_send() at transaction.c:418 0x7fffeea4d710	
	transaction_step() at transaction.c:443 0x7fffeea4d7a6	
	lwm2m_step() at liblwm2m.c:476 0x7fffeea4799b	
	thread_lwm2m() at lwm2mserver.c:160 0x7fffeea43410	
	ThreadWrapper() at 0x7ffff79b49fe	
	start_thread() at pthread_create.c:333 0x7ffff71b56ba	
	clone() at clone.S:109 0x7ffff76d641d	

=== prv_obsRequestCallback locals =========================
static void prv_obsRequestCallback(lwm2m_transaction_t * transacP,
                                   void * message)
{

    if (code != COAP_205_CONTENT)
    {
        observationP->callback(observationP->clientP->internalID,
                               &observationP->uri,
                               code,
                               LWM2M_CONTENT_TEXT, NULL, 0,
                               observationP->userData);
        observe_remove(observationP);
    }
locals dump:
=========
observationP	lwm2m_observation_t *	0x7fffd8000a70	
	next	struct _lwm2m_observation_ *	0x0	
	id	uint16_t	0	
	clientP	struct _lwm2m_client_ *	0x7fffd8000c10	
	uri	lwm2m_uri_t	{...}	
	status	lwm2m_status_t	STATE_REGISTERED	
	callback	lwm2m_result_callback_t	0x7fffeea43bab <obs_notify_callback>	
	userData	void *	0x1	
__func__	const char [15]	0x7fffeea5cc50 <__func__.4247>	

=== transaction_send locals  =========================
int transaction_send(lwm2m_context_t * contextP,
                     lwm2m_transaction_t * transacP)
{
    .....
    if (transacP->ack_received || maxRetriesReached)
    {
        if (transacP->callback)
        {
            transacP->callback(transacP, NULL);
        }
        transaction_remove(contextP, transacP);
        return -1;
    }

locals dump:
=========
contextP	lwm2m_context_t *	0x7fffd8000910	
	clientList	lwm2m_client_t *	0x7fffd8000c10	
	monitorCallback	lwm2m_result_callback_t	0x7fffeea3f49c <prv_monitor_callback>	
	monitorUserData	void *	0x7fffd8000910	
	nextMID	uint16_t	19932	
	transactionList	lwm2m_transaction_t *	0x7fffd80017f0	
	userData	void *	0x0	
transacP	lwm2m_transaction_t *	0x7fffd80017f0	
	next	lwm2m_transaction_t *	0x7fffd80026c0	
	mID	uint16_t	19920	
	peerH	void *	0x7fffd80009f0	
	ack_received	uint8_t	0 '\0'	
	response_timeout	time_t	0	
	retrans_counter	uint8_t	6 '\006'	
	retrans_time	time_t	1531524841	
	message	void *	0x7fffd8002970	
	buffer_len	uint16_t	19	
	buffer	uint8_t *	0x7fffd8002180 "D\001", <incomplete sequence Ð>	
	callback	lwm2m_transaction_callback_t	0x7fffeea50a53 <prv_obsRequestCallback>	
	userData	void *	0x7fffd8000a70	
maxRetriesReached	_Bool	true

**Comment by Kevin0626** [comment]
![screenshot from 2018-07-17 16-12-42](https://user-images.githubusercontent.com/19812231/42805258-ee329b92-89dd-11e8-8a5e-978c9e7cc60b.png)

Hi @davidgraeff We have done some study on the source code about this issue. We suspect such as work flow introduced this problem.

1) the device go offline in fact, but not detected by the lifetime timeout yet
2) lwm2m_observe() was called on the object of this device
3) device offline detected by timeout, then registration_handleRequest() removed all the observation context for the client
4) the observe transaction timeout, prv_obsRequestCallback() tried to free the same pointer attached in the transaction.
5) the exception happened as it was already freed.

ln regard to the fix, it looks the observation context management is pretty fragile, a fix to this single issue may not solve similar problems. Please refer to the picture I attached, the observation pointer can be referred by many ongoing transactions. That can introduces many breaks.

To remove the complexity, one option will be let each transaction (observe/cancel obs) have a new allocated context object. We only do change to the observationList in the transaction internal callbacks. If a observation is already present for the object, then remove the existing and add the new one into the list.

Assuming the transaction memory freeing mechanism is solid, it will help to ensure any context attached to the transaction can be properly freed.

We would like to know what is the plan on the issue.  We could make changes in our project and then contribute to the project.  We don't prefer a private fork because it is burden for maintenance.

**Comment by davidgraeff** [comment]
@dnav Can you comment on this?

**Comment by Kevin0626** [comment]
@dnav I have created a pull request from https://github.com/Kevin0626/wakaama

**Comment by dnav** [comment]
Fixed by #93
