### ISSUE TITLE
How to use Multiple Resource Instances in a Wakaama client?

### ISSUE THREAD

**Issue by LindsayMidnight** [eclipse/wakaama#386]
Hi all!

Currently I'm developing my Wakaama Client with a unique GPS Smart Object in which I would like to use Multiple Resources.
I think this could be implemented somehow with the Wakaama library, because there are functions and variables for this purpose, but I can't get it work!
With ordinary single instance resources it works perfectly - I created my object using the example object implementations (test_object.c, and object_location.c). But none of the examples contain muliple resources, so I tried to figure it out myself. 
Do you have any idea or experience with Multiple Resource Instances?

Thank you for your attention and help,
Linn

**Comment by sbertin-telular** [comment]
I believe I had responded to Zsófia Papp on the wakaama-dev mailing list about this same issue. Here is what I wrote:
gps_read might work if *numDataP is 0, but it probably won’t work any other way. The arrays for the children should be allocated in the do loop. You are also hardcoding the indices instead of using the current index. Here is an example of what I think one case it should look like:
            case RES_M_GEOFENCING_LAT:
            {
                //lwm2m_data_encode_float(data->geofencing_lat, *dataArrayP + i);
                lwm2m_data_t *instances = lwm2m_data_new(2);
                lwm2m_data_encode_float(data->geofencing_lat[0], &instances[0]);
                lwm2m_data_encode_float(data->geofencing_lat[1], &instances[1]);
                lwm2m_data_encode_instances( instances, 2, *dataArrayP + i);
                result = COAP_205_CONTENT;
                break;
            }

You probably have problems with the hardcoded indices in gps_write also. It should look more like this:
            case RES_M_GEOFENCING_LAT:  
                 //if (lwm2m_data_decode_float(&dataArray[i], &data->geofencing_lat) == 1)
                 If ( dataArray[i].type == LWM2M_TYPE_MULTIPLE_RESOURCE && dataArray[i].value.asChildren.count == 2)
                 {
                     if ( lwm2m_data_decode_float( &(dataArray[i].value.asChildren.array[0]), &(data->geofencing_lat[0])) == 1 &&
                          lwm2m_data_decode_float( &(dataArray[i].value.asChildren.array[1]), &(data->geofencing_lat[1])) == 1 )  
                         result = COAP_204_CHANGED;
                 }
                break;

**Comment by LindsayMidnight** [comment]
Yes, I wrote to the mailing list too, but I didn't see your answer, I probably overlooked it :(

And you are right, this was the solution.
Thanks a lot!
