### ISSUE TITLE
discover segmentation fault after writing resource attributes

### ISSUE THREAD

**Issue by pdaum23** [eclipse/wakaama#388]
Hi there,

Using the sample server/client I am getting a segmentation fault by first writing attributes to the client such as: attr 0 /31024/10/1 10 20 and then attempting a discover: disc 0 /31024 

The client crashes at discover.c:91
else if (objectParamP->toSet & LWM2M_ATTR_FLAG_MIN_PERIOD)

objectParamP is NULL

Best regards,
Phil

**Comment by pdaum23** [comment]
The segmentation fault I reported on August 17 is corrected by first testing objectParamP for a NULL assignment. This test is performed in two places in discover.c

91         else if (objectParamP != NULL)
92         {
93             if (objectParamP->toSet & LWM2M_ATTR_FLAG_MIN_PERIOD)
94             {
                     ............................

**Comment by sbernard31** [comment]
@sbertin-telular, you should check if this "fix" is needed.

**Comment by sbertin-telular** [comment]
This issue does still exist on master.
