### ISSUE TITLE
Issue regarding Bootstrapping in secure mode 

### ISSUE THREAD

**Issue by zac7272** [eclipse/wakaama#391]
Hi,

I am trying to implement bootstrapping where the main server and bootstrap server both are kept in secure modes. Although I am able to achieve ready state ie client is registered successfully on Leshan/client when bs server is insecure and the main server is kept in secured mode.

But when I try same with bs secured and during port switching occurs between 5784(bs server) to 5684(main server) some packet is sent to the client but no response comes from the server.

This might be some incorrect data being sent to the main server due to which server doesn't respond.

Is Bootstrapping supported when both bs server and dm server are in secure mode?

Please guide me in resolving the issue. Do I need to decrypt the packets exchanged if yes then please guide accordingly.  

For you reference putting my logs captured.

**Comment by palashchauhan** [comment]
./lwm2mclient -n ps_nbiot_123 -h -p 5784 -4 -b -i ps_nbiot_123 -s 1234    rm: cannot remove ‘/etc/ready’: No such file or directory
rm: cannot remove ‘/etc/reg_fail’: No such file or directory

lwm2m client version : [4][0][0]

lwm2m client sleeping for 30 seconds
Trying to bind LWM2M Client to port 56830
LWM2M Client "ps_nbiot_123" started on port 56830
>  -> State: STATE_BOOTSTRAPPING
Sending 67 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 0A 8D   *.......*.......
2A F1 B0 C4  98 1C 7C 12  BD 2C DB 4C  08 DD 8C 27   *.....|..,.L...'
64 17 AD 50  4B D8 B0 CE  42 F9 4B 00  00 00 02 C0   d..PK...B.K.....
A8 01 00                                             ...
nbsent my print 670 is the err2129716192 is data sent*************************************** -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING

Data received numBytes=79

inside

inside
60 bytes received from [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 00 00  2F 03 00 00   ............/...
23 00 00 00  00 00 00 00  23 FE FD 20  2D BB 5B 7A   #.......#.. -.[z
40 3C E6 9D  F5 1F 95 CF  1D BA E3 EB  70 82 2E 8E   @<..........p...
65 4E 2D 62  9F 6E 75 2E  F4 B4 82 F0                eN-b.nu.....
Sending 99 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 01 00  56 01 00 00   ............V...
4A 00 01 00  00 00 00 00  4A FE FD 00  00 00 0A 8D   J.......J.......
2A F1 B0 C4  98 1C 7C 12  BD 2C DB 4C  08 DD 8C 27   *.....|..,.L...'
64 17 AD 50  4B D8 B0 CE  42 F9 4B 00  20 2D BB 5B   d..PK...B.K. -.[
7A 40 3C E6  9D F5 1F 95  CF 1D BA E3  EB 70 82 2E   z@<..........p..
8E 65 4E 2D  62 9F 6E 75  2E F4 B4 82  F0 00 02 C0   .eN-b.nu........
A8 01 00                                             ...
per is 141119762129719181 is the data47 is the data lenght********************nbsent my print 990 is the err2129716384 is data sent*************************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=140

inside

inside

inside
120 bytes received from [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 01 00  52 02 00 00   ............R...
46 00 01 00  00 00 00 00  46 FE FD 5B  97 66 0A CE   F.......F..[.f..
A5 9F C8 24  D8 28 10 6C  D7 F9 13 E9  40 FE E9 7D   ...$.(.l....@..}
0F 7B 26 C2  C3 79 B8 96  3C E5 61 20  5B 97 66 0A   .{&..y..<.a [.f.
C4 0D B0 CD  25 C4 BF F3  62 27 BF BF  FD B1 42 F6   ....%...b'....B.
CE 17 F8 B9  1D BC 6A 23  94 B2 5E C8  C0 A8 00 16   ......j#..^.....
FE FD 00 00  00 00 00 00  00 02 00 0C  0E 00 00 00   ................
00 02 00 00  00 00 00 00                             ........
Sending 39 bytes to [127.0.0.1]:5784
16 FE FD 00  00 00 00 00  00 00 02 00  1A 10 00 00   ................
0E 00 02 00  00 00 00 00  0E 00 0C 70  73 5F 6E 62   ...........ps_nb
69 6F 74 5F  31 32 33                                iot_123
Sending 14 bytes to [127.0.0.1]:5784
14 FE FD 00  00 00 00 00  00 00 03 00  01 01  ..............
Sending 53 bytes to [127.0.0.1]:5784
16 FE FD 00  01 00 00 00  00 00 00 00  28 00 01 00   ............(...
00 00 00 00  00 DA C1 0B  5B 29 B3 88  E9 CA 8D CA   ........[)......
F6 BE 64 6E  6E 76 CB 7F  F3 76 6A 90  46 A0 34 DF   ..dnnv...vj.F.4.
B8 17 0C 06  40                                      ....@
per is 141119762129719181 is the data82 is the data lenght********************per is 141119762129719276 is the data12 is the data lenght********************nbsent my print 390 is the err2129716376 is data sent***************************************nbsent my print 140 is the err2129716544 is data sent***************************************nbsent my print 530 is the err2129716256 is data sent*************************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=86

inside

inside
67 bytes received from [127.0.0.1]:5784
14 FE FD 00  00 00 00 00  00 00 03 00  01 01 16 FE   ................
FD 00 01 00  00 00 00 00  00 00 28 00  01 00 00 00   ..........(.....
00 00 00 9D  BB EC A2 7B  9E B5 C6 49  33 B6 3E B4   .......{...I3.>.
13 64 E0 0A  88 2A 93 C3  1C 19 32 2C  05 79 4F 78   .d...*....2,.yOx
49 DB 85                                             I..
per is 141119762129719181 is the data1 is the data lenght********************per is 14111976decrypt_verify(): found 24 bytes cleartext
2129719203 is the data24 is the data lenght******************** -> State: STATE_BOOTSTRAPPING
Sending 57 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 01 00  2C 00 01 00   ............,...
00 00 00 00  01 CB 2D A9  35 9E 63 3A  70 AC E8 9F   ......-.5.c:p...
51 46 5C 20  26 83 3D 60  85 18 29 6B  34 26 EA 27   QF\ &.=`..)k4&.'
39 A7 16 48  BA 70 9C AF  B1                         9..H.p...
nbsent my print 570 is the err2129716688 is data sent*************************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=56

inside

inside
37 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 01 00  18 00 01 00   ................
00 00 00 00  01 29 08 33  DB 60 7B CF  B8 1B A4 DE   .....).3.`{.....
6A B9 9F 59  85                                      j..Y.
per is 14111976decrypt_verify(): found 8 bytes cleartext
2129719189 is the data8 is the data lenght********************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=60

inside

inside
41 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 02 00  1C 00 01 00   ................
00 00 00 00  02 4C 09 2C  53 AE 24 B3  60 30 EC 9B   .....L.,S.$.`0..
B5 B3 34 37  E4 24 DD 5B  EC                         ..47.$.[.
per is 14111976decrypt_verify(): found 12 bytes cleartext
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 02 00  1C 00 01 00   ................
00 00 00 00  02 21 9B B1  21 7B F6 7F  05 77 57 CF   .....!..!{...wW.
D8 18 26 BD  4B 2E D0 90  62                         ..&.K...b
2129719189 is the data12 is the data lenght********************nbsent my print 410 is the err2129716488 is data sent***************************************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=148

inside

inside

inside
128 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 03 00  73 00 01 00   ............s...
00 00 00 00  03 6F 23 00  7B F5 45 EF  F5 30 62 F2   .....o#.{.E..0b.
24 6A 8B 8D  2A 57 F1 87  8B 24 51 C3  76 6B 0C 2F   $j..*W...$Q.vk./
1B 93 FE D5  8E F0 C1 0B  A9 8B EA 5C  8B B1 1D CB   ...........\....
3C 93 EE 59  71 87 16 AC  FB C8 15 9A  02 52 B8 36   <..Yq........R.6
A7 14 53 B0  AC 8D B9 16  1D 63 E4 39  38 F6 8D 9E   ..S......c.98...
55 52 87 E7  A5 AA F8 28  35 5A AD 1B  7A 66 5C 30   UR.....(5Z..zf\0
CE 1B 4F 7B  FD DA E6 71  EC 35 D7 35  ED 8E 84 1C   ..O{...q.5.5....
per is 14111976decrypt_verify(): found 99 bytes cleartext
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 03 00  1C 00 01 00   ................
00 00 00 00  03 F9 BE 63  65 C6 69 72  0C 45 30 0A   .......ce.ir.E0.
EC FB 9C 9C  D3 23 30 DF  1E                         .....#0..
2129719189 is the data99 is the data lenght********************nbsent my print 410 is the err2129716488 is data sent***************************************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=148

inside

inside

inside
128 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 04 00  73 00 01 00   ............s...
00 00 00 00  04 B0 9E 07  67 86 CA CC  8E 8E E6 0B   ........g.......
20 76 43 08  3E FC 3D CD  D7 99 AF FB  24 81 BF 5B    vC.>.=.....$..[
03 EC 99 6E  09 C8 EA 7F  E5 D6 D4 DB  61 49 19 AE   ...n........aI..
E5 A8 F3 4E  C0 77 A9 E7  11 8D B1 07  1D 21 05 F3   ...N.w.......!..
7A 01 93 AB  EE 63 A6 56  BC EB 7D 21  24 47 0D EA   z....c.V..}!$G..
DE 5F 15 92  8E 6B 80 B5  C4 C8 00 04  82 61 B6 67   ._...k.......a.g
D1 E1 2E 31  45 52 D8 DC  E2 A6 F2 72  EF 0A 15 CE   ...1ER.....r....
per is 14111976decrypt_verify(): found 99 bytes cleartext
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 04 00  1C 00 01 00   ................
00 00 00 00  04 23 A6 5B  7E 6A CC 70  78 1A 8B 40   .....#.[~j.px..@
E6 BC 96 C7  27 9E 27 C5  67                         ....'.'.g
2129719189 is the data99 is the data lenght********************nbsent my print 410 is the err2129716488 is data sent***************************************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=83

inside

inside
64 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 05 00  33 00 01 00   ............3...
00 00 00 00  05 AA A5 7B  19 B9 95 BC  8B F4 B6 24   .......{.......$
B5 06 27 E9  6E E8 8F 54  4C 18 AB 35  AA A3 81 8C   ..'.n..TL..5....
FC 44 64 F4  1D C9 A7 40  48 8B 93 16  70 3D 26 CE   .Dd....@H...p=&.
per is 14111976decrypt_verify(): found 35 bytes cleartext
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 05 00  1C 00 01 00   ................
00 00 00 00  05 A5 E3 72  EF F5 4B F8  4D 64 A3 AF   .......r..K.Md..
AD 70 F6 A4  85 87 1F C7  04                         .p.......
2129719189 is the data35 is the data lenght********************nbsent my print 410 is the err2129716488 is data sent***************************************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING

Data received numBytes=63

inside

inside
44 bytes received from [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 06 00  1F 00 01 00   ................
00 00 00 00  06 3D 54 20  A4 44 10 7E  2D 47 41 4A   .....=T .D.~-GAJ
6B E4 43 0F  8A 22 AA 4F  47 BC 1A A4                k.C..".OG...
per is 14111976decrypt_verify(): found 15 bytes cleartext
Sending 41 bytes to [127.0.0.1]:5784
17 FE FD 00  01 00 00 00  00 00 06 00  1C 00 01 00   ................
00 00 00 00  06 B8 5B 3C  10 A8 EE 1D  67 32 E8 8A   ......[<....g2..
05 1C 0C 74  6A 11 8D 28  91                         ...tj..(.
2129719189 is the data15 is the data lenght********************nbsent my print 410 is the err2129716488 is data sent***************************************the data read  trasferred 2129719189************************** -> State: STATE_BOOTSTRAPPING
**********************inside code*************************************
 File created Amrit

Amrit uri=coaps://leshan.eclipse.org:5684

Amrit uri=coaps://leshan.eclipse.org:5684
host printing*****************************************leshan.eclipse.org

host1=leshan.eclipse.org
port printing*****************************************5684

port is
Sending 67 bytes to [127.0.0.1]:5684
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 1D F5   *.......*.......
FA 5D 82 24  4E 33 E8 E7  4F 65 F9 0C  91 D4 58 99   .].$N3..Oe....X.
B1 E5 C0 15  FC 6E 65 48  46 15 16 00  00 00 02 C0   .....neHF.......
A8 01 00                                             ...
 5684nbsent my print 670 is the err2129716392 is data sent*************************************** -> State: STATE_REGISTERING

 init_reg_time=1536648698

curr_time=1536648727 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536648698

curr_time=1536648729 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536648698

curr_time=1536648733 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536648698

curr_time=1536648741 re_reg_time=0
 -> State: STATE_REGISTERING
Taking too much time in registering, Exiting

**Comment by dnav** [comment]
First, I would advise you to use [Wireshark](https://www.wireshark.org/) on your client to make sure the registration packets are really going to `coaps://leshan.eclipse.org:5684`.

The most probable cause I can see is that the dtls connection to the bootstrap server is reused to try to connect to the LwM2M server.

**Comment by dnav** [comment]
Yes right.

The registration packet is sent to localhost instead of leshan.eclipse.org.

> Sending 67 bytes to [127.0.0.1]:5684

**Comment by palashchauhan** [comment]
Hi, @dnav thankyou for replying, Actually I captured Wireshark logs but when tried to decrypt it no data was found and from online resources found that connection using dtls, the packets could not be decrypted via Wireshark.
please refer [https://osqa-ask.wireshark.org/questions/8373/dtls-decryption-not-working-on-wireshark-165-even-for-sample-capture](url)

**Comment by palashchauhan** [comment]
@apsk25 Please guide me where to make changes.

**Comment by dnav** [comment]
@palashchauhan, even without decrypting the data, wireshark should tell you where the packets are sent.

According to your logs, the registration packet is sent to the `localhost` instead of `leshan.eclipse.org`. Wireshark would confirm this.

**Comment by palashchauhan** [comment]
Hi @dnav some changes have been made as suggested. Still, the client fails to register.

![qwewfrqf](https://user-images.githubusercontent.com/8406089/45353830-9ceb5800-b5d9-11e8-8e0b-49a5214e1ff6.PNG)

Please guide me further.

Regards,
PC

**Comment by apsk25** [comment]
You have to tell everyone in this open forum what you are trying to do.
Are you directly connected to Leshan server through WiFi?

**Comment by palashchauhan** [comment]
@apsk25 Right now I am connecting directly to Leshan server through cellular data i.e. without wifi.

**Comment by apsk25** [comment]
Please check if you are able to directly connect through wifi.
Please first check from the git code directly downloaded from the net. If
that works, then check your code changes.

**Comment by palashchauhan** [comment]
Hi @dnav 
I suspect when we are using the Bootstrap server in secure mode problem occurs. My question is can we implement Bootstrapping using a Bootstrap server with Leshan server both in secure modes. For your information, we are also used local daemon python code to facilitate connection with the server which opens a local socket with the client at 127.0.0.1 due to which we are getting initial packet exchanges with the same IP.

Please guide me as with logs I can infer that we are sending some packets to Leshan server to which response is not received. Is secure mode BS server supported by Leshan server? 

Regards,

PC

**Comment by dnav** [comment]
From your first post, "when bs server is insecure and the main server is kept in secured mode" it works.
So when can rule out a wrong configuration of the leshan server account.

I thought the BS Server was deployed locally but it seems you are also using `leshan.eclipse.org` for bootstrapping, right ?

If this is the case, my bet is on a DTLS issue. A DTLS session is created to connect to the BS Server. When connecting to the LwM2M Server, as the hostname is the same, maybe your implementation reuse the same DTLS session. Thus registration packets are sent to the BS Server instead of the LwM2M Server.

Regards,

**Comment by palashchauhan** [comment]
Hi @dnav 

Yes, you are right I am using `leshan.eclipse.org` as bs server. 
Will look into the code and get back to you.

Regards,

PC

**Comment by palashchauhan** [comment]
Here are my logs after bootstrapping
host1=leshan.eclipse.org
port printing*****************************************5684

port is
Sending 67 bytes to [127.0.0.1]:5684
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 1F 8D   *.......*.......
AF 30 DA 74  AD 04 F2 82  63 CC B5 77  A6 50 4E 45   .0.t....c..w.PNE
CB 5C 3D 62  8A 2F 79 FC  70 65 40 00  00 00 02 C0   .\=b./y.pe@.....
A8 01 00                                             ...
 5684uri is #################Tthe################## &&&&&&&&&&&&&&&cops port&&&&&&&&&&775nbsent my print 670 is the err2125120696 is data sent*************************************** -> State: STATE_REGISTERING

 init_reg_time=1536758628

curr_time=1536758659 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536758628

curr_time=1536758661 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536758628

curr_time=1536758665 re_reg_time=0
 -> State: STATE_REGISTERING

 init_reg_time=1536758628

curr_time=1536758673 re_reg_time=0
 -> State: STATE_REGISTERING

Taking too much time in registering, Exiting[1]+  Killed          

Please note 127.0.0.1 is the local connection established to make contact with python daemon to facilitate client connection.

I am not getting any response from main server.

**Comment by zac7272** [comment]
Hi @dnav Recently I had gone through your comment on issue `https://github.com/eclipse/wakaama/issues/199` where you have clearly indicated that :-

> The bootstrap server is not designed to work with DTLS

Actually, I am trying implement Bootstrapping via DTLS connection and the client fails to register and I get error  

> Taking too much time in registering, Exiting[1]+ Killed

So is this the reason why my client cant be registerd as Bootstrapping via DTLS is not supported.

Please Note - In my case Bootstrap server and Leshan server are used to connect the client in secured mode using PSK''s.

Looking for your reply...

Regards,

PC

**Comment by dnav** [comment]
Hi,

In issue #199, I was talking about the **wakaama** bootstrap server.

Sorry, this is not the reason behind your issue.

**Comment by ossdev07** [comment]
Thank you @dnav  for the reply. 

So in **Leshan** bootstrapping via **DTLS** supported where **BS** is kept in secure mode.

Do you suspect any thing unusual which causes this issue ? Any suggestions where I can help myself to solve this issue.

**Comment by zac7272** [comment]
Yes @apsk25 
I am able to directly connect through wifi sucessfully.
But it fails when I use the cellular network.

**Comment by apsk25** [comment]
There is an issue with the changes that you have made in your code to
connect through cellular network.

**Comment by sbernard31** [comment]
I guess we can close this issue ?

**Comment by zac7272** [comment]
yes please
