### ISSUE TITLE
JSON data parsing for multi instance resource

### ISSUE THREAD

**Issue by gilbaruch77** [eclipse/wakaama#399]
JSON data parsing for multi-instance resource does not work.
Seems data striping is missing for that case in json_parse() :

                if (LWM2M_URI_IS_SET_RESOURCE(uriP))
                {
                    lwm2m_data_t * resP;

                    resP = NULL;
                    for (i = 0 ; i < size && resP == NULL; i++)
                    {
                        lwm2m_data_t * targetP;

                        targetP = resultP + i;
                        if (targetP->id == uriP->resourceId)
                        {
                            if (targetP->type == LWM2M_TYPE_MULTIPLE_RESOURCE)
                            {
                               -      resP = targetP->value.asChildren.array;
                               -      size = targetP->value.asChildren.count;
                               +     size = prv_dataStrip(size, targetP, &resP);
                            }

**Comment by dnav** [comment]
Thanks you for spotting this.
