### ISSUE TITLE
Dose wakaama have an official version released?

### ISSUE THREAD

**Issue by yuanjingz** [eclipse/wakaama#402]
I saw there release 0.5 on the eclipse website. at September 6th, 2017, but the project has not provided download information.

**Comment by dnav** [comment]
Hi,

Due to external events, I dropped the ball on the 0.5 release.

Now, we are in the process of creating a 1.0 release before starting a re-design for LwM2M 1.1.

Regards,

**Comment by dnav** [comment]
Hi,

wakaama is now officially in version 1.0. See https://github.com/eclipse/wakaama/releases

Regards,
