### ISSUE TITLE
LWM2M IOTAgent - Orion Subscription help

### ISSUE THREAD

**Issue by arilwan** [eclipse/wakaama#409]
Whenever I start the lightweight device connected to another system (it is wakaama implementation based) by executing `./client.sh `device registers with IOTAgent successfully and sends observation (seen from server logs).
But I am doubting if the agent actually registers itself with Orion. Orion subscription check returns empty list.
```
$ curl -X GET http://localhost:1026/v2/subscriptions
[]
```
I expect the agent should forward/submit subscription request to Orion immediately it receives device registration(am I right?).

Not sure if I MUST do PROVISIONING here as well, despite that device can register with iotagent automatically on start.

**Comment by dnav** [comment]
I do not have any experience with Orion.

As LwM2M is now fairly common, maybe the Orion community would be of better help.

Regards,
