### ISSUE TITLE
Does wakaama support use of certificate?

### ISSUE THREAD

**Issue by syhoangmai** [eclipse/wakaama#413]
Hi,
I have these two questions about wakaama client:

- Does wakaama client support getting certificate from bootstrap server (e.g Leshan)? I tried to bootstrap my device (unsecurely with Leshan) and the client can receive authentication info + lwm2m server URI if the next authentication mechanism will be PSK or unsecured but fail in case of certificate. I only attempted to get bootstrap info and print out details of the security object.

- Does wakaama client support certificate authentication with the lwm2m server?

**Comment by sbertin-telular** [comment]
According to the README for tinydtls (https://git.eclipse.org/c/tinydtls/org.eclipse.tinydtls.git/tree/README) only PSK and RPK are supported. There is no mention of certificates. If you need DTLS with certificates in your own client, you will need to use different DTLS support, such as OpenSSL or mbed TLS.

**Comment by syhoangmai** [comment]
Thank you for your reply, I think I should take a look at another dtls lib instead of tinydtls.

Sorry my question above may be a bit misleading. Please let me clarify it. 

I am thinking that wakaama don't "download" certificate from the bootstrap server (ignoring the dtls authentication process with the lwm2m server that is to come later). From my understanding the bootstrap process is just the bootstrap server write authentication info into the security object of the lwm2m client and the lwm2m client take that info to authenticate with the lwm2m server (please correct me if I am wrong).  In the PSK case the client got the credentials (which I printout and checked with info on bootstrap server), but client does not "download" certificate correctly. So, again I was wondering whether certificate is supported by wakaama . The file liblwm2m.h defined:

> #define LWM2M_SECURITY_MODE_PRE_SHARED_KEY  0
#define LWM2M_SECURITY_MODE_RAW_PUBLIC_KEY  1
#define LWM2M_SECURITY_MODE_CERTIFICATE     2
#define LWM2M_SECURITY_MODE_NONE            3

so I was expecting wakaama support use of certificate. The real secure communication should be taken care by OpenSSL or mbedTLS.

**Comment by sbertin-telular** [comment]
I'm not sure I understand what you are asking, but I'll try to clarify.

Your understanding of the bootstrap process is close, but the bootstrap server also writes a server object that has non-security related information about the server, such as the registration lifetime. This probably isn't relevant to your question, I just wanted to be clear that the bootstrap process is more than just the security object.

The bootstrap server writes all the authentication info to the security object, the client doesn't download anything. In the PSK case, there is no certificate. There is only the key and the identity. I suggest you review Appendix E.1 of the LWM2M technical spec (http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf) if you haven't already.

If you are just trying to bootstrap with certificate mode, it might succeed but the sample security object isn't really written to handle it. There may be other problems, such as leaking memory, when using it for RPK or certificate mode.

**Comment by sbernard31** [comment]
@syhoangmai could we close this issue now ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
