### ISSUE TITLE
Temperature Sensor: LWM2M objects 3303 created

### ISSUE THREAD

**Issue by arilwan** [eclipse/wakaama#417]
Hi everyone,

Working with `wakaama` client implementation of the `LWM2M` and `Fiware Orion` (of course using `IoTAgent`). I already have `raspberry Pi `sensor collecting temperature and stores in `SQLite` DB.

The scenario I want implement is to have the `IoTAgent` observes the `wakaama LWM2M client` (I mean `wakaama client` send the data to the `IoTAgent`.

I already created the `3303` object in `wakaama/example/client/object_temperature.c` then build, and I can confirm the `client` connects to the `IoTAgent` as far IoT logs (see below).
```
time=2019-01-24T12:51:15.270Z | lvl=DEBUG | corr=3e578c67-f589-4348-afaf-225509e9c787 | trans=3e578c67-f589-4348-afaf-225509e9c787 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=n/a | subsrv=n/a | msg=Looking for device with id [raspiSensorTV]. | comp=IoTAgent
time=2019-01-24T12:51:15.299Z | lvl=DEBUG | corr=n/a | trans=n/a | op=LWM2MLib.Registration | msg=Registration request ended successfully
time=2019-01-24T12:51:15.349Z | lvl=DEBUG | corr=n/a | trans=n/a | op=LWM2MLib.InformationReporting | msg=Observing value from resource /3303/0/0 in device [1]
```
But unfortunately, no are measure is sent by the `client`. Is anything wrong with my `object_temperature.c`? Code reproduced:
```
#include "liblwm2m.h"
#include "lwm2mclient.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <sqlite3.h>

//Resource Id's
#define RES_SENSOR_VALUE  5700
#define RES_SENSOR_UNITS  5701

typedef struct _prv_instance_
{
  struct _prv_instance_ * next;
  uint16_t     shortID;
  double       temp;
   char        unit[10];
} prv_instance_t;


static uint8_t prv_temperature_read(uint16_t instanceId,
                               int * numDataP,
                               lwm2m_data_t ** dataArrayP,
                               lwm2m_object_t * objectP)
{
   prv_instance_t * targetP;
   int i;
   sqlite3 *db;
   sqlite3_stmt *res;
   char temperature_val[30];

targetP = (prv_instance_t *)lwm2m_list_find(objectP->instanceList, instanceId);
if (NULL == targetP) return COAP_404_NOT_FOUND;

fprintf(stderr, "----------------- Entering in prv_temperature ----------------\n");
   // connect to the backend
int rc = sqlite3_open("../../urbansense.sqlite3", &db);

if (rc != SQLITE_OK) {
   fprintf(stderr, "Cannot open database: %s\n", sqlite3_errmsg(db));
   sqlite3_close(db);
   return 1;
   }
   else {
   fprintf(stderr, "Connection successful.\n" );
   }
rc = sqlite3_prepare_v2(db, "SELECT temperature_data FROM basic_environment ORDER BY ID DESC LIMIT 1", -1, &res, 0);
if (rc != SQLITE_OK) {
  fprintf(stderr, "Failed to fetch data: %s\n", sqlite3_errmsg(db));
  sqlite3_close(db);
  return 1;
  }
rc = sqlite3_step(res);
if (rc == SQLITE_ROW) {
  sprintf(temperature_val, "%s", sqlite3_column_text(res, 0));
  fprintf(stdout, "Temperature value ==== : %s\n", sqlite3_column_text(res, 0));
  sqlite3_finalize(res);
  sqlite3_close(db);
  }
 if(*numDataP == 0)
  {
     *dataArrayP = lwm2m_data_new(1);
     if (*dataArrayP == NULL) return COAP_500_INTERNAL_SERVER_ERROR;
     *numDataP = 1;
     (*dataArrayP)[0].id = RES_SENSOR_VALUE;
     (*dataArrayP)[1].id = RES_SENSOR_UNITS; 
   }
 for (i = 0; i < *numDataP; i++)
  {
     switch((*dataArrayP)[i].id)
     {
      case RES_SENSOR_VALUE:
          lwm2m_data_encode_float(targetP->temp, *dataArrayP +1);
           break;
      case RES_SENSOR_UNITS:
          lwm2m_data_encode_string(targetP->unit, *dataArrayP +1);
          break;
      default:
          return COAP_404_NOT_FOUND;
     }
  }
 return COAP_205_CONTENT;
}

lwm2m_object_t * get_object_temperature()
{
    /*
     * The get_object_temperature function create the object itself and return a pointer to the structure that represent it.
     */
    lwm2m_object_t * temperatureObj;

    temperatureObj = (lwm2m_object_t *)lwm2m_malloc(sizeof(lwm2m_object_t));

    if (NULL != temperatureObj)
    {
        memset(temperatureObj, 0, sizeof(lwm2m_object_t));

        /*
         * Assigns it's unique ID 3303
         */
        temperatureObj->objID = LWM2M_TEMPERATURE_OBJECT_ID;

        /*
         * and its unique instance
         *
         */
        temperatureObj->instanceList = (lwm2m_list_t *)lwm2m_malloc(sizeof(lwm2m_list_t));
        if (NULL != temperatureObj->instanceList)
        {
            memset(temperatureObj->instanceList, 0, sizeof(lwm2m_list_t));
        }
        else
        {
            lwm2m_free(temperatureObj);
            return NULL;
        }

       
        temperatureObj->readFunc     = prv_temperature_read;
        temperatureObj->userData = lwm2m_malloc(sizeof(prv_instance_t));


    }

    return temperatureObj;
}

void free_object_temperature(lwm2m_object_t * objectP)
{
    if (NULL != objectP->userData)
     {
       lwm2m_free(objectP->userData);
       objectP->instanceList = NULL;
      } 
    if(NULL != objectP->instanceList)
    {
      lwm2m_free(objectP->instanceList);
      objectP->instanceList = NULL; 
    }

    lwm2m_free(objectP);
}
```

**Comment by sbertin-telular** [comment]
I haven't looked over your code, but are you calling lwm2m_resource_value_changed when the temperature changes? If not then there will never be a notify sent because Wakaama doesn't know anything changed.

**Comment by arilwan** [comment]
Ok, I haven't call such function` lwm2m_resource_value_changed`.

**Comment by arilwan** [comment]
> I haven't looked over your code, but are you calling lwm2m_resource_value_changed when the temperature changes? If not then there will never be a notify sent because Wakaama doesn't know anything changed.

@sbertin-telular Just to make myself a bit clear, checked that `lwm2m_resource_value_changed` is defined in `observe.c` ? For instance, should I called it from within the function responsible for fetching data in my `object_temperature.c`?.

**Comment by sbertin-telular** [comment]
lwm2m_resource_value_changed would need to be changed within the application code, not within the code for the object. This would ideally be just after you write the new value to the database. Have a look at the prv_change function in lwm2mclient.c for an example.

**Comment by arilwan** [comment]
> be changed within the **application code**

@sbernard31 I am confused here please, **application code**  do you mean making changes to `lwm2mclient.c` apart from object initialisation and `free_object`  
So my transaction to the  database should actually come within `lwm2mclient.c`? Will appreciate a little more explanation please.

**Comment by sbertin-telular** [comment]
Wakaama is meant to be integrated into a larger application that manages the device. lwm2mclient.c is code meant to serve as an example and facilitate testing. If you are using lwm2mclient.c directly, then yes you will need to modify that. The database write does not need to be moved to lwm2mclient.c. You could implement some other way of detecting changes to the database such as periodically reading the value and checking for changes. If you do that, I would recommend checking more frequently than it could change to avoid missing changes.

If this is for a product, not just a personal project, I would recommend you write your own application or integrate Wakaama into your existing application instead of using lwm2mclient.c because it may not be up to production quality standards.

**Comment by arilwan** [comment]
Oh, was thinking ´lwm2mclient` is meant to initialize all objects only. Better for me to use it since this only for my research work in the lab.

**Comment by arilwan** [comment]
@sbertin-telular @dnav 

I'm very sorry to write on this issue again, but I'm still having trouble. I would appreciate if you could kindly take a look at my code to see what I'm doing wrong. I ignored the database transaction stuff, instead get temperature value change only. To simplify my research, I used wakaama files as they are, then add following:
Temperature object as above (now modified) in `/example/client/object_temperature.c` reproduced below
```
#include "liblwm2m.h"
#include "lwm2mclient.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

// Resource Id's:
#define RES_SENSOR_VALUE    5700
#define RES_SENSOR_UNITS    5701

typedef struct
{
    uint26_t    shortID;
    float       temp;
    char        unit[10];
    unsigned long timestamp;
} temperature_data_t;

static uint8_t prv_set_value(lwm2m_data_t* dataP,
                           temperature_data_t* tempData)
{
    uint8_t ret = COAP_205_CONTENT;  
    switch (dataP->id)     // temperature resourceId
    {
    case RES_SENSOR_VALUE:
        lwm2m_data_encode_float(tempData->temp, dataP);
        break;
    case RES_SENSOR_UNITS:
        //not interested in temperature unit value
        ret = COAP_405_METHOD_NOT_FOUND;
        break;
    default:
        ret = COAP_404_NOT_FOUND;
        break;
    }
  
    return ret;
}

static uint8_t prv_temperature_read(uint16_t objInstId,
                                 int*  numDataP,
                                 lwm2m_data_t** tlvArrayP,
                                 lwm2m_object_t*  objectP)
{
    int     i;
    uint8_t result = COAP_500_INTERNAL_SERVER_ERROR;
    temperature_data_t* tempData = (temperature_data_t*)(objectP->userData);

    // defined as single instance object!
    if (objInstId != 0) return COAP_404_NOT_FOUND;

    if (*numDataP == 0)     // full object, readable resources!
    {
        uint16_t readResIds[] = {
                RES_SENSOR_VALUE,
                RES_SENSOR_UNITS
        }; // readable resources!
        
        *numDataP  = sizeof(readResIds)/sizeof(uint16_t);
        *tlvArrayP = lwm2m_data_new(*numDataP);
        if (*tlvArrayP == NULL) return COAP_500_INTERNAL_SERVER_ERROR;
        
        // init readable resource id's
        for (i = 0 ; i < *numDataP ; i++)
        {
            (*tlvArrayP)[i].id = readResIds[i];
        }
    }
    
    for (i = 0 ; i < *numDataP ; i++)
    {
        result = prv_set_value((*tlvArrayP)+i, tempData);
        if (result != COAP_205_CONTENT) break;
    }
    
    return result;
}

lwm2m_object_t * get_object_temperaturen()
{
    lwm2m_object_t * temperatureObj;

    temperatureObj = (lwm2m_object_t *)lwm2m_malloc(sizeof(lwm2m_object_t));
    
    if (NULL != temperatureObj)
    {
        memset(temperatureObj, 0, sizeof(lwm2m_object_t));

        temperatureObj->objID = LWM2M_TEMPERATURE_OBJECT_ID;
        
        // and its unique instance
        temperatureObj->instanceList = (lwm2m_list_t *)lwm2m_malloc(sizeof(lwm2m_list_t));
        
        if (NULL != temperatureObj->instanceList)
        {
            memset(temperatureObj->instanceList, 0, sizeof(lwm2m_list_t));
        }
        else
        {
            lwm2m_free(temperatureObj);
            return NULL;
        }

        temperatureObj->readFunc    = prv_temperature_read;
        temperatureObj->userData    = lwm2m_malloc(sizeof(temperature_data_t));

        // initialize private data structure containing the needed variables
        if (NULL != temperatureObj->userData)
        {
            temperature_data_t* data = (temperature_data_t*)temperatureObj->userData;
            data->shortID = 0;
            data->temp = 0.0;
            data->unit = "Cel";
            data->timestamp   = time(NULL);
        }
        else
        {
            lwm2m_free(temperatureObj);
            temperatureObj = NULL;
        }
    }
    
    return temperatureObj;
}

void free_object_temperature(lwm2m_object_t * object)
{
    lwm2m_list_free(object->instanceList);
    lwm2m_free(object->userData);
    lwm2m_free(object);
}
```
Now creates a `set_temperature_value()` in `lwm2mclient.c` in which I call the `lwm2m_resource_value_changed` code below
```
void set_temperature_value(lwm2m_context_t * contextP, lwm2m_object_t * objectP,
                          double value)
{
    
    temperature_data_t * targetP;
    
    targetP = (temperature_data_t *)(objectP->instanceList);
    
    if (targetP != NULL)
    {
        targetP->x_value = value;
        
        lwm2m_uri_t joystickUri = {
            
            (LWM2M_URI_FLAG_OBJECT_ID|LWM2M_URI_FLAG_INSTANCE_ID|LWM2M_URI_FLAG_RESOURCE_ID),
            
            OBJECT_ID_joystick, targetP->shortID, JOYSTICK_X_VALUE };
        
        lwm2m_resource_value_changed(contextP, &joystickUri);
        
    }
    
}
```
Yet, no measure is observed. What I am doing worng here please?

**Comment by sbertin-telular** [comment]
I wouldn't even expect this to compile. You're mixing temperature and joystick in set_temperature_value.

**Comment by arilwan** [comment]
It was a copy-paste mistake. I corrected with what I actually have written.

**Comment by sbertin-telular** [comment]
Still has copy/paste errors, but I get the idea.

Back in your first message I see in the IoT Agent log "Observing value from resource /3303/0/0". The resource that should be observed is /3303/0/5700.

**Comment by arilwan** [comment]
I should check with Agent log again. Just wanted to be sure I'm on right track. Do I have to make a call to `set_temperature_value` to initiate observation (if so, from òbject_temperature.c`)? It seems I only define `set_temperature_value` without being called anywhere.

**Comment by sbertin-telular** [comment]
The observation is initiated by the agent, not any code on the device. In order to notify the agent of changes after it observes the temperature you will need to call set_temperature_value when the temperature changes. I would recommend the set_temperature_value function be in object_temperature.c (so there is no need to expose temperature_data_t) and be called from lwm2mclient.c.

**Comment by arilwan** [comment]
> Still has copy/paste errors, but I get the idea.
> 
> Back in your first message I see in the IoT Agent log "Observing value from resource /3303/0/0". The resource that should be observed is /3303/0/5700.

I can confirm the Agent is still observing inappropriate resource `/3303/0/0` instead of `/3303/0/5700` despite that I declared the resource id in my `object_temperature.c`
```
// Resource Id's:
#define RES_SENSOR_VALUE    5700
#define RES_SENSOR_UNITS    5701
```
What am I missing?

**Comment by sbertin-telular** [comment]
You're missing something on the IoT Agent side. I'm not familiar with it, so can't offer any guidance.

**Comment by arilwan** [comment]
> You're missing something on the IoT Agent side. I'm not familiar with it, so can't offer any guidance.

This one too is a guide. Got to check with `IoTAgent`. Issue closed.
