### ISSUE TITLE
COAP+LwM2M

### ISSUE THREAD

**Issue by apiknik** [eclipse/wakaama#420]
Hello! Help me, please.
I'm going to use UDP+COAP+LwM2M stack and i'm looking for realization of COAP and LwM2M.
I don't understand, is Wakaama client and server already contain/implement CoAP and i don't need to use separate realization of CoAP and can just use UPD+Wakaama? Or its use "er-coap-13" realization?  Thank you!

**Comment by arilwan** [comment]
Wakaama implements LwL2M which runs on top of COAP

**Comment by sbertin-telular** [comment]
Wakaama implements what it needs from CoAP and does not require a separate CoAP implementation.
