### ISSUE TITLE
please fix mem leak issue in observe_step()

### ISSUE THREAD

**Issue by zengbiao** [eclipse/wakaama#437]
please add "if (dataP != NULL) lwm2m_data_free(size, dataP);" at observe.c (line:533)

**Comment by sbertin-telular** [comment]
It looks to me that dataP would always be NULL at that point. The lwm2m_data_free calls on lines 539, 547, 555, and 824 would prevent memory leaks. Can you describe under what conditions you are seeing a memory leak?

**Comment by zengbiao** [comment]
I think "continue" is very easy to be ignored ~~~
if (COAP_205_CONTENT != object_readData(contextP, &observedP->uri, &size, &dataP)) {
                // zengbiao: if read data error, free memory before continue
                if (dataP != NULL) lwm2m_data_free(size, dataP);
                continue;
            }

**Comment by sbertin-telular** [comment]
I think the problem is more that object_readData can return with a non-NULL dataP when returniong something other than COAP_205_CONTENT. Pull request #396 fixes it in one place while #435 fixes it in object_readData.

**Comment by sbernard31** [comment]
This should be fixed in master since #435 was integrated.
