### ISSUE TITLE
Incorrect CoAP result on security object action made by the DM server

### ISSUE THREAD

**Issue by fdur** [eclipse/wakaama#440]
According to LwM2M 1.0.2 specification:
> The LwM2M Client MUST reject with an “Unauthorized” response code any LwM2M Server operation on the Security Object (ID: 0).

In current source code, "Not Found" is returned

**Comment by sbernard31** [comment]
Not a big bug but probably better to fix it.
This is also true for  [LWM2M 1.1.](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-3-0-63-Device-Management-and-Service-Enablement-Interface)

**Comment by qleisan** [comment]
@fdur thanks for reporting this bug! @sbernard31 please close once #533 is merged.
