### ISSUE TITLE
Update message interval (180s)

### ISSUE THREAD

**Issue by sothy** [eclipse/wakaama#442]
Hi,
I'm using wakaama ( DTLS/PSK) with leshan-demo-server locally. I observed 180s as interval for LwM2M update message and DTLS handshake also. For this observation, I used wireshark.  How do you set? how can configure? 

Thanks

**Comment by fdur** [comment]
This is linked to lifetime value
If you can connect your device to your Leshan demo server, Click on Read button in LwM2M Server/instance 0/Lifetime
You should have 180
This value is set by default by the bootstrap server, meaning that, normally, you connected your client to the Leshan bootstrap server (also locally I think)
By default, the lifetime value is 180 (I didn't check ...)
The easiest way to update the lifetime value is the Write button on Leshan server
If you want to send a new value by the Leshan bootstrap server, you need to use REST API in order to configure the data to be sent by the Bootstrap server

**Comment by sbertin-telular** [comment]
The default lifetime for the example client is 300s and can also be changed by the -t option. The update will happen before then to prevent expiration. The maximum time a CoAP transaction can take is 120s. If the lifetime is greater than that, the first update attempt will be 120s before the end of the lifetime. If the lifetime is less than 120s (not recommended), the first update attempt will be at half the lifetime.

**Comment by sothy** [comment]
@sbertin-telular , thanks, That's the case for LwM2M update interval. Why DTLS is also doing rehandshake in similar interval? If understand properly, DTLS connection can exist for one day?  (except NAT situation with 40s).

**Comment by sbertin-telular** [comment]
I haven't looked closely at the DTLS support in the example client to be able to comment on the rehandshake.

**Comment by boaks** [comment]
You may have a look at:

https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md

It's in the meantime implemented in californium (2.0.0-M15). 
A simple client support, which just enables the new extension and then uses the cid, if returned, would not be too complex (I guess just a couple of days for tinyDTLS). I'm currently waiting for the IANA assignments. We will see, if there is interest in. 

If you just want to check, how that works in your environment, try californium 2.0.0-M15 and provide some feedback to me. AFAIK Leshan also updated to 2.0.0-M15 so you should even be able to see, how this works with LWM2M.

**Comment by sothy** [comment]
Hello @boaks , I didnt find the way how to find provide connectin-id in leshan-client-demo? please provide i can check.

**Comment by boaks** [comment]
You need to configure it with the `DtlsConnectorConfig.Builder` in LeshanDemoServer and the LeshanDemoClient. To enable DTLS 1.2 connection ID on the server side, set 
a new SingleNodeConnectionIdGenerator(6) (e.g. a 6 byte cid), and on the client at least to support it with new SingleNodeConnectionIdGenerator(0), or also a new SingleNodeConnectionIdGenerator(6) (a 6 byte cid). Both are set in the `DtlsConnectorConfig.Builder` with `setConnectionIdGenerator`.

**Comment by sothy** [comment]
@boaks Thanks and I make it. I used Californium properties file to configure CID (DTLS_CONNECTION_ID_LENGTH=6
).  For the testing, if NAT does not change IP addresss/port address during the DTLS session, I can not validate completely. 

One more question, if I fixed connection-id in client side, and  I reboot the device, it will do complete handshake or only re-handshake with simple flows.

**Comment by boaks** [comment]
I'm not sure, if setting it Californium.properties works with leshan. There must be some code, which loads those configuration and set it to the `DtlsConfiguration` instance.
You may use WireShark to see, if still application records are used (then no cid is used), or not.

> One more question, if I fixed connection-id in client side, and I reboot the device, it will do complete handshake or only re-handshake with simple flows.

That's a misunderstanding! To really reboot a peer, the association credentials (read/write key, sequence number and the assigned connection id) has to be persisted and loaded again. That's possible to implement, but right now, not implemented in Californium.  
With that, you would not need a handshake at all, you would be able to send the message encrypted immediately. To save the keys come with the risk, that some else is reading them. So it's critical to save 
this key secure enough according your requirements.

Without that persistent "association", the behaviour doesn't differ from the one without connection ID. If the session (master secrets etc., but not the read/write keys an sequence numbers as for the association) is persisted and loaded again (that's supported, see [ClientSessionCache](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/ClientSessionCache.java) you can do a resumption handshake, if not. a full handshake is required. Saving the session is also security relevant and must be protected according your requirements.

**Comment by sbernard31** [comment]
@sothy should we close this issue ?

**Comment by sothy** [comment]
yes pls @sbernard31
