### ISSUE TITLE
Bootstrap-Delete incorrectly deletes the Security object for the bootstrap server

### ISSUE THREAD

**Issue by sbertin-telular** [eclipse/wakaama#445]
The LWM2M spec states:

> Only in Bootstrap Interface, the Delete operation MAY targets “/0” URI. In that case, the operation MUST delete all the existing Security Object Instances - **except LwM2M Bootstrap-Server Account** - in the LwM2M Client;

and:

> if no Object ID is indicated, all existing Object Instances (**except the LwM2M Bootstrap-Server Account one**) in the LwM2M Client will be deleted.

The boostrap Security object should only be deleted if that instance is specifically deleted.

**Comment by sbertin-telular** [comment]
Delete all works properly, but delete /0 does not.

**Comment by qleisan** [comment]
This can be closed now when #446 is merged?

**Comment by sbertin-telular** [comment]
Yes, it is fixed by #446.
