### ISSUE TITLE
Porting Wakaama to non POSIX system

### ISSUE THREAD

**Issue by JRubis** [eclipse/wakaama#447]
Is there a porting guide or example of porting Wakaama to a non-POSIX system?

**Comment by sbernard31** [comment]
AFAIK, there is nothing like this. @sbertin-telular, @rettichschnidi do you know something about this ? 

@JRubis, since this time you maybe find a way ? Do you think you have interesting information to share about this ?

**Comment by JRubis** [comment]
Sorry. If I did, I cant remember at this point since I haven't been working with Wakaama in almost a year.

**Comment by rettichschnidi** [comment]
@sbertin-telular I do not and I also do not have a need for it any time soon.

**Comment by sbertin-telular** [comment]
Our system isn't entirely POSIX, but I don't have a guide or example I can point to. Basically look at the example client and write your application based on how it interacts with Wakaama.
