### ISSUE TITLE
Question: system_api.c functions

### ISSUE THREAD

**Issue by JRubis** [eclipse/wakaama#449]
I am porting Wakaama to a new target and wondering about the purpose/intent of the following functions located in system_api.c when LWM2M_EMBEDDED_MODE is defined.

```
static void prv_value_change(void* context,
                             const char* uriPath,
                             const char * value,
                             size_t valueLength)
{
    lwm2m_uri_t uri;
    if (lwm2m_stringToUri(uriPath, strlen(uriPath), &uri))
    {
        handle_value_changed(context, &uri, value, valueLength);
    }
}

void init_value_change(lwm2m_context_t * lwm2m)
{
    system_setValueChangedHandler(lwm2m, prv_value_change);
}
```

I actually had LWM2M_EMBEDDED_MODE not defined and my system was working OK. So it appears these definitions may be optional?

**Comment by sbertin-telular** [comment]
I had not noticed that before, and have Wakaama working on our device using our own client code. It looks like the intent is to register a callback that is called when something changes. I would definitely consider it optional.

**Comment by sbernard31** [comment]
@JRubis, could we close this issue now ?
