### ISSUE TITLE
Why does wakaama not support UTC+13 time zone?

### ISSUE THREAD

**Issue by PetroShevchenko** [eclipse/wakaama#452]
According to wiki page https://en.wikipedia.org/wiki/UTC%2B13:00 time zone UTC+13 is used in Samoe and Tokelau. But function prv_check_time_zone from examples/client/object_device.c perceives this time zone as erroneous. 
Does ISO8601 really not support UTC+13? Or is it a bug in prv_check_time_zone?

**Comment by sbertin-telular** [comment]
I would assume it is a bug in prv_check_time_offset. According to https://en.wikipedia.org/wiki/List_of_UTC_time_offsets the range should be -12 to +14.

**Comment by sbernard31** [comment]
Fixed by #534.
