### ISSUE TITLE
should ip change trigger reregister

### ISSUE THREAD

**Issue by ephimee** [eclipse/wakaama#454]
When my client is registered and the local IP changes, any message sent to the server is answered with a 4 byte RST message (in case of Leshan server).
Then all observes are cleared in the client, but I would expect the client to also send a new register message notifying the server of the new IP address.
I'm trying to either use lwm2m_close() or try with lwm2mH->state = STATE_INITIAL but I do not know what is the best way?

**Comment by erkki** [comment]
If the IP changes, the client should send a registration update with `lwm2m_update_registration`.

In addition, if DTLS is used, the story becomes different, as there's relaxed session based matching in leshan with the DTLS CID extension. https://github.com/eclipse/californium/issues/824

**Comment by sbernard31** [comment]
@ephimee do you finally find a way ? Should we close this issue ? 

About ip changing @erkki is right you need to send a registration update.
If you are using DTLS, you probably need create a new DTLS connection (look at https://github.com/eclipse/leshan/wiki/LWM2M-Observe#requestnotifications-matching)

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
