### ISSUE TITLE
The client directly collapse.

### ISSUE THREAD

**Issue by liu583685** [eclipse/wakaama#456]
All configuration is the default configuration, the client starts with a different port number.
Use the server to read the client /5/, the client directly collapse.

Server command:   
            read 0 /5/
Client response log:

12 bytes received from [127.0.0.1]:9999
44 01 20 B8  B8 20 9D 8C  B1 35 61 6E   D. .. ...5an
#> failed sending 171 bytes
#> failed sending 4 bytes
 -> State: STATE_READY
12 bytes received from [127.0.0.1]:9999
44 01 20 B8  B8 20 9D 8C  B1 35 61 6E   D. .. ...5an
Segmentation fault (core dumped)

**Comment by sbertin-telular** [comment]
I believe this is an issue in the JSON serializer. I don't remember exactly what the problem was, but I've fixed it on my lwm2m_1.1 branch (https://github.com/sbertin-telular/wakaama/tree/lwm2m_1.1).

**Comment by liu583685** [comment]
Ok, problem solved. Thank you again and again
