### ISSUE TITLE
test client crashed with segmentation fault with coap://leshan.eclipseprojects.io:5683 

### ISSUE THREAD

**Issue by mailyuanhao** [eclipse/wakaama#457]
test client  often crash when the network environment is poor.

[core.zip](https://github.com/eclipse/wakaama/files/3868096/core.zip)

**Comment by sbernard31** [comment]
I guess without more information, we will not be able to do anything.

@mailyuanhao  do you still face this issue ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
