### ISSUE TITLE
READ /5/0 returned non IPV4 or IPV6 Segmentation Fault - LWM2M client crashed

### ISSUE THREAD

**Issue by JF64** [eclipse/wakaama#462]
running LWM2M client on a Raspberry PI 2 Model B, LWM2M client keeps crashing with READ /5/0

_**pi@raspberrypi:/opt/client $ ./lwm2mclient -n jemenapoc -p 5683 -4 -h leshan.eclipseprojects.io
Trying to bind LWM2M Client to port 56830
LWM2M Client "jemenapoc" started on port 56830
> #> failed sending 158 bytes
 -> State: STATE_REGISTERING
22 bytes received from [23.97.187.154]:5683
64 41 9F B3  B3 9F 03 F2  82 72 64 0A  66 32 46 47   dA.......rd.f2FG
4D 33 31 37  34 30                                   M31740
 -> State: STATE_READY
19 bytes received from [23.97.187.154]:5683
48 01 35 CD  98 7B 6C F6  CE C9 F5 ED  B1 35 01 30   H.5..{l......5.0
62 2D 16                                             b-.
#> failed sending 52 bytes
#> failed sending 4 bytes
 -> State: STATE_READY
19 bytes received from [23.97.187.154]:5683
48 01 35 CD  98 7B 6C F6  CE C9 F5 ED  B1 35 01 30   H.5..{l......5.0
62 2D 16                                             b-.
non IPV4 or IPV6 address
Segmentation fault**_

I have been able to reproduce this error consistently using the leshan server available at leshan.eclipseprojects.io  and also with  a LWM2M server from a Vendor. It seems that always happens when all resources associated at instance 5 are read (/5/0), it doesn't fails when each resource from instance 5 is read individually.

Error returned by leshan server is: _unable to read /5/0 for XXXX: 500 Request Timeout_

Trace attached on LWM2M client side:
[failure.zip](https://github.com/eclipse/wakaama/files/4169151/failure.zip)

LWM2MClient:
[client.zip](https://github.com/eclipse/wakaama/files/4169153/client.zip)

Any suggestion?

**Comment by sbertin-telular** [comment]
Change line 91 of examples/client/object_firmware.c from:
*dataArrayP = lwm2m_data_new(3);
to:
*dataArrayP = lwm2m_data_new(6);

That should fix the problem.

**Comment by JF64** [comment]
Thanks mate, it went nice and sweet with this minor alteration.
