### ISSUE TITLE
write object failed if request set coap block2 option

### ISSUE THREAD

**Issue by xuyouming1986** [eclipse/wakaama#464]
I find that if i request read an object with large payload, wakaama do not use coap block transfer automatically.So i add coap bolck2 option to inform wakaama to use coap block2 transfer, and it worked. But when i write object, it failed with response code 402 and message "BlockOutOfScope", wakkama think request bock offset is 0 and reponse payload is also 0, so get this error.

two questions:
1、if response payload is 0, i think it should also work, right?
2、Is there a way when makaama find response payload is large it will automatically use coap block transfer?

**Comment by sbertin-telular** [comment]
This might be addressed by pull request #461. Can you check?

**Comment by qleisan** [comment]
@sbernard31 @sbertin-telular discussed this with @tuve - block transfer is implemented and 2) is ok. We don't understand scenario 1). Unless you (or somebody) can provide an explanation how to test this we recommend closing the issue.

**Comment by sbernard31** [comment]
@qleisan  I don't get 1) too :sweat_smile:  

@xuyouming1986 block transfer is available in master. (see #461) 
Feedback are welcome
I close this issue but feel free to reopen (or create a new one) if you find something wrong.
