### ISSUE TITLE
unable to connect to server.

### ISSUE THREAD

**Issue by hamidkavianathar** [eclipse/wakaama#465]
hi
I want to execute wakaama code to a microcontroller. I am using LwIP tcp/ip stack. for simplicity I am using light client application. I have some very basic question. the first one is in create_socket finction, after creating socket, you are binding it to an address. as much as I know in udp case the client side does not need to do this. 
thanks.

**Comment by sbertin-telular** [comment]
The create_socket function is also used by the server, which does need to bind the socket. What problem are you seeing?

**Comment by hamidkavianathar** [comment]
hi @sbertin-telular 
thanks for the reply. 
I ran light-client example successfully on my microcontroller and now I want to run the client example which has used dtls. I don't know how to set the port number. I have tried 5683, 5684, 5683 and 8080 but I can't connect to server. I have captured the packets between my PC and my microcontroller. here is the results:
No.	Time	Source	Destination	Protocol	Length	Info
452	114.648234	192.168.100.1	192.168.100.42	UDP	200	56830 → 8080 Len=158
474	116.654127	192.168.100.1	192.168.100.42	UDP	200	56830 → 8080 Len=158
484	118.660228	192.168.100.1	192.168.100.42	UDP	200	56830 → 8080 Len=158
2	0.000879	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
4	0.990676	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
6	1.194379	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
8	1.991385	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
10	3.448218	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
12	3.991074	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
14	4.444928	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)
19	5.445088	192.168.100.1	192.168.100.42	ICMP	70	Destination unreachable (Port unreachable)

**Comment by sbertin-telular** [comment]
The example server does not support DTLS. You might want to try the Leshan server if you need DTLS.

**Comment by hamidkavianathar** [comment]
Thanks for your attention.
I am using leshan server. My apologies I have forgotten to mention it.

**Comment by sbertin-telular** [comment]
I just did the following to connect to the Leshan test server. I hope it helps you.
mkdir ~/tmp
cd ~/tmp
git clone https://github.com/eclipse/wakaama.git
cd wakaama
git submodule init
git submodule update
mkdir ../build
cd ../build
cmake -DDTLS=1 ../wakaama/examples/client/
make
./lwm2mclient -h leshan.eclipseprojects.io -p 5684 -4  -n 123456789 -i identity1 -s 3131313131

**Comment by hamidkavianathar** [comment]
thanks for the reply.
I have a question. why have not you used -b? it's bootstrapping purpose. when must I use this flag? 
```
        case 'b':
            bootstrapRequested = true;
            if (!serverPortChanged) serverPort = LWM2M_BSSERVER_PORT_STR;
            break;
```

**Comment by sbertin-telular** [comment]
I didn't really think about bootstrapping. I was trying to give you an example with DTLS working. I've never tried bootstrapping with DTLS against the Leshan test server and I don't really know if it will give a secure connection to the registration server or not.

Bootstrapping is needed when the client needs the server and security objects from the bootstrap server.

I used the Leshan test server (see https://github.com/eclipse/leshan#test-server-sandbox).

**Comment by hamidkavianathar** [comment]
Hi
finally I did it. thank you for your attention and your kindness.
