### ISSUE TITLE
why does not wakaama support add resource?

### ISSUE THREAD

**Issue by zhenglining** [eclipse/wakaama#466]
in _lwm2m_object_t just has objID and instanceList, there's no something like resourceList to set resouce, so how can I register a uri contains resourceId like /1/0/1?

**Comment by sbertin-telular** [comment]
The resources are part of the code for the object.

**Comment by sbernard31** [comment]
@zhenglining does it answer to your question ? could we close this bug ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
