### ISSUE TITLE
[bug] coap parse error on 64 bits platform

### ISSUE THREAD

**Issue by Kevin0626** [eclipse/wakaama#467]
It only happens in release build mode. When you switch to debug build for debugging, then it is gone. It is quite confusing.

After spending some debugging effort, here is the root cause and fix:
https://github.com/eclipse/wakaama/blob/master/core/er-coap-13/er-coap-13.c
line 622:
  size_t option_length = 0;
change to:
unsigned int option_length = 0;

**Comment by Kevin0626** [comment]
https://github.com/Kevin0626/wakaama/commit/3adafb5bbe718285cb2312ecd5605cbb2bcc2503

**Comment by sbertin-telular** [comment]
I think this is a duplicate of #429 and is fixed by #432.

**Comment by Kevin0626** [comment]
@sbertin-telular  thanks! The PR for #432 is still open and this repo has no new submissions for more than a year. It looks there is no maintainers for this project now? @dnav
