### ISSUE TITLE
TimeStone

### ISSUE THREAD

**Issue by cruise2018** [eclipse/wakaama#477]
hi , I notice that the code has not been update for a long time while some some fixed features has been brought up. I want to know that is there any timestone for the new version?

**Comment by rettichschnidi** [comment]
There is work ongoing on Eclipse side in order to get @sbertin-telular and @mlasch and/or me commit permissions. Also, there will be an intermediate project manager. All of this should happen latest in September.

**Comment by sbernard31** [comment]
@cruise2018, See #488 to get more information about what is currently happening.

You'are asking for a new release for which purpose ?
Do you need a bug fix release ? (see #487) 
Or are you interested in new LWM2M 1.1 feature ?

**Comment by sbernard31** [comment]
I close this issue but please do not hesitate to answer to question above :point_up:  and to reopen if needed.
