### ISSUE TITLE
Are there relations between /1/0/17  /1/0/18  (LWM2M_SERVER_SEQ_DELAY_TIMER_ID)?

### ISSUE THREAD

**Issue by peyton-li** [eclipse/wakaama#478]
Dears:
  I want to know ,how to use resource  /1/0/17 and 1/0/18,
  when i set the resource 17 to 4, how can i set the resource 18? 
  are there some arithmetic between resource  /1/0/17 and 1/0/18?
  Thank you~~

**Comment by sbertin-telular** [comment]
The LWM2M specifications are available from http://openmobilealliance.org/wp/index.html. I suggest you review section 6.2.1.1 of http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.pdf. In short, /1/0/17 is the number of attempts and 1/0/18 is the delay between attempts. They can be set independently to meet your requirements.

**Comment by peyton-li** [comment]
thank you very much, i got it.

**Comment by jpradocueva** [comment]
I would suggest using this other link, which points to the overview page. From here you can click on the list of documents to download: http://www.openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html. 
Please let me know if I can be of any assistance. 
Joaquin, OMA Director of Technical Programs,

**Comment by peyton-li** [comment]
> I would suggest using this other link, which points to the overview page. From here you can click on the list of documents to download: http://www.openmobilealliance.org/wp/Overviews/lightweightm2m_overview.html.
> Please let me know if I can be of any assistance.
> Joaquin, OMA Director of Technical Programs,

yeah，this link your support can download the doc, thank you~
