### ISSUE TITLE
Possible NULL dereference in wakaama/core/observe.c

### ISSUE THREAD

**Issue by tluio** [eclipse/wakaama#481]
In function observe_step(), dataP is initialized with NULL. If LWM2M_URI_IS_SET_RESOURCE(&targetP->uri) returns false, dataP will be NULL in the whole function. However, dataP is dereferenced through dataP->type in some places. I am not sure if all of them are unreachable.

**Comment by sbertin-telular** [comment]
I think this is a good catch. The observe could be at the object or object instance level. If the server then sets a numeric attribute (which shouldn't happen, but could) I don't see anything to prevent a numeric attribute from being set. This would cause the dataP->type to be evaluated.

**Comment by qleisan** [comment]
@tluio @sbertin-telular I cannot find any issue based on this scenario. Any additional insights or can we dismiss this bug?

First dataP is set to NULL
https://github.com/eclipse/wakaama/blob/1b87c37096c1edfae7f4f964cb1306c0c883eb0f/core/observe.c#L523

When this if statement is false dataP remains NULL

https://github.com/eclipse/wakaama/blob/1b87c37096c1edfae7f4f964cb1306c0c883eb0f/core/observe.c#L535-L537

and execution continues in this for loop

https://github.com/eclipse/wakaama/blob/1b87c37096c1edfae7f4f964cb1306c0c883eb0f/core/observe.c#L580-L582

dataP is only used once and protected by check for NULL

https://github.com/eclipse/wakaama/blob/1b87c37096c1edfae7f4f964cb1306c0c883eb0f/core/observe.c#L778-L782

the loop and function exits

https://github.com/eclipse/wakaama/blob/1b87c37096c1edfae7f4f964cb1306c0c883eb0f/core/observe.c#L840-L844

**Comment by sbertin-telular** [comment]
I think this was fixed by 68b6c491d18effc7c312410f08a337e0d9f316e9.

**Comment by sbernard31** [comment]
So I can close this one?

**Comment by qleisan** [comment]
yes!
