### ISSUE TITLE
Version Release Issues

### ISSUE THREAD

**Issue by 879166906** [eclipse/wakaama#484]
Hello! We have noticed that no new version has been released for a long time. When will the new version be released?

**Comment by rettichschnidi** [comment]
A release date can not yet been communicated, but a new team is getting formed and will take over and resume the development within the next few weeks. Stay tuned!

**Comment by sbernard31** [comment]
@879166906, See #488 to get more information about what is currently happening.

You'are asking for a new release for which purpose ?
Do you need a bug fix release ? (see #487) 
Or are you interested in new LWM2M 1.1 feature ?

**Comment by sbernard31** [comment]
I close this issue but please do not hesitate to answer to question above :point_up:  and to reopen if needed.
