### ISSUE TITLE
Check uriP == NULL in senml_json_serialize() in senml_json.c line 1099

### ISSUE THREAD

**Issue by stefanfangvall** [eclipse/wakaama#504]

**Comment by sbertin-telular** [comment]
For future reference, line 1099 is the call to json_findAndCheckData().

**Comment by tuve** [comment]
This was originally reported to me and @stefanfangvall by a mutual former colleague of ours, since I though it would be a pity to let his findings be lost  asked @stefanfangvall just to report the lines that does not apply to #461 as issues. Sorry if this is a bit of confusing.

**Comment by sbernard31** [comment]
(I'm not sure but I flag this as an enhancement ? :thinking:)

**Comment by qleisan** [comment]
Submitted a PR that addresses the issue raised. Feedback is welcome - part of the bigger question about defining code style rules #513

**Comment by sbertin-telular** [comment]
Is this check intended as an optimization to return earlier, or is there an actual problem being addressed? From my reading of the code without #554 uriP is not used directly in senml_json_serialize(), but is passed to uri_toString() and then json_findAndCheckData(). uri_toString() already has checks for uriP being non-null. It will set depthP (baseLevel in senml_json_serialize()) to URI_DEPTH_NONE and return 0. json_findAndCheckData() will determine the desired level as URI_DEPTH_OBJECT and call prv_findAndCheckData(). With URI_DEPTH_OBJECT as the desired depth, prv_findAndCheckData() will return without using uriP.

**Comment by stefanfangvall** [comment]
If there is no risk to crash than it is okay to close this issue
