### ISSUE TITLE
block transfer unit tests broken

### ISSUE THREAD

**Issue by qleisan** [eclipse/wakaama#511]
While testing #461 (block transfer)

Suite: Suite_block1
  Test: test of test_block1_nominal() ...passed
  Test: test of test_block1_retransmit() ...Segmentation fault (core dumped)

**Comment by qleisan** [comment]
In PR #461 the "test_block1_retransmit()" is disabled. The test is considered faulty not the code. Should be revisited and re-enabled

**Comment by rettichschnidi** [comment]
@tuve Any chance you can take care of this?

**Comment by tuve** [comment]
I can have a look at

**Comment by rettichschnidi** [comment]
PR #682 will fix this.
