### ISSUE TITLE
New to Wakaama || Clarification with Examples

### ISSUE THREAD

**Issue by mini525** [eclipse/wakaama#516]
Hi folks, 

I am a newbie, 

I just started to learn Wakaama LwM2M. I am using raspberry pi as my environment went through the read me.md file and successfully created a client lwm2m and was able to view the same client id in leshan.ecpliseprojects.io.

In this, I tried to read the basic information like the manufacturer on the server-side by clicking read button, but the action is incomplete.

Also, I am trying to add a sensor here and view the same server-side. Where should I start with?

**Comment by qleisan** [comment]
Hi. You are spot on, there are improvements needed in documentation/examples/"user interface" to make this project more new-user friendly. And we are working on it - input like this is much appreciated.

Quick suggestions (respons might be a bit shorter/slower right now due to holidays for many active users including myself :)
- check what encoding is being used in Leshan (drop down in the top right of the web page). The wakaama client no longer support TLV since it now is aiming towards lwm2m 1.1 compatibility. Choose a json format
- try building/running the wakaama server locally.
- try downloading and running the leshan server locally
- (if you are familiar with it) check communication with wireshark.

**Comment by mini525** [comment]
Thanks qleisan, 
No problem I hope I have lot to learn and understand. I will wait for the people to come back from holidays.


![2020-12-24-015647_1920x1080_scrot](https://user-images.githubusercontent.com/76512837/103083012-63bc3380-45a9-11eb-8614-a9f2eebfe974.png)


- The same error I am receiving with JSON.

- I did build the server but not sure where to see the same.

- I will try to download and run the leshan server locally.

- I am not familiar with the wireshark will look at the same.

Happy Holidays all...

**Comment by qleisan** [comment]
Try with "SENML_JSON" (both "multi-value" and "single-value" dropdown). Do you get a successful response now?

**Comment by mini525** [comment]
Yeah I got something this time.

![2020-12-28-025912_1920x1080_scrot](https://user-images.githubusercontent.com/76512837/103199394-c585e180-48b8-11eb-8714-7e203a42fa6a.png)


I am trying to integrade DHT22 temperature and humidity sensor. I went through many links, they are using java ee with object id 3303 & 3304.

**Comment by qleisan** [comment]
Wakaama client supporting temperature object 3303 is now available [here](https://github.com/qleisan/wakaama).

`git checkout newTempObj`
`cmake -DCMAKE_BUILD_TYPE=Debug -S examples/client -B build-client` (debug is not needed)
`cd build-client`
`make`
`./lwm2mclient -4 -n client3303 -h leshan.eclipseprojects.io`

Go to [https://leshan.eclipseprojects.io/#/clients/client3303](https://leshan.eclipseprojects.io/#/clients/client3303) select "senml_json" in (single-value) dropdown. You should now be able to click "Sensor Value" and get a (fake) reading back. The value increases on every read. Expect no other functionality to work.. 
Hope this helps!

**Comment by mini525** [comment]
Hi Qlesian, 
When I try to execute the command I am getting the following error, 

error: pathspec 'newTempObj' did not match any file(s) known to git


![2021-01-04-014618_1920x1080_scrot](https://user-images.githubusercontent.com/76512837/103508221-a7772e80-4e2e-11eb-8e7b-4bc0825f685a.png)

However I was able to build the example\client.

I am also interested to know how to create a dht22.c which includes object id 3303 and 3304. Mapping the data to the real sensor attached to my Pi.

**Comment by qleisan** [comment]
Please try this (works for me :). Do you get a different result?
`mkdir tempclone`
`cd tempclone`
 `git clone https://github.com/qleisan/wakaama.git`
 `cd wakaama/`
 `git checkout newTempObj`
`git log --pretty=oneline -2`
```
eeb90b3a1f91fafa7a3b295ba77685f0a522e7c9 (HEAD -> newTempObj, origin/newTempObj) Add basic temperature object 3303
8784fac655f7baaed3ddc8fa9430655c851bb1f4 (origin/master, origin/HEAD, master) Fix DTLS connection_send in example code
```
NB the client will build even if you do not check out `newTempObj` but without any of the changes made to support 3303. Once you know how to add 3303 you will be able to add 3304 in a similar way.

**Comment by mini525** [comment]
I got it this time, thanks.

![2021-01-04-042816_1920x1080_scrot](https://user-images.githubusercontent.com/76512837/103520607-663e4900-4e45-11eb-8de6-2f7f7beb1b39.png)

I also got few questions,
1. How to identify the object name like this one 3303 was referred to newTempObj?
2. The file object_temperature.c was created into the client folder, so we should edit this file to map the real sensor data value?
3. What does this command line do? "git log --pretty=oneline -2"?
4. Should we check if the object is supported in client? or all the objects listed [here](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) will support by default?

**Comment by qleisan** [comment]
great!

1. `newTempObj` is only used as a branch name in git, it is not used in the source code. If you "diff" the `newTempObj` branch vs the `master` branch you can review the changes made to add support for 3303. This is a great way to learn!
2. Yes
3. It just prints out git log history in a compact way to verify that the commit `Add basic temperature object 3303` is present
4. You need to add support for all objects you need (except mandatory ones) in your client. The server recognizes many objects by default including 3303, 3304.

**Comment by sbernard31** [comment]
@mini525 here some documentation about object supporting at Leshan side : https://github.com/eclipse/leshan/wiki/Adding-new-objects

**Comment by mini525** [comment]
Hi Qlesian, 
I have modified the object_temperature.c file with respect to the Adafruit_Python_DHT sensor library.

I have connected the DHT sensor to pin 4 of my pi.

Kindly comment if I have made any mistakes in modifying the code.

[object_temperature.txt](https://github.com/eclipse/wakaama/files/5764578/object_temperature.txt)

Note: I have commented the line // Modified whichever I have added new with respect to the DHT sensor.

Thanks

**Comment by mini525** [comment]
> @mini525 here some documentation about object supporting at Leshan side : https://github.com/eclipse/leshan/wiki/Adding-new-objects

Thanks

> great!
> 
> 1. `newTempObj` is only used as a branch name in git, it is not used in the source code. If you "diff" the `newTempObj` branch vs the `master` branch you can review the changes made to add support for 3303. This is a great way to learn!
> 2. Yes
> 3. It just prints out git log history in a compact way to verify that the commit `Add basic temperature object 3303` is present
> 4. You need to add support for all objects you need (except mandatory ones) in your client. The server recognizes many objects by default including 3303, 3304.

Thanks

**Comment by qleisan** [comment]
Looks like you are on the right path. Build and run to sort out remaining issues (e.g. have you declared the "temp" variable?) 
Enjoy!

**Comment by mini525** [comment]
Hi Qlesian, 

Is there any IDE that I can use to compile, or organize the client folder as project to see the dependencies?

I tried to include the header file and compile it, but getting error when I build, 

/home/pi/tempclone/wakaama/examples/client/Adafruit_Sensor.h:161:1: error: unknown type name ‘class’
 class Adafruit_Sensor {

**Comment by qleisan** [comment]
Wakaama doesn't require or provide any specific IDE. It is a collection of C-files that can be imported to an IDE/editor of your choice.

You are mixing C and C++, this can get complicated. I pushed a commit `Demonstrate use of C++` to the same repo/branch as before `https://github.com/qleisan/wakaama.git` / `newTempObj ` that demonstrates how this can be done in a simple scenario. This should cover the foundation of what you need to do.

Somewhat simplified, you need to enable `project (lwm2mclient C CXX)` and use `extern "C"`

`git clone https://github.com/qleisan/wakaama.git`
`cd wakaama/`
`git checkout newTempObj`
`cmake examples/client -B build-client`
`cd build-client`
`make`
`./lwm2mclient -4 -n client3303 -h leshan.eclipseprojects.io`

Go to [https://leshan.eclipseprojects.io/#/clients/client3303](https://leshan.eclipseprojects.io/#/clients/client3303) select "senml_json" in (single-value) dropdown. You should be able to click "Sensor Value" and get a (fake) reading back.
You should now also get a printout "_**Inside 'mycppfun()' C++ functionmycppfun() returned 26**_". This C++ function can be rewritten to read the sensor value using C++. 
Good luck!

**Comment by qleisan** [comment]
@mini525 Did  you succeed in adding support for your sensor  (can we close this issue) ?
Any feedback to the wakaama project on the challenges involved?

**Comment by mini525** [comment]
Hi qleisan, 
No I have not yet completed and facing some header file issues again. 

I have downloaded some c coded file with linux headers but after installing the linux headers when I try to compile the code, I am getting the header file errror.

Should we write the drivers from scratch for the LwM2M or we can import the header files from other developers?

**Comment by qleisan** [comment]
My examples above show how you can add a new object and call c++ code from wakaama (when compiled as C-code). I hope it provided some help to you. It sounds like you now are working with other challenges. Ok to close this issue? You can always open a new when you face wakaama related issues.

**Comment by mini525** [comment]
Sure we can close this for now. Will get back when I face more issues.

**Comment by qleisan** [comment]
click the "close issue" button you have below :)
