### ISSUE TITLE
Endless loop when client responds with large payload without block transfer

### ISSUE THREAD

**Issue by mlasch** [eclipse/wakaama#536]
_Test scenario:_ A wakaama server issues a READ command to a client. 
When the client replies with a payload bigger than `REST_MAX_CHUNK_SIZE`, the wakaama server responds with "4.13 Entity too large" **and** advertises its configured block size with a new GET request and block2 option set. If the client does not handle the block2 GET correctly and again send a too large payload this results in an endless loop.
Ideas on how this can be handled, maybe a max retry count on the server side? I tested with wakaama server and zephyr lwm2m client.

**Comment by sbernard31** [comment]
>  A wakaama server issues a READ command to a client.
> When the client replies with a payload bigger than REST_MAX_CHUNK_SIZE, the wakaama server responds with "4.13 Entity too large"

We should not answer to a response with a response. You can not send a 4.13 in response to a 2.05.
I mean 4.13 is [client response code](https://tools.ietf.org/html/rfc7252#section-5.9.2).
So there is maybe a first issue here. (or maybe I don't get you?)

> If the client does not handle the block2 GET correctly and again send a too large payload this results in an endless loop.

It sounds there is another issue here.

I guess this could be resolved like this.
- IF server receive a too big payload to a request sent **without block2** option THEN it could retry with block2 option.
- IF server receive a too big payload to a request sent **with block2** option THEN it should consider there is nothing to do and so report the error to application layer.

I guess this should avoid the infinite loop ? :thinking:

**Comment by mlasch** [comment]
This screenshot illustrates a read command which shows the server behavior. (`REST_MAX_CHUNK_SIZE` is set to 512 on the server)
![zephyr_register_read_too_large](https://user-images.githubusercontent.com/17436433/107378788-989a3080-6aec-11eb-88f3-bc143ff39791.png)
This means the server should ignore the (too big) 2.05 response and only issue a new GET request with block2 set to `REST_MAX_CHUNK_SIZE`?

About your suggestions:
1. I agree, the server should indicate its block size with a second GET request.
2. If the client sends a block2 with a too big payload the server can still indicate its max. payload size with the block2 option. And hope the client can handle it correctly.

However after signaling its block size once, the server should stop trying and report an error.

**Comment by sbernard31** [comment]
> This screenshot illustrates a read command which shows the server behavior.

Generally this is better for analyzing to join the capture instead of a screenshot.

Looking at the screenshot, I see that I didn't understand you first point correctly.
The 4.13 is a response for the second GET request,  not a response for the 2.05 content response. So there is no issue here.

So it remains only the infinite GET issue.

@mlasch thx you very much for reporting this. :pray:

**Comment by mlasch** [comment]
I just found out that I have to gzip the file in order to attach a pcap:
[zephyr_register_read_too_large.pcapng.gz](https://github.com/eclipse/wakaama/files/5952329/zephyr_register_read_too_large.pcapng.gz)
The 4.13 has the same MID as the first GET and is a response to the the 2.05 response which also has the same MID. I agree its a bit messy in the screenshot.
`2001:db8::1` is the zephyr client, `2001:db8::2` is the wakaama server.

**Comment by sbernard31** [comment]
It's clearer with the capture, thx :pray:.
Sorry for confusion, but this change my understanding again about the first point :sweat_smile: ...
My first guess was right, there is an issue with the 4.13. It must not be send by the server when receiving a too big response. (unfortunately, I think there is no way in CoAP to inform the client in this case)

About the second point (infinite loop), 
Regarding the [RFC7959](https://tools.ietf.org/html/rfc7959#section-2.4) :
> To influence the block size used in a response, the requester MAY
   also use the Block2 Option on the initial request, giving the desired
   size, a block number of zero and an M bit of zero. A _"CoAP"_ server (_"in our case LWM2M client"_) MUST use
   the block size indicated or a smaller size.
   
I think behavior defined in https://github.com/eclipse/wakaama/issues/536#issuecomment-775965260 should be OK
- IF server receive a too big payload to a request sent without block2 option THEN it could retry with block2 option.
- IF server receive a too big payload to a request sent with block2 option THEN it should consider there is nothing to do and so report the error to application layer.

 If device can not use block2 option and payload is still too big, I think there is nothing more to do. This prevent infinite loop and avoid the need to add a new state (a kind of counter).

**Comment by tuve** [comment]
I agree with the solution @sbernard31 outlined.

**Comment by tuve** [comment]
This will be fixed by #542, see
[zephyr-wakaama.pcap.zip](https://github.com/eclipse/wakaama/files/6002759/zephyr-wakaama.pcap.zip)
 pcap

**Comment by tuve** [comment]
I am looking into rfc7252 about the response, when it is a piggyback response like this within an ack there is clear that it should not be any  response back. However I am not entirely sure what to do if it is a separate response in a confirmable. Should we just ack that message regardless if we can handle it or not or is it ok to respond with an error code? I guess it is the first but I would like to hear your thought as well. @sbernard31 @mlasch

**Comment by sbernard31** [comment]
I'm not sure to get you. 

> Should we just ack that message regardless if we can handle it or not or is it ok to respond with an error code? I guess it is the first

This is my understanding. Just sending the ACK. The ACK just means I get your message (response or request) nothing else more. Seperate response does not change that we can not answer to a response with a response so if we can not handle it, we just ignore it. The Foreign peer will not be aware we can handle it.
(optional) Ideally Wakaama should raise to the upper layer that it received a response it is not able to handle.

**Comment by mlasch** [comment]
I think rfc7959 is more clear on how to behave in different block-wise scenarios. In this case, example 3 in _3.1.  Block2 Examples_ shows how to handle a response when the server is not happy with the block size chosen by the client. In our case instead of sending an error to the client, the server should issue just a new GET with its preferred block size to the client.

(I'm using client/server in the lwm2m context, it's confusing with CoAP)

**Comment by tuve** [comment]
The question is actually not related to blocktransfer. It is rather if the (lwm2m) server makes a GET request and the client responds with an ACK and a piggyback payload, then we can't respond with anything. However it is possible that the client responds with an empty ACK and then a confirmable (CON) message with the payload. The question is should we always ACK this CON or is it in this scenario possible to respond with an error code?

**Comment by tuve** [comment]
When I think about it should be that we always ACK only, it is a response and not an request. We ACK that we have received it if there is any problem (like it is to large) it is up to the server to take appropriate action (like retrying the request as a block2).

**Comment by tuve** [comment]
[zephyr-wakaama.pcap.zip](https://github.com/eclipse/wakaama/files/6009057/zephyr-wakaama.pcap.zip)

Now we do not sent any error respones to a respone

**Comment by sbernard31** [comment]
@mlasch, if you want you could check if #542 works for you :)

**Comment by sbernard31** [comment]
fixed by #542
