### ISSUE TITLE
A client which connects to a server intermittently can't deregister

### ISSUE THREAD

**Issue by pehrnord** [eclipse/wakaama#556]
https://github.com/eclipse/wakaama/blob/c5c6d321d50ff0534a390acc2bd9db7de48da41d/core/liblwm2m.c#L79

A client which connects to a server intermittently can't deregister without calling lwm2m_close. This requires the client to call lwm2m_init on each connection.
Should lwm2m_deregister be part of the interface for a client (include in liblwm2m.h)?

**Comment by sbertin-telular** [comment]
I agree. It seems like an oversight in the API.

**Comment by qleisan** [comment]
Created PR that simply adds `lwm2m_deregister()` to `liblwm2m.h` 

This function sends deregistration (COAP DELETE) to ALL connected servers eventually (normal flow) causing client state to be STATE_BOOTSTRAP_REQUIRED. State chart [here](https://github.com/eclipse/wakaama/issues/406#issuecomment-776066663)

**Comment by pehrnord** [comment]
This looks good to me!
