### ISSUE TITLE
PR: Allow setting reviewers

### ISSUE THREAD

**Issue by rettichschnidi** [eclipse/wakaama#571]
When creating PRs, I'd like to be able to specify reviewers, but GitHub does not allow me to. Maybe this is because I am not a committer?

@sbernard31 Can you please enable this?

**Comment by sbernard31** [comment]
I think committer right is needed : 

> Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

(source : https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)

**Comment by rettichschnidi** [comment]
Too bad -> closing

**Comment by sbertin-telular** [comment]
@sbernard31, is it time to hold a committer election for @rettichschnidi or do you think there is not enough history yet?

**Comment by sbernard31** [comment]
That's funny because since yesterday I plan to discuss today with the team about electing new committers. :grin:
