### ISSUE TITLE
Recruiting new committers. 👷‍♀️

### ISSUE THREAD

**Issue by sbernard31** [eclipse/wakaama#572]
Since the project revival (#488), there are many active contributors.
I think this is time to promote at least some of them as committer. 

Team would you prefer to talk about it publicly using this issue or do you prefer to use private channel ?

**Comment by sbernard31** [comment]
@sbertin-telular , @rettichschnidi, @qleisan , @tuve, @mlasch ?

**Comment by sbertin-telular** [comment]
I'll be unavailable for the next two weeks, so I'll leave it up to the others.

**Comment by rettichschnidi** [comment]
> Team would you prefer to talk about it publicly using this issue or do you prefer to use private channel ?

+1 for public

**Comment by rettichschnidi** [comment]
> I'll be unavailable for the next two weeks, so I'll leave it up to the others.

Will you skip voting or are you not available for nomination?

**Comment by sbertin-telular** [comment]
> Will you just skip the discussion or are you not available for being nominated?

Both. I was previously elected, but not allowed to accept by my employer.

**Comment by sbernard31** [comment]
> but not allowed to accept by my employer.

![sad](https://media.giphy.com/media/M28rUlcjueKUE/giphy.gif)
Really so bad, as you are a key member of Wakaama community. It would have been great to have you as committer or even project lead. Hoping you will still be at least an active contributor. :slightly_smiling_face:

**Comment by rettichschnidi** [comment]
Unsure if my track record is good enough yet, but I'd like to become a committer.

**Comment by sbernard31** [comment]
(I didn't get so much feedback about discussing this publicly, I hope this is OK for all of you :grimacing:)

From what I saw until now, I feel all people mentioned above showed enough investment in this project and also have the cooperative mindset needed to be committer. :+1: We will see if  PMC agree with this. 

@rettichschnidi is OK to be committer. 
@qleisan , @tuve, @mlasch is it something you would like too (I'm mean to be a committer on Wakaama project) ? 

Does your employer sounds OK with this idea ?

About, legal paper work, I'm not 100% sure but : 
Each committer will have to accept the terms of the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) electronically (ECA) and to provide a signed Eclipse [Individual Committer Agreement](https://www.eclipse.org/legal/committer_process/EclipseIndividualCommitterAgreement.pdf) (ICA).  (Note that as contributor you probably already accept the ECA).  The legal department of your company will likely want to review the ECA and ICA  before you sign. 

Alternatively, if your organization becomes a member of the Eclipse Foundation, all of your company's employees can be covered by a [Member Committer and Contributor Agreement](https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf). If your company is interested by being an Eclipse Member, you should contact [Frédéric Desbiens](mailto:frederic.desbiens@eclipse-foundation.org) / @fdesbiens.

Just to in case I share [this post](https://blogs.eclipse.org/post/wayne-beaton/becoming-eclipse-committer) which explains a little bit the role and responsibility of committers.
For [more details](https://www.eclipse.org/projects/handbook/#contributing-committers).

**Comment by mlasch** [comment]
> (I didn't get so much feedback about discussing this publicly, I hope this is OK for all of you :grimacing:)

:+1:

I would be happy to support the project as a committer.

**Comment by rettichschnidi** [comment]
> Does your employer sounds OK with this idea ?

Husqvarna (@tuve, @mlasch, me) is.

**Comment by sbernard31** [comment]
> Husqvarna (@tuve, @mlasch, me) is fine with it.

@rettichschnidi, if you are several in same company maybe it worth to sign a  [Member Committer and Contributor Agreement](https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf), I advice you to discuss about this with @fdesbiens.

I will start an election process for you in a first time. 
For @mlasch, we could try or maybe we wait just a little bit more than you provide [some more PRs](https://github.com/eclipse/wakaama/pulls?q=is%3Apr+author%3Amlasch+) ? 

@rettichschnidi, @mlasch,  I need to use an email address to identify you, I guess I use the one you are using to sign your commit ?

**Comment by rettichschnidi** [comment]
> @rettichschnidi, @mlasch, I need to use an email address to identify you, I guess I use the one you are using to sign your commit ?

Yes, should work.

**Comment by sbernard31** [comment]
In fact your address is already used in public place with github  (e.g. :https://github.com/eclipse/wakaama/pull/580/commits/8da76eae78a26c144566adca8f460e82e0e17075)
But maybe you want to use another address than this one ? 

I don't know exactly how this address is used but AFIAK I don't think that this address will not be used for mailing list automatically. Meaning that if you don't want to subscribe or use another address this should be possible (:warning: I'm clearly not 100% sure)

As far as I get your green light and the email address to use, I start the election.

**Comment by rettichschnidi** [comment]
@sbernard31 Yes, I am talking about another address. I am aware that addresses become publicly known as soon as they get used to commit to a public Git repository.

To avoid more delays, please use the address I am using to commit.

**Comment by sbernard31** [comment]
Waiting for vote : https://projects.eclipse.org/projects/iot.wakaama/elections/election-reto-schneider-committer-eclipse-wakaama

**Comment by tuve** [comment]
I am fine with being a committter as well, if the track record is good enough.

**Comment by tuve** [comment]
> > Husqvarna (@tuve, @mlasch, me) is fine with it.
> 
> @rettichschnidi, if you are several in same company maybe it worth to sign a [Member Committer and Contributor Agreement](https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf), I advice you to discuss about this with @fdesbiens.
> 
I know this has been in progress, I can check the status of becoming a member.

**Comment by rettichschnidi** [comment]
> I know this has been in progress, I can check the status of becoming a member.

Thanks!

Meanwhile, I'll sign the ICA anyway.

**Comment by sbernard31** [comment]
> I am fine with being a committter as well, if the track record is good enough.

Good to know, I will check this. 

Just missing the @qleisan answer. Too many suspense !!
<img src="https://media.giphy.com/media/tJ6dpaGeT8ATK/giphy.gif"  width=200/>

**Comment by sbernard31** [comment]
:confetti_ball: @rettichschnidi election is [**approved**](https://projects.eclipse.org/projects/iot.wakaama/elections/election-reto-schneider-committer-eclipse-wakaama) !! :tada:   
(Just missing some paperwork stuff before this was effective, I guess)

**Comment by sbernard31** [comment]
@tuve, @mlasch I would like to start election for both of you. 

Could you confirm I can use email address used in your commit ? 
For @tuve : https://github.com/eclipse/wakaama/pull/461/commits/249408faa76871d1419f0e5a85441b1c2dba42a0
For @mlasch : https://github.com/eclipse/wakaama/pull/579/commits/25e3fa4cd64de25da6dc31e3ea78875730da5c42

**Comment by tuve** [comment]
I have two email addresses linked to my github account, maybe you should use my main address instead.

**Comment by sbernard31** [comment]
Do you signed ECA for both of them ?

**Comment by tuve** [comment]
No only for the husqvarnagroup.com address, but there is no issue for me to sign it for my other email address.

**Comment by sbernard31** [comment]
Ok I will try with the one visible on your profile (@tuve) ?

**Comment by mlasch** [comment]
Sounds good, yes you can use the email address from my commits for the election.

**Comment by sbernard31** [comment]
@mlasch I double checked your contribution. Maybe a bit lighter than the others. Do you have new PRs in the pipeline ? 
If yes maybe we wait for this ones, if not I will try anyway with  what we have currently.

**Comment by mlasch** [comment]
> Do you have new PRs in the pipeline ?
I will continue to contribute, no ready-to-push PRs right now.

We can revisit the discussion on a later point when I got more contributions.

**Comment by sbernard31** [comment]
> We can revisit the discussion on a later point when I got more contributions.

As you prefer. Just to let you know, even if we try now and it failed, we can re-try later but my bet is this will not fail. I just asked in case you have 1 or 2 PR almost ready. So it's like you prefer, on my side I ready to start the election if you want.

**Comment by sbernard31** [comment]
Waiting for vote : https://projects.eclipse.org/projects/iot.wakaama/elections/election-tuve-nordius-committer-eclipse-wakaama

**Comment by mlasch** [comment]
> As you prefer. Just to let you know, even if we try now and it failed, we can re-try later but my bet is this will not fail. I just asked in case you have 1 or 2 PR almost ready. So it's like you prefer, on my side I ready to start the election if you want.

So let's do it. :+1:

**Comment by sbernard31** [comment]
@mlasch, waiting for vote : https://projects.eclipse.org/projects/iot.wakaama/elections/election-marc-lasch-committer-eclipse-wakaama

**Comment by qleisan** [comment]
@sbernard31 sorry for my late reply. Not sure how long I will be able to actively contribute. If it is acceptable to become a committer without without making a long term commitment, I'd be happy to take on the role. If not, better to wait and see if I can make such a promise at a later date.

**Comment by sbernard31** [comment]
> sorry for my late reply. 

@qleisan no problem. There was no urgency.

> Not sure how long I will be able to actively contribute. If it is acceptable to become a committer without without making a long term commitment

It's a good question :thinking:. 
Stop contributing at some time is "normal" for an committer. So I would say this should not be an issue, in the other hand if you think this is possible that you stop investing time in 1 or 2 month maybe it isn't worth all the paperwork . :grin:.

**Comment by sbernard31** [comment]
:confetti_ball:  @mlasch and @tuve election **approved** ! :tada:

**Comment by mlasch** [comment]
Happy to be on board!

**Comment by sbernard31** [comment]
@qleisan, I get feedback from eclipse and each project defines its own rules and responsibility about being a committer. This should be applied to all possible contributors. Of course this must not conflict with any eclipse rules. 

Previously there is nothing clear about long term engagement, so I don't know if we should apply it now. Anyway,  this is maybe something that team should clarify at mid-term.

Concerning you about being committer : 
 - Regarding you previous contribution, I feel you deserve it as much as the others,
 - But **you should be comfortable with the idea** and  if you prefer to keep contributor for now, it's OK. 

In a practical way :
 - if you think this is possible you stop to contribute in 1 or 2 month, this maybe doesn't worth the paperwork.
 - do you know what could give you more visibility about a longer-term commitment on the project  ?

**Comment by qleisan** [comment]
Having thought about it and checked with my employer (no objections, quite the opposite) I'd like to become a committer as well!

**Comment by sbernard31** [comment]
@qleisan Should I use the address you are using to sign commit ? (e.g. https://github.com/eclipse/wakaama/pull/566)

**Comment by qleisan** [comment]
No, better to use "leif.sandstrom@cybercom.com".

**Comment by sbernard31** [comment]
I tried to start election with this address and get an error message:  :x:  **Please insert a valid user**.

I'm not sure why ? :thinking: maybe because this address is not linked to your eclipse account ?

**Comment by qleisan** [comment]
Updated so my eclipse account use the address above. Thought I had both addresses linked to the account but that was not the case.

**Comment by sbernard31** [comment]
@qleisan waiting for vote : https://projects.eclipse.org/projects/iot.wakaama/elections/election-leif-sandstr%C3%B6m-committer-eclipse-wakaama

**Comment by sbernard31** [comment]
:confetti_ball: @qleisan election **approved** ! :tada:

**Comment by sbernard31** [comment]
I see that everybody is listed as committer in : https://projects.eclipse.org/projects/iot.wakaama/who

The team is ready. :sunglasses: 

![team walk ](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FQRXwbVxk1oViM%2Fgiphy.gif&f=1&nofb=1)

I can not see more candidate for now, so I close this issue, hoping new contributors could become committers in a near future.

**Comment by sbernard31** [comment]
Hi guys, I noticed that there is not so much activity since end of May, I'm a bit worry about this ?

**Comment by tuve** [comment]
The project @qleisan was working almost full time on ended end of May and that was a major driving force. Now I think the most of us are on vacation. I am still working but very much involved in different tasks so I don't have the time I would like to spend on this project as of now. We are still using wakaama and as far as I know there is no plans of any changes in that respect, so I think things will pickup again. In Sweden things slow down in June, nothing happens ind July and things slowly picks up again in August. So for now 🏖.

**Comment by sbernard31** [comment]
Thx for the feedback. :relieved:

**Comment by mlasch** [comment]
There is a similar situation here, focus shifted a bit away in the past weeks, now vacation time started. Long term commitment is still in favor of Wakaama.
