### ISSUE TITLE
Git Commit Format

### ISSUE THREAD

**Issue by rettichschnidi** [eclipse/wakaama#585]
The [Eclipse Foundation Project Handbook](https://www.eclipse.org/projects/handbook/#resources-commit) specifies how a Git commit must look like in order to be acceptable.

The following rule is mandatory, could be checked automatically but is currently now:
* Summary is max. 72 characters

The following rule is not mandatory ("should"), but when implementing the above as a checked in CI, I'd like to enforce it too:
* Existence of a description

**Comment by sbernard31** [comment]
I will no write too much commit so this is clearly a decision on your side but I'm not sure making the description mandatory is a good idea. Sometime there is nothing much to say than just the summary.

**Comment by rettichschnidi** [comment]
I know Zephyr has this rule. While not always too sensible (e.g. https://github.com/zephyrproject-rtos/zephyr/commit/22a82bc05432bd8db8dc1fe369d828150c80a2ee), it seems to me that it encourages greatly to come up with helpful commit messages.

For example, most of the last 20 commit messages in https://github.com/zephyrproject-rtos/zephyr/commits/zephyr-v2.5.0 makes me feel like I have a shot at understand the commits intention thanks to the additional information in the body.

**Comment by mlasch** [comment]
From personal experience I can say, that being forced to write a description is sometimes annoying. However it forces yourself to think again about the commit. Also the workaround mentioned by @rettichschnidi works for small changes. I would support such a rule.

**Comment by qleisan** [comment]
Naming and explaining is usually the hardest part, but very important. I'm for (although I will regret it :)

**Comment by rettichschnidi** [comment]
After all those force-pushes, I think the PR #590 is now in a good shape and ready to be reviewed.

**Comment by rettichschnidi** [comment]
Just merged PR #590, which covers this issue.
