### ISSUE TITLE
MAX_BLOCK_SIZE not used

### ISSUE THREAD

**Issue by xuyouming1986** [eclipse/wakaama#671]
In master branch， we defined macro MAX_BLOCK_SIZE in block.c ， but we did not used，is that intended？
Note that in old version, we limitted total payload size in blockwised transfer.

// the maximum payload transferred by block we accumulate per transfer
#ifndef MAX_BLOCK_SIZE
#define MAX_BLOCK_SIZE 4096
#endif

**Comment by mlasch** [comment]
Hello @xuyouming1986, you are right `MAX_BLOCK_SIZE` is not used (anymore). In the current master the coap block size is either set at build time via `LWM2M_COAP_DEFAULT_BLOCK_SIZE` or at runtime with the `lwm2m_set_coap_block_size()` setter function.
The macro `MAX_BLOCK_SIZE` could well be removed.
