### ISSUE TITLE
How to connect to leshan server

### ISSUE THREAD

**Issue by TUT-jiayou** [eclipse/wakaama#673]
Hi,all
* I try some methods to connect leshan lwm2m server
`./lwm2mclient -n tut_test_for_now -h leshan.eclipseprojects.io  -p 5783 -b -4`
![image](https://user-images.githubusercontent.com/21277368/198316055-37ef2e67-36f8-4def-a91e-c5190f256d6a.png)
` ./lwm2mclient_tinydtls -h leshan.eclipseprojects.io -4 -p 5784 -n wakaama-560-with-dtls -i wakaama-560-with-dtls -s 5cdafa07cf5d7e0e65b8e504bc0dc9 -b`
![image](https://user-images.githubusercontent.com/21277368/198316237-7d6198a5-4679-4adb-9105-82daef825976.png)
* I use master brance code
* I try use leshan client demo to connect wakaama server successfully.
* would someone give me some guide and help? Thanks for your help.

**Comment by sbernard31** [comment]
In your first screenshot, the message says : "no bootstrap config'

So I guess you don't add a bootstrap configuration for your device in : https://leshan.eclipseprojects.io/bs/#/bootstrap

I see your device endpoint name is : `tut_test_for_now` searching in https://leshan.eclipseprojects.io/bs/#/bootstrap UI interface I can see any configuration for it...

(By the way, can someone explain me why there is so many people who share textual information with screenshot  ? :thinking:  )

**Comment by boaks** [comment]
> By the way, can someone explain me why there is so many people who share textual information with screenshot ? 

Yes, because movies are too large :-).

**Comment by TUT-jiayou** [comment]
thanks for your time. 
sorry, I will use textual format for better reading.
* for `./lwm2mclient -n tut_test_for_now -h leshan.eclipseprojects.io -p 5783 -b -4` ,  just add name ,then device is added successfully.
![image](https://user-images.githubusercontent.com/21277368/198324956-89722169-6eaf-4157-b2ca-d3e089683eca.png)

* for ` ./lwm2mclient_tinydtls -h leshan.eclipseprojects.io -4 -p 5784 -n  tut_test_for_now  -i xsgadgaasgs -s 5cdafa07cf5d7e0e65b8e504bc0dc9 -b` , need to add secure information in  lwm2m server and bootstrap server using coaps protocol.
![image](https://user-images.githubusercontent.com/21277368/198330883-d24a3c8e-bc73-45ec-9589-58a678b7134f.png)
![image](https://user-images.githubusercontent.com/21277368/198330990-7cd2ac1e-c473-4566-992c-4e446cdf0283.png)

* this may be  helpful for someone like me. It is time to sleep. Bye Bye !
