### ISSUE TITLE
Where is freed dtlsSession ?

### ISSUE THREAD

**Issue by parmi93** [eclipse/wakaama#675]
An object of type `session_t` is allocated in the examples/shared/dtlsconnection.c file on line 428
`connP->dtlsSession = (session_t *)malloc(sizeof(session_t));`

I was wondering where is this object deallocated?
I am porting Wakaama to a non-posix platform, trying to keep as close as possible to the examples, but I could not find the point where I should deallocate this object.

**Comment by boaks** [comment]
Not sure, how that is done in wakaama, tinydtls offers some functions for that.

[session.h](https://github.com/eclipse/tinydtls/blob/main/session.h#L114-L130)

Tinydtls also keeps the "session" in the peer, and doesn't use the pointer after returning from functions.

Many examples don't shutdown/free the resources, especially, if the example consider that this is done on exit anyway.

**Comment by sbernard31** [comment]
It's just an example so, I will not be totally surprised if this was not done.
