### ISSUE TITLE
[BUG] senml_json_parse(...) LOG_ARG

### ISSUE THREAD

**Issue by parmi93** [eclipse/wakaama#676]
I noticed that the payload for write commands sent from Leshan do not have the terminator character at the end of the string, so to avoid memory overflow I had to change this line:
`LOG_ARG("bufferLen: %d, buffer: \"%s\"", bufferLen, STR_NULL2EMPTY((char *)buffer));`
to
`LOG_ARG("bufferLen: %d, buffer: \"%.*s\"", bufferLen, bufferLen, STR_NULL2EMPTY((char *)buffer));`

**Comment by rettichschnidi** [comment]
TIL: There is a .* specifier. Nice!

Do you know if this is (typically) supported on Embedded platforms? Wondering if using this solution would break the code e.g. for the use cases of @sbertin-telular.

**Comment by sbertin-telular** [comment]
I use .* frequently. I doubt there would be an issue for most embedded platforms. Floating point and wide characters are more likely to be issues than supplying a string length.

**Comment by parmi93** [comment]
> TIL: There is a .* specifier. Nice!
> 
> Do you know if this is (typically) supported on Embedded platforms? Wondering if using this solution would break the code e.g. for the use cases of @sbertin-telular.

I use .* frequently on my embedded platform (Quectel BG95) and it work without any issues.

But if this is your concern, then there might be other format specifiers that might not be supported by embedded platforms, for example in my case %f is not supported, but that is used by Wakaama (in observe.c and data.c)

**Comment by rettichschnidi** [comment]
I knew about %f being expensive, thus often missing or disabled. Good to know that .* is more common.

@parmi93 Any chance to get a PR from you for this? Alternatively, I can do it. Just let me know.

**Comment by rettichschnidi** [comment]
[Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
