### ISSUE TITLE
[BUG?] Memory leak if the client fails to register with the server

### ISSUE THREAD

**Issue by parmi93** [eclipse/wakaama#693]
It took me a while to figure out where this memory leak occurred, but I'm still not entirely sure if it's a Wakaama bug, or my misuse of this library.

This is the [`lwm2m_transaction_t`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/include/liblwm2m.h#L685) struct:
```c
/*
 * LWM2M transaction
 *
 * Adaptation of Erbium's coap_transaction_t
 */

typedef struct _lwm2m_transaction_ lwm2m_transaction_t;

typedef void (*lwm2m_transaction_callback_t) (lwm2m_context_t * contextP, lwm2m_transaction_t * transacP, void * message);

struct _lwm2m_transaction_
{
    lwm2m_transaction_t * next;  // matches lwm2m_list_t::next
    uint16_t              mID;   // matches lwm2m_list_t::id
    void *                peerH;
    uint8_t               ack_received; // indicates, that the ACK was received
    time_t                response_timeout; // timeout to wait for response, if token is used. When 0, use calculated acknowledge timeout.
    uint8_t  retrans_counter;
    time_t   retrans_time;
    void * message;
    uint16_t buffer_len;
    uint8_t * buffer;
    size_t
        payload_len;  // the length of the entire payload, message payload might be smaller in case of a block1 transfer
    uint8_t *payload; // carries the entire payload across multiple transactions in case of a block 1 transfer
    lwm2m_transaction_callback_t callback;
    void * userData;
};
```
I noticed that the `userData` field is used/allocated by the [`prv_register`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/registration.c#L725) function, which is called when the client needs to be registered on the server, in this particular case `userData` is a pointer to another struct ([`registration_data_t`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/registration.c#L631)) which contains other pointers (`query` and `payload`) also allocated by the same [`prv_register`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/registration.c#L725) function.

The `userData` field is deallocated by the callback `lwm2m_transaction_t::callback` ([`prv_handleRegistrationReply`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/registration.c#L638)), this callback is called only when the server responds to the registration message via the [`transaction_handleResponse`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/coap/transaction.c#L287), or when the transaction expires via the [`transaction_send`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/coap/transaction.c#L368) function.

The issue is that if the server does not respond to the connection message or the user decides to quit the client before the server respond, the `userData` field will never be deallocated.

In the [`examples/client/lwm2mclient.c`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/examples/client/lwm2mclient.c) example, the user can quit the client by sending the `quit` command on the STDIN port, in this case the transaction list is deallocated by the [`prv_deleteTransactionList`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/liblwm2m.c#L168) called by [`lwm2m_close`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/liblwm2m.c#L180) function.
The problem is that [`prv_deleteTransactionList`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/liblwm2m.c#L168) does not deallocate the `userData` field of the transactions, actually it cannot deallocate this pointer, because of `void *` type, and this causes the memory leak.

To fix this issue I was thinking of modifying the [`prv_deleteTransactionList`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/liblwm2m.c#L168) function by calling the callback:
```c
void prv_deleteTransactionList(lwm2m_context_t * context)
{
    while (NULL != context->transactionList)
    {
        lwm2m_transaction_t * transaction;

        transaction = context->transactionList;
        context->transactionList = context->transactionList->next;
        if(transaction->callback) {
            transaction->callback(context, transaction, NULL);
        }
        transaction_free(transaction);
    }
}
```
But I'm not sure if that's the right way to fix this.

**Comment by parmi93** [comment]
Briefly, by adding the call to this callback the function [`prv_handleRegistrationReply`](https://github.com/eclipse/wakaama/blob/snapshots/2023-03-31/core/registration.c#L638) will be called, which [frees](https://github.com/eclipse/wakaama/blob/11662338212a8eb36353f42341e9b5d312c90255/core/registration.c#L715) the `userData`, `query` and `payload` fileds.

**Comment by mlasch** [comment]
Just to clarify, that I understand the problem correctly: The lwm2mclient starts, the server does not respond and then the client is stopped with the `quit` CLI command, in that case the userData is not freed?

**Comment by parmi93** [comment]
> Just to clarify, that I understand the problem correctly: The lwm2mclient starts, the server does not respond and then the client is stopped with the `quit` CLI command, in that case the userData is not freed?

Correct, this memory leak occurs when the client quits before the server responds.
