### ISSUE TITLE
[BUG?] lwm2m_handle_packet trying to free a NULL payload pointer

### ISSUE THREAD

**Issue by parmi93** [eclipse/wakaama#707]
I'm not sure if this can be considered a bug, also because this hasn't caused any problems so far (but could it be a problem on other devices?)

I noticed that [`lwm2m_handle_packet`](https://github.com/eclipse/wakaama/blob/514659414c792f8c252782af63551b6d09704a7b/core/packet.c#L480) frees the payload on line [644](https://github.com/eclipse/wakaama/blob/514659414c792f8c252782af63551b6d09704a7b/core/packet.c#LL644C17-L644C37) without taking into consideration that the payload may not exist, for example in case the client has to send a message without payload (which often happens during the bootstrap phase and connection to the LwM2M server).

It's an easy fix so I send a pull request:
https://github.com/eclipse/wakaama/pull/706

**Comment by rettichschnidi** [comment]
Not a bug because of this: https://github.com/eclipse/wakaama/pull/706#issuecomment-1570733465
