### ISSUE TITLE
LWM2M_WITH_LOGS can't display payload

### ISSUE THREAD

**Issue by ieei0214** [eclipse/wakaama#73]
In core/packet.c line 210

LOG("  Content type: %d\r\n  Payload: %.*s\r\n\n", message->content_type, message->payload_len, message->payload);

Add %d for message->payload_len =>

LOG("  Content type: %d\r\n  Lens: %d Payload: %.*s\r\n\n", message->content_type, message->payload_len, message->payload);

**Comment by dnav** [comment]
Thank you for pointing this. I plan a big pass on logs.
