### ISSUE TITLE
Moving from Master to Main

### ISSUE THREAD

**Issue by mlasch** [eclipse/wakaama#736]
Most mayor code hosting platforms changed the default branch name from `master` to the more neutral `main` in recent years.

I propose to change the default branch to `main` also for the Wakaama project.

**Comment by mlasch** [comment]
@sbernard31 can you look into this? It seems that committers do not have the permission to change the default branch.

**Comment by sbernard31** [comment]
@mlasch  unfortunately even project lead doesn't own this kind of "right".

If we want to change this, we need to ask that to eclipse foundation. By creating a [new issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk) project.

**Comment by mlasch** [comment]
I opened an issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4225

**Comment by rettichschnidi** [comment]
Done with admins and #751
