### ISSUE TITLE
Election of new committer

### ISSUE THREAD

**Issue by mlasch** [eclipse/wakaama#745]
I would like to propose to elect @LukasWoodtli as a new committer for the Wakaama project. He has made several important 
[contributions](https://github.com/eclipse/wakaama/commits?author=LukasWoodtli) in the last months and I think he would be a great help for the project going forward.

@sbernard31 how can we start an election process?

I create this issue since #572 was closed, where we discussed adding new committers last time.

**Comment by sbernard31** [comment]
> I would like to propose to elect @LukasWoodtli as a new committer for the Wakaama project.

Great news ! 

> I create this issue since https://github.com/eclipse/wakaama/issues/572 was closed, where we discussed adding new committers last time.

Eventually, you could have reopened it but creating a new one is good too. 

> how can we start an election process?

There is a description of the election process at : https://www.eclipse.org/projects/handbook/#elections-how
To start the election : 
 - go to the project page : https://projects.eclipse.org/projects/iot.wakaama
 - log you (if this is not already done)
 - and you should see committer tools on the right (like [this](https://www.eclipse.org/projects/handbook/#pmi-project-page))
 - then just click on : [**Nominate a Committer**](https://projects.eclipse.org/projects/iot.wakaama/nominate/CM)
 
 I just add some more useful link about being a committer : 
 - https://blogs.eclipse.org/post/wayne-beaton/becoming-eclipse-committer
 - https://www.eclipse.org/projects/handbook/#contributing-committers
 
 HTH :wink:

**Comment by mlasch** [comment]
> To start the election :

Thanks for the info, I started the election process. 👍🏼

**Comment by sbernard31** [comment]
(I just put the election link here : https://projects.eclipse.org/projects/iot.wakaama/elections/election-lukas-woodtli-committer-eclipse-wakaama)

**Comment by sbernard31** [comment]
> The Committer election for Lukas Woodtli on project Eclipse Wakaama
(iot.wakaama) has been approved by the PMC (khudalla). 

@LukasWoodtli  Welcome on board ! 

![welcome](https://media.giphy.com/media/VPcVGQVX5WOMU/giphy.gif)

(@rettichschnidi, @mlasch

**Comment by rettichschnidi** [comment]
Welcome!

**Comment by mlasch** [comment]
Do we need to open a ticket, to add @LukasWoodtli to get commiter rights on Github?

**Comment by boaks** [comment]
I would report it using a ticket. 
If you check the github profile, he is neither member of Eclipse nor a wakaama committer.

**Comment by LukasWoodtli** [comment]
Here is the state in my Eclipse account:

![image](https://github.com/eclipse/wakaama/assets/8074319/56c686f6-848a-4fc5-9063-38b976b1127c)

I don't know if this is synced automatically with GitHub or if we need to request the permissions for GitHub.

**Comment by LukasWoodtli** [comment]
Opened an issue on Eclipse IT helpdesk:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4266

**Comment by LukasWoodtli** [comment]
> Opened an issue on Eclipse IT helpdesk: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4266

Done!
