### ISSUE TITLE
How to use the wakaama library for Espressif

### ISSUE THREAD

**Issue by Hariprabhu13** [eclipse/wakaama#757]
Hi,
       I have developping the openthread device's and I want to implement the lwm2m client in it. So, anyone can tell me that it is supported esp32c6 device firmware's. And how to add the Library for my project to enable lwm2m client in it...

**Comment by jvermillard** [comment]
In the past, I started from the example (for example, the light client) and adapted the connection piece (socket) to replace the POSIX socket call with what is available for your target IP stack.

**Comment by Hariprabhu13** [comment]
Thanks for your reply @jvermillard 
                                                       In my end device I've using the UDP socket for Communicate from the Leshan server for Light Control, Instead of I'm want to use the LWM2M Client in my Device for Light Control from the Server...

**Comment by LukasWoodtli** [comment]
Try something like this:

1. Add the Wakaama repo as submodule to your project.
2. Include `wakaama.cmake` in your CMake project.
3. Call the CMake functions `target_sources_data` and `target_sources_wakaama` on your target.
4. Implement the C functions listed under `Platform abstraction functions to be implemented by the user`  in `liblwm2m.h` somewhere in your project.
5. Implement a connection with your UDP socket. Get inspiration from the examples (`examples/shared/`).
6. Take a suitable example as basis for your code. And work from there.

Feel free to ask for help if you get stuck. Unfortunately, we did not manage yet to write a tutorial on how to get started with Wakaama.

**Comment by Hariprabhu13** [comment]
Hi @LukasWoodtli ,
                       I'll try this in my code as your reference and Let you Know...

**Comment by LukasWoodtli** [comment]
Closing this issue due to no action lately.
@Harpabhu13 feel free to reopen it if you need support.
