### ISSUE TITLE
Question regarding the appropriate license for this project

### ISSUE THREAD

**Issue by roycyt** [eclipse/wakaama#760]
There is an inconsistency in the license declaration in the README.md. It states, "This work is dual-licensed under the Eclipse Public License v2.0 and Eclipse Distribution License v1.0," but uses a different SPDX-License-Identifier: "EPL-2.0 OR BSD-3-Clause".

**Comment by LukasWoodtli** [comment]
It seems that the "Eclipse Distribution License v1.0" is equivalent to the `BSD-3 Clause` license and uses that SPDX-License-Identifier.
See https://www.eclipse.org/org/documents/edl-v10.php
