### ISSUE TITLE
Project repository needs a CONTRIBUTING.md

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/wakaama#78]
The project repository needs a contribution guide. For guidance, please see:

https://wiki.eclipse.org/Architecture_Council/Contributor_Guide_Recommendation

**Comment by jvermillard** [comment]
I'm a bit sad to not see a PR on this topic :)

Anyway I would prefer to use the one from Leshan: https://github.com/eclipse/leshan/blob/master/CONTRIBUTING.md
which also explain the git commit -s in details

**Comment by dnav** [comment]
Fixed by #79
