### ISSUE TITLE
lightclient won't register

### ISSUE THREAD

**Issue by markbul** [eclipse/wakaama#90]
Hello, the lightclient doesn't work for me. While the lwm2mclient does. I really hope you can help me because I really need to make it work.
This is what I do:

I start the wakaama server, you told to say how did I start it, in this way:
(from the wakaama directory)
cmake tests/server
make
./lwm2mserver

And about the lightclient:
(from the tests directory, since that from wakaama I've just started the server so I cannot call cmake from there)
cmake lightclient
make
./lightclient

And about the lightclient:
(from the tests directory, since that from wakaama I've just started the server so I cannot call cmake from there)
cmake lightclient
make
./lightclient

As soon as I start the client, the client tells this (and this message is repeated several times every x seconds):
State: STATE_REGISTERING
No Bootstrap Server.
LWM2M Servers:
 - Server ID 123    status: REGISTRATION FAILED

At the same time the server says:
New client #0 registered.
Client #0:
    name: "testlwm2mclient"
    binding: "UDP"
    lifetime: 300 sec
    objects: /1/0, /3/0, /1024/10, /1024/11, /1024/12, 

> Sending 13 bytes to [::ffff:127.0.0.1]:56830
64 41 79 11  11 79 DC 7D  82 72 64 01  30  dAy..y.}.rd.0
110 bytes received from [::ffff:127.0.0.1]:56830
(then here there's the message received from the client)

I really hope you can help me. Furthermore I have another question: what are the characteristic of this lightclient compared to the lwm2mclient (that is the more complete one)? 

Thank you so much

**Comment by dogonthesun** [comment]
Look here https://github.com/eclipse/wakaama/blob/master/tests/lightclient/object_security.c#L222
Just change URL to coap://[::1]:5683

**Comment by markbul** [comment]
Thank you so much for your help, now it works :)

Just a little curiosity even though it's off topic:
In the client, after telling "State: STATE_READY", which looking at the code should mean that the client successfully registered, it says: "No Bootstrap Server." That means that it enters in this if: https://github.com/eclipse/wakaama/blob/master/tests/lightclient/lightclient.c#L207
What does it mean?

**Comment by dogonthesun** [comment]
It means that there is no bootstrap server. LWM2M spec may provide more additional info =)

**Comment by markbul** [comment]
Yeah I read the LWM2M spec, what I don't understand is that if there's no bootstrap server the registration couldn't occur... Because the client before to do the registration has to do the bootstrap

**Comment by dogonthesun** [comment]
Bootstrapping and registration are not depending on each other. Let's move our fireside talks to private dialog. It doesn't relate to wakaama.

**Comment by markbul** [comment]
You're actually right, we are a bit off topic here
