### ISSUE TITLE
Wakaama is corrupted when epname is too long

### ISSUE THREAD

**Issue by zhangbl1105** [eclipse/wakaama#91]
**Callstack:**

0xf7dbb770
coap_serialize_multi_option() at er-coap-13.c:225 0x8095dd3
transaction_send() at transaction.c:394
lwm2m_step() at liblwm2m.c
main()

**Analysis:**

If the EP is too long, and lead to the header is longer than COAP_MAX_HEADER_SIZE,  the coap_serialize_multi_option() return 0 and transaction->buffer would be assigned to NULL. 

But the coap_free_header is called and the **transcationP->message is freed partially.**

When re-send,transaction, coap_serialize_message is called again due to the NULL value of transaction->buffer,.................then the program is corrupted.

**Solution**

Remove the transaction if coap_serialize_message is failed

BR/Baoli

**Comment by dnav** [comment]
Thank you for spotting this.
Should be fixed by #93

**Comment by dnav** [comment]
Fixed by #93
