### ISSUE TITLE
Infinite bootstrapping loop when the BS delete its own account.

### ISSUE THREAD

**Issue by dnav** [eclipse/wakaama#96]
If the Bootstrap Server deletes or overwrites its own account, the status of the matching lwm2m_server_t is set to STATE_DIRTY then to STATE_BS_PENDING.
Then the server lists are not refreshed and the changes are not take into account.

**Comment by ieei0214** [comment]
@dnav 

STATE_DIRTY is just for tag server which is modified by bootstrap.  So I remove it and add bool dirty in lwm2m_status_t.

It can pass the server bs process.

**Comment by dnav** [comment]
Fixed by #98
