### ISSUE TITLE
*** glibc detected *** ./lwm2mclient: double free or corruption (!prev): 0x0018e640 *** Aborted

### ISSUE THREAD

**Issue by rafter1** [eclipse/wakaama#99]
The latest wakaama client crashes with the following error, after registration with server.

*** glibc detected *** ./lwm2mclient: double free or corruption (!prev): 0x0018e640 ***
Aborted

The ipv4 fix is working but the crash is making the latest version, unusable. 
Can you please fix the issue soon.

Thanks,
Rafeeq

**Comment by dogonthesun** [comment]
*** Error in `./lwm2mclient': malloc(): memory corruption (fast): 0x000000000177eaf0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x77da5)[0x7f919214dda5]
/lib64/libc.so.6(+0x823e9)[0x7f91921583e9]
/lib64/libc.so.6(__libc_malloc+0x50)[0x7f9192159950]
./lwm2mclient(lwm2m_malloc+0x18)[0x407e41]
./lwm2mclient(coap_add_multi_option+0x23)[0x418d4a]
./lwm2mclient(coap_set_header_uri_path+0x9f)[0x41a897]
./lwm2mclient(registration_deregister+0xcd)[0x414054]
./lwm2mclient(lwm2m_deregister+0x2d)[0x40d902]
./lwm2mclient(lwm2m_close+0x18)[0x40daba]
./lwm2mclient(main+0xc8e)[0x406353]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7f91920f6580]
./lwm2mclient(_start+0x29)[0x404149]
======= Memory map: ========
00400000-00421000 r-xp 00000000 fd:02 17170729                           /home/v/work/wakaama/tests/client/build/lwm2mclient
00620000-00621000 r--p 00020000 fd:02 17170729                           /home/v/work/wakaama/tests/client/build/lwm2mclient
00621000-00622000 rw-p 00021000 fd:02 17170729                           /home/v/work/wakaama/tests/client/build/lwm2mclient
0177e000-0179f000 rw-p 00000000 00:00 0                                  [heap]
7f918c000000-7f918c021000 rw-p 00000000 00:00 0 
7f918c021000-7f9190000000 ---p 00000000 00:00 0 
7f9191ebf000-7f9191ed5000 r-xp 00000000 fd:00 2495703                    /usr/lib64/libgcc_s-5.3.1-20151207.so.1
7f9191ed5000-7f91920d4000 ---p 00016000 fd:00 2495703                    /usr/lib64/libgcc_s-5.3.1-20151207.so.1
7f91920d4000-7f91920d5000 r--p 00015000 fd:00 2495703                    /usr/lib64/libgcc_s-5.3.1-20151207.so.1
7f91920d5000-7f91920d6000 rw-p 00016000 fd:00 2495703                    /usr/lib64/libgcc_s-5.3.1-20151207.so.1
7f91920d6000-7f919228d000 r-xp 00000000 fd:00 2498862                    /usr/lib64/libc-2.22.so
7f919228d000-7f919248d000 ---p 001b7000 fd:00 2498862                    /usr/lib64/libc-2.22.so
7f919248d000-7f9192491000 r--p 001b7000 fd:00 2498862                    /usr/lib64/libc-2.22.so
7f9192491000-7f9192493000 rw-p 001bb000 fd:00 2498862                    /usr/lib64/libc-2.22.so
7f9192493000-7f9192497000 rw-p 00000000 00:00 0 
7f9192497000-7f91924b8000 r-xp 00000000 fd:00 2499399                    /usr/lib64/ld-2.22.so
7f9192690000-7f9192693000 rw-p 00000000 00:00 0 
7f91926b4000-7f91926b7000 rw-p 00000000 00:00 0 
7f91926b7000-7f91926b8000 r--p 00020000 fd:00 2499399                    /usr/lib64/ld-2.22.so
7f91926b8000-7f91926b9000 rw-p 00021000 fd:00 2499399                    /usr/lib64/ld-2.22.so
7f91926b9000-7f91926ba000 rw-p 00000000 00:00 0 
7ffc6d4bb000-7ffc6d4dc000 rw-p 00000000 00:00 0                          [stack]
7ffc6d5a3000-7ffc6d5a5000 r--p 00000000 00:00 0                          [vvar]
7ffc6d5a5000-7ffc6d5a7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by dnav** [comment]
Hi,
with latest version, using "lwm2mclient -4", I do not have any crash when deregistering.

Could you specify the steps to reproduce the issue ?

Thanks
